import { createStore } from 'solid-js/store';

// ---------------------------------------------------------------------------
// Public types
// ---------------------------------------------------------------------------

/**
 * Barycentric coordinates [u, v, w] for a point on a triangle.
 * u + v + w = 1.  Stored as a 3-tuple of numbers.
 */
export type BarycentricUV = [number, number, number];

/**
 * Sampled FEA quantities at a probe point.
 * All fields are null when the relevant channel is not populated upstream.
 */
export interface ProbeSample {
  /** Displacement vector (displaced − original), in mesh units. Null when displaced_positions absent. */
  displacement: [number, number, number] | null;
  /** von Mises stress scalar. Null when the 'vonMises' scalar channel is absent. */
  vonMises: number | null;
  /** All interpolated scalar channels (including 'vonMises' when present). */
  scalars: Record<string, number>;
  /** All interpolated 3-component vector channels. */
  vectors: Record<string, [number, number, number]>;
}

/**
 * A pinned probe point on a mesh surface.
 * Identified by (entity_path, face_id, barycentric_uv) so it can be
 * re-sampled after parameter changes.
 */
export interface PinnedProbe {
  /** Unique monotonic id generated by the store (e.g. 'probe-0'). */
  id: string;
  /** Entity path of the mesh (matches the mesh's name attribute). */
  entity_path: string;
  /** Triangle face index (0-based) within the entity's index buffer. */
  face_id: number;
  /** Barycentric weights [u, v, w] within the face. */
  barycentric_uv: BarycentricUV;
  /** Last sampled values, or null before the first sample. */
  sample: ProbeSample | null;
  /**
   * Whether the probe is stale — set when resampleAll() cannot resolve the
   * entity/face on the current mesh (topology change). The sample is preserved
   * (last-known value) and the marker is greyed.
   */
  stale: boolean;
}

// ---------------------------------------------------------------------------
// Store state and interface
// ---------------------------------------------------------------------------

export interface ProbeStoreState {
  probes: PinnedProbe[];
}

export interface ProbeStore {
  state: ProbeStoreState;
  /**
   * Add a new pinned probe. Returns the new probe's id.
   * The probe is appended with stale=false.
   */
  addProbe(opts: {
    entity_path: string;
    face_id: number;
    barycentric_uv: BarycentricUV;
    sample: ProbeSample | null;
  }): string;
  /** Remove the probe with the given id. No-op for unknown ids. */
  removeProbe(id: string): void;
  /** Remove all probes. */
  clear(): void;
  /**
   * Replace a probe's sample and set stale=false.
   * Used on successful re-evaluation. No-op for unknown ids.
   */
  updateSample(id: string, sample: ProbeSample): void;
  /**
   * Set a probe's stale flag to true while preserving its last-known sample.
   * Called when resampleAll() cannot resolve the entity/face on the current mesh.
   * No-op for unknown ids.
   */
  markStale(id: string): void;
}

// ---------------------------------------------------------------------------
// Factory
// ---------------------------------------------------------------------------

/**
 * Create the probe store.
 *
 * Mirrors createFeaModeStore / createViewportStore: returns a reactive
 * `state` object and mutation methods.  Pure SolidJS — no Three.js.
 */
export function createProbeStore(): ProbeStore {
  const [state, setState] = createStore<ProbeStoreState>({ probes: [] });

  // Monotonic counter for deterministic id generation (no Date.now / Math.random).
  let counter = 0;

  function addProbe(opts: {
    entity_path: string;
    face_id: number;
    barycentric_uv: BarycentricUV;
    sample: ProbeSample | null;
  }): string {
    const id = `probe-${counter++}`;
    const probe: PinnedProbe = {
      id,
      entity_path: opts.entity_path,
      face_id: opts.face_id,
      barycentric_uv: opts.barycentric_uv,
      sample: opts.sample,
      stale: false,
    };
    setState('probes', (prev) => [...prev, probe]);
    return id;
  }

  function removeProbe(id: string): void {
    setState('probes', (prev) => prev.filter((p) => p.id !== id));
  }

  function clear(): void {
    setState('probes', []);
  }

  function updateSample(id: string, sample: ProbeSample): void {
    setState('probes', (prev) =>
      prev.map((p) => (p.id === id ? { ...p, sample, stale: false } : p))
    );
  }

  function markStale(id: string): void {
    setState('probes', (prev) =>
      prev.map((p) => (p.id === id ? { ...p, stale: true } : p))
    );
  }

  return { state, addProbe, removeProbe, clear, updateSample, markStale };
}
