// Include the cxx-generated header first for shared type definitions (Point3, BBox, TessResult)
#include "reify-kernel-occt/src/ffi.rs.h"
#include "occt_wrapper.h"
// Generated by build.rs from src/floor_constants.rs — provides
// namespace occt { constexpr double CPP_LINE_WIRE_MIN_LENGTH_SQ = ...; }
#include "line_wire_floors.h"

// stdlib
#include <set>
#include <string>
#include <vector>

// OCCT primitives
#include <BRepPrimAPI_MakeBox.hxx>
#include <BRepPrimAPI_MakeCylinder.hxx>
#include <BRepPrimAPI_MakeSphere.hxx>

// OCCT booleans
#include <BRepAlgoAPI_Fuse.hxx>
#include <BRepAlgoAPI_Cut.hxx>
#include <BRepAlgoAPI_Common.hxx>

// OCCT fillet / chamfer
#include <BRepFilletAPI_MakeFillet.hxx>
#include <BRepFilletAPI_MakeChamfer.hxx>
#include <TopExp.hxx>
#include <TopExp_Explorer.hxx>
#include <TopTools_IndexedDataMapOfShapeListOfShape.hxx>
#include <TopTools_IndexedMapOfShape.hxx>
#include <TopTools_ListIteratorOfListOfShape.hxx>
#include <TopoDS.hxx>

// OCCT draft
#include <BRepOffsetAPI_DraftAngle.hxx>

// OCCT loft / offset / shell / thicken
#include <BRepOffsetAPI_ThruSections.hxx>
#include <BRepOffsetAPI_MakeOffsetShape.hxx>
#include <BRepOffsetAPI_MakeThickSolid.hxx>
#include <TopTools_ListOfShape.hxx>

// OCCT prism (extrude) and revolve
#include <BRepPrimAPI_MakePrism.hxx>
#include <BRepPrimAPI_MakeRevol.hxx>

// OCCT edge/wire/face/solid construction
#include <BRepBuilderAPI_MakeEdge.hxx>
#include <BRepBuilderAPI_MakeWire.hxx>
#include <BRepBuilderAPI_MakeFace.hxx>
#include <BRepBuilderAPI_MakeSolid.hxx>

// OCCT pipe (sweep)
#include <BRepOffsetAPI_MakePipe.hxx>
#include <BRepOffsetAPI_MakePipeShell.hxx>

// OCCT edge/wire/face construction
#include <BRepBuilderAPI_MakeEdge.hxx>
#include <BRepBuilderAPI_MakeWire.hxx>
#include <BRepBuilderAPI_MakeFace.hxx>
#include <Geom_Circle.hxx>
#include <Geom_Plane.hxx>
#include <Geom_Surface.hxx>

// OCCT curve construction (arc, helix, interp, bezier, nurbs)
#include <Geom_CylindricalSurface.hxx>
#include <Geom2d_Line.hxx>
#include <GeomAPI_PointsToBSpline.hxx>
#include <Geom_BezierCurve.hxx>
#include <Geom_BSplineCurve.hxx>
#include <TColgp_Array1OfPnt.hxx>
#include <TColStd_Array1OfReal.hxx>
#include <TColStd_Array1OfInteger.hxx>

// OCCT shape utilities
#include <BRepLib.hxx>

// OCCT transforms
#include <BRepBuilderAPI_Transform.hxx>
#include <gp_Trsf.hxx>
#include <gp_Vec.hxx>
#include <gp_Ax1.hxx>
#include <gp_Ax2.hxx>
#include <gp_Dir.hxx>
#include <gp_Pnt.hxx>

// OCCT properties + surface adaptor
#include <BRepGProp.hxx>
#include <GProp_GProps.hxx>
#include <BRepAdaptor_Surface.hxx>
#include <BRepAdaptor_CompCurve.hxx>
#include <Bnd_Box.hxx>
#include <BRepBndLib.hxx>

// OCCT distance
#include <BRepExtrema_DistShapeShape.hxx>

// OCCT conformance queries
#include <BRepCheck_Analyzer.hxx>
#include <ShapeAnalysis_Shell.hxx>

// OCCT STEP export
#include <STEPControl_Writer.hxx>
#include <Standard_Failure.hxx>

// OCCT BRep serialization
#include <BRepTools.hxx>
#include <BRep_Builder.hxx>

// OCCT mesh
#include <BRepMesh_IncrementalMesh.hxx>
#include <BRep_Tool.hxx>
#include <Poly_Triangulation.hxx>
#include <TopLoc_Location.hxx>

#include <sstream>
#include <fstream>
#include <cstdio>
#include <cmath>
#include <mutex>
#include <stdexcept>

namespace occt {

// --- Validation thresholds ---
//
// DEFENSE-IN-DEPTH: The Rust layer validates first with stricter thresholds
// (AXIS_MAG_SQ_MIN = 1e-12). These C++ thresholds are a safety net for any
// future code paths that may bypass the Rust layer (e.g., direct FFI testing,
// hot-path optimizations).

/// Minimum squared magnitude for axis/direction vectors (catches true zeros and denormals).
constexpr double CPP_AXIS_MAG_SQ_MIN = 1e-30;

/// Minimum magnitude for direction vectors used in normalization (linear_pattern, normals).
constexpr double CPP_DIR_MAG_MIN = 1e-10;

/// Minimum absolute angle for revolve operations (catches effectively-zero angles).
constexpr double CPP_ANGLE_ABS_MIN = 1e-30;

/// Minimum squared length for make_line_wire endpoints (m²).
/// Rejects degenerate wires below this threshold (see src/floor_constants.rs
/// for the exact value; the minimum segment length is its square root).
/// Defense-in-depth against degenerate wires: the Rust layer applies an
/// earlier primary floor, and OCCT's own Precision::Confusion guard provides
/// a final backstop. This C++ constant sits between the two, catching inputs
/// that bypass the Rust layer without colliding with the axis-vector
/// CPP_AXIS_MAG_SQ_MIN sites in make_prism / make_revolve.
///
/// SINGLE SOURCE: the canonical value lives in src/floor_constants.rs.
/// build.rs reads it and emits it into line_wire_floors.h (included above),
/// so this symbol is defined by the generated header — not here.
/// The layered invariant RUST_LINE_WIRE_MIN_LENGTH_SQ < CPP_LINE_WIRE_MIN_LENGTH_SQ
/// is enforced at compile time by `const _: () = assert!(...)` in lib.rs.

// --- Primitive construction ---

std::unique_ptr<OcctShape> make_box(double width, double height, double depth) {
    try {
        gp_Pnt corner(-width / 2.0, -height / 2.0, -depth / 2.0);
        BRepPrimAPI_MakeBox maker(corner, width, height, depth);
        maker.Build();
        if (!maker.IsDone()) {
            throw std::runtime_error("BRepPrimAPI_MakeBox failed");
        }
        auto result = std::make_unique<OcctShape>();
        result->shape = maker.Shape();
        return result;
    } catch (Standard_Failure const& e) {
        throw std::runtime_error(std::string("OCCT make_box: ") + e.GetMessageString());
    } catch (std::exception const& e) {
        throw std::runtime_error(std::string("OCCT make_box: unexpected: ") + e.what());
    } catch (...) {
        throw std::runtime_error("OCCT make_box: unknown C++ exception");
    }
}

std::unique_ptr<OcctShape> make_cylinder(double radius, double height) {
    try {
        BRepPrimAPI_MakeCylinder maker(radius, height);
        maker.Build();
        if (!maker.IsDone()) {
            throw std::runtime_error("BRepPrimAPI_MakeCylinder failed");
        }
        auto result = std::make_unique<OcctShape>();
        result->shape = maker.Shape();
        return result;
    } catch (Standard_Failure const& e) {
        throw std::runtime_error(std::string("OCCT make_cylinder: ") + e.GetMessageString());
    } catch (std::exception const& e) {
        throw std::runtime_error(std::string("OCCT make_cylinder: unexpected: ") + e.what());
    } catch (...) {
        throw std::runtime_error("OCCT make_cylinder: unknown C++ exception");
    }
}

std::unique_ptr<OcctShape> make_sphere(double radius) {
    try {
        BRepPrimAPI_MakeSphere maker(radius);
        maker.Build();
        if (!maker.IsDone()) {
            throw std::runtime_error("BRepPrimAPI_MakeSphere failed");
        }
        auto result = std::make_unique<OcctShape>();
        result->shape = maker.Shape();
        return result;
    } catch (Standard_Failure const& e) {
        throw std::runtime_error(std::string("OCCT make_sphere: ") + e.GetMessageString());
    } catch (std::exception const& e) {
        throw std::runtime_error(std::string("OCCT make_sphere: unexpected: ") + e.what());
    } catch (...) {
        throw std::runtime_error("OCCT make_sphere: unknown C++ exception");
    }
}

// --- Boolean operations ---

std::unique_ptr<OcctShape> boolean_fuse(const OcctShape& left, const OcctShape& right) {
    try {
        BRepAlgoAPI_Fuse fuse(left.shape, right.shape);
        fuse.Build();
        if (!fuse.IsDone()) {
            throw std::runtime_error("BRepAlgoAPI_Fuse failed");
        }
        auto result = std::make_unique<OcctShape>();
        result->shape = fuse.Shape();
        return result;
    } catch (Standard_Failure const& e) {
        throw std::runtime_error(std::string("OCCT boolean_fuse: ") + e.GetMessageString());
    } catch (std::exception const& e) {
        throw std::runtime_error(std::string("OCCT boolean_fuse: unexpected: ") + e.what());
    } catch (...) {
        throw std::runtime_error("OCCT boolean_fuse: unknown C++ exception");
    }
}

std::unique_ptr<OcctShape> boolean_cut(const OcctShape& left, const OcctShape& right) {
    try {
        BRepAlgoAPI_Cut cut(left.shape, right.shape);
        cut.Build();
        if (!cut.IsDone()) {
            throw std::runtime_error("BRepAlgoAPI_Cut failed");
        }
        auto result = std::make_unique<OcctShape>();
        result->shape = cut.Shape();
        return result;
    } catch (Standard_Failure const& e) {
        throw std::runtime_error(std::string("OCCT boolean_cut: ") + e.GetMessageString());
    } catch (std::exception const& e) {
        throw std::runtime_error(std::string("OCCT boolean_cut: unexpected: ") + e.what());
    } catch (...) {
        throw std::runtime_error("OCCT boolean_cut: unknown C++ exception");
    }
}

std::unique_ptr<OcctShape> boolean_common(const OcctShape& left, const OcctShape& right) {
    try {
        BRepAlgoAPI_Common common(left.shape, right.shape);
        common.Build();
        if (!common.IsDone()) {
            throw std::runtime_error("BRepAlgoAPI_Common failed");
        }
        auto result = std::make_unique<OcctShape>();
        result->shape = common.Shape();
        return result;
    } catch (Standard_Failure const& e) {
        throw std::runtime_error(std::string("OCCT boolean_common: ") + e.GetMessageString());
    } catch (std::exception const& e) {
        throw std::runtime_error(std::string("OCCT boolean_common: unexpected: ") + e.what());
    } catch (...) {
        throw std::runtime_error("OCCT boolean_common: unknown C++ exception");
    }
}

// --- Modifications ---

std::unique_ptr<OcctShape> fillet_all_edges(const OcctShape& shape, double radius) {
    try {
        BRepFilletAPI_MakeFillet fillet(shape.shape);
        for (TopExp_Explorer ex(shape.shape, TopAbs_EDGE); ex.More(); ex.Next()) {
            fillet.Add(radius, TopoDS::Edge(ex.Current()));
        }
        fillet.Build();
        if (!fillet.IsDone()) {
            throw std::runtime_error("BRepFilletAPI_MakeFillet failed");
        }
        auto result = std::make_unique<OcctShape>();
        result->shape = fillet.Shape();
        return result;
    } catch (Standard_Failure const& e) {
        throw std::runtime_error(std::string("OCCT fillet_all_edges: ") + e.GetMessageString());
    } catch (std::exception const& e) {
        throw std::runtime_error(std::string("OCCT fillet_all_edges: unexpected: ") + e.what());
    } catch (...) {
        throw std::runtime_error("OCCT fillet_all_edges: unknown C++ exception");
    }
}

std::unique_ptr<OcctShape> chamfer_all_edges(const OcctShape& shape, double distance) {
    try {
        BRepFilletAPI_MakeChamfer chamfer(shape.shape);
        for (TopExp_Explorer ex(shape.shape, TopAbs_EDGE); ex.More(); ex.Next()) {
            chamfer.Add(distance, TopoDS::Edge(ex.Current()));
        }
        chamfer.Build();
        if (!chamfer.IsDone()) {
            throw std::runtime_error("BRepFilletAPI_MakeChamfer failed");
        }
        auto result = std::make_unique<OcctShape>();
        result->shape = chamfer.Shape();
        return result;
    } catch (Standard_Failure const& e) {
        throw std::runtime_error(std::string("OCCT chamfer_all_edges: ") + e.GetMessageString());
    } catch (std::exception const& e) {
        throw std::runtime_error(std::string("OCCT chamfer_all_edges: unexpected: ") + e.what());
    } catch (...) {
        throw std::runtime_error("OCCT chamfer_all_edges: unknown C++ exception");
    }
}

// --- Transforms ---

std::unique_ptr<OcctShape> translate_shape(const OcctShape& shape, double dx, double dy, double dz) {
    try {
        gp_Trsf trsf;
        trsf.SetTranslation(gp_Vec(dx, dy, dz));
        BRepBuilderAPI_Transform transform(shape.shape, trsf, true);
        transform.Build();
        if (!transform.IsDone()) {
            throw std::runtime_error("BRepBuilderAPI_Transform (translate) failed");
        }
        auto result = std::make_unique<OcctShape>();
        result->shape = transform.Shape();
        return result;
    } catch (Standard_Failure const& e) {
        throw std::runtime_error(std::string("OCCT translate_shape: ") + e.GetMessageString());
    } catch (std::exception const& e) {
        throw std::runtime_error(std::string("OCCT translate_shape: unexpected: ") + e.what());
    } catch (...) {
        throw std::runtime_error("OCCT translate_shape: unknown C++ exception");
    }
}

std::unique_ptr<OcctShape> rotate_shape(const OcctShape& shape, double ax, double ay, double az, double angle_rad) {
    try {
        gp_Ax1 axis(gp_Pnt(0, 0, 0), gp_Dir(ax, ay, az));
        gp_Trsf trsf;
        trsf.SetRotation(axis, angle_rad);
        BRepBuilderAPI_Transform transform(shape.shape, trsf, true);
        transform.Build();
        if (!transform.IsDone()) {
            throw std::runtime_error("BRepBuilderAPI_Transform (rotate) failed");
        }
        auto result = std::make_unique<OcctShape>();
        result->shape = transform.Shape();
        return result;
    } catch (Standard_Failure const& e) {
        throw std::runtime_error(std::string("OCCT rotate_shape: ") + e.GetMessageString());
    } catch (std::exception const& e) {
        throw std::runtime_error(std::string("OCCT rotate_shape: unexpected: ") + e.what());
    } catch (...) {
        throw std::runtime_error("OCCT rotate_shape: unknown C++ exception");
    }
}

std::unique_ptr<OcctShape> scale_shape(const OcctShape& shape, double factor, double cx, double cy, double cz) {
    try {
        gp_Trsf trsf;
        trsf.SetScale(gp_Pnt(cx, cy, cz), factor);
        BRepBuilderAPI_Transform transform(shape.shape, trsf, true);
        transform.Build();
        if (!transform.IsDone()) {
            throw std::runtime_error("BRepBuilderAPI_Transform (scale) failed");
        }
        auto result = std::make_unique<OcctShape>();
        result->shape = transform.Shape();
        return result;
    } catch (Standard_Failure const& e) {
        throw std::runtime_error(std::string("OCCT scale_shape: ") + e.GetMessageString());
    } catch (std::exception const& e) {
        throw std::runtime_error(std::string("OCCT scale_shape: unexpected: ") + e.what());
    } catch (...) {
        throw std::runtime_error("OCCT scale_shape: unknown C++ exception");
    }
}

std::unique_ptr<OcctShape> rotate_around_shape(const OcctShape& shape,
    double px, double py, double pz,
    double ax, double ay, double az,
    double angle_rad) {
    try {
        // gp_Ax1 defines an axis through a point with a direction.
        // trsf.SetRotation(axis, angle) then rotates around that axis,
        // correctly handling the non-origin pivot point.
        gp_Ax1 axis(gp_Pnt(px, py, pz), gp_Dir(ax, ay, az));
        gp_Trsf trsf;
        trsf.SetRotation(axis, angle_rad);
        BRepBuilderAPI_Transform transform(shape.shape, trsf, true);
        transform.Build();
        if (!transform.IsDone()) {
            throw std::runtime_error("BRepBuilderAPI_Transform (rotate_around) failed");
        }
        auto result = std::make_unique<OcctShape>();
        result->shape = transform.Shape();
        return result;
    } catch (Standard_Failure const& e) {
        throw std::runtime_error(std::string("OCCT rotate_around_shape: ") + e.GetMessageString());
    } catch (std::exception const& e) {
        throw std::runtime_error(std::string("OCCT rotate_around_shape: unexpected: ") + e.what());
    } catch (...) {
        throw std::runtime_error("OCCT rotate_around_shape: unknown C++ exception");
    }
}

// --- Mirror / Pattern ---

std::unique_ptr<OcctShape> mirror_shape(const OcctShape& shape,
    double ox, double oy, double oz,
    double nx, double ny, double nz) {
    try {
        gp_Ax2 mirror_plane(gp_Pnt(ox, oy, oz), gp_Dir(nx, ny, nz));
        gp_Trsf trsf;
        trsf.SetMirror(mirror_plane);
        BRepBuilderAPI_Transform transform(shape.shape, trsf, true);
        transform.Build();
        if (!transform.IsDone()) {
            throw std::runtime_error("BRepBuilderAPI_Transform (mirror) failed");
        }
        auto result = std::make_unique<OcctShape>();
        result->shape = transform.Shape();
        return result;
    } catch (Standard_Failure const& e) {
        throw std::runtime_error(std::string("OCCT mirror_shape: ") + e.GetMessageString());
    } catch (std::exception const& e) {
        throw std::runtime_error(std::string("OCCT mirror_shape: unexpected: ") + e.what());
    } catch (...) {
        throw std::runtime_error("OCCT mirror_shape: unknown C++ exception");
    }
}

std::unique_ptr<OcctShape> linear_pattern(const OcctShape& shape,
    double dx, double dy, double dz,
    uint32_t count, double spacing) {
    try {
        if (count < 1) {
            throw std::runtime_error("linear_pattern: count must be >= 1");
        }
        // Normalize direction
        double mag = std::sqrt(dx*dx + dy*dy + dz*dz);
        if (mag < CPP_DIR_MAG_MIN) {
            throw std::runtime_error("linear_pattern: direction must be non-zero");
        }
        double ndx = dx / mag, ndy = dy / mag, ndz = dz / mag;

        // Start with the original shape
        TopoDS_Shape accumulated = shape.shape;

        for (uint32_t i = 1; i < count; ++i) {
            double dist = spacing * static_cast<double>(i);
            gp_Trsf trsf;
            trsf.SetTranslation(gp_Vec(ndx * dist, ndy * dist, ndz * dist));
            BRepBuilderAPI_Transform transform(shape.shape, trsf, true);
            transform.Build();
            if (!transform.IsDone()) {
                throw std::runtime_error("linear_pattern: transform failed");
            }
            BRepAlgoAPI_Fuse fuse(accumulated, transform.Shape());
            fuse.Build();
            if (!fuse.IsDone()) {
                throw std::runtime_error("linear_pattern: fuse failed");
            }
            accumulated = fuse.Shape();
        }

        auto result = std::make_unique<OcctShape>();
        result->shape = accumulated;
        return result;
    } catch (Standard_Failure const& e) {
        throw std::runtime_error(std::string("OCCT linear_pattern: ") + e.GetMessageString());
    } catch (std::exception const& e) {
        throw std::runtime_error(std::string("OCCT linear_pattern: unexpected: ") + e.what());
    } catch (...) {
        throw std::runtime_error("OCCT linear_pattern: unknown C++ exception");
    }
}

std::unique_ptr<OcctShape> linear_pattern_2d(const OcctShape& shape,
    double dx1, double dy1, double dz1,
    uint32_t count1, double spacing1,
    double dx2, double dy2, double dz2,
    uint32_t count2, double spacing2) {
    try {
        if (count1 < 1) {
            throw std::runtime_error("linear_pattern_2d: count1 must be >= 1");
        }
        if (count2 < 1) {
            throw std::runtime_error("linear_pattern_2d: count2 must be >= 1");
        }
        // Normalize direction 1
        double mag1 = std::sqrt(dx1*dx1 + dy1*dy1 + dz1*dz1);
        if (mag1 < CPP_DIR_MAG_MIN) {
            throw std::runtime_error("linear_pattern_2d: direction1 must be non-zero");
        }
        double ndx1 = dx1 / mag1, ndy1 = dy1 / mag1, ndz1 = dz1 / mag1;

        // Normalize direction 2
        double mag2 = std::sqrt(dx2*dx2 + dy2*dy2 + dz2*dz2);
        if (mag2 < CPP_DIR_MAG_MIN) {
            throw std::runtime_error("linear_pattern_2d: direction2 must be non-zero");
        }
        double ndx2 = dx2 / mag2, ndy2 = dy2 / mag2, ndz2 = dz2 / mag2;

        // Start with the original shape
        TopoDS_Shape accumulated = shape.shape;

        for (uint32_t i = 0; i < count1; ++i) {
            for (uint32_t j = 0; j < count2; ++j) {
                if (i == 0 && j == 0) continue; // skip the original
                double tx = static_cast<double>(i) * spacing1 * ndx1
                          + static_cast<double>(j) * spacing2 * ndx2;
                double ty = static_cast<double>(i) * spacing1 * ndy1
                          + static_cast<double>(j) * spacing2 * ndy2;
                double tz = static_cast<double>(i) * spacing1 * ndz1
                          + static_cast<double>(j) * spacing2 * ndz2;
                gp_Trsf trsf;
                trsf.SetTranslation(gp_Vec(tx, ty, tz));
                BRepBuilderAPI_Transform transform(shape.shape, trsf, true);
                transform.Build();
                if (!transform.IsDone()) {
                    throw std::runtime_error("linear_pattern_2d: transform failed");
                }
                BRepAlgoAPI_Fuse fuse(accumulated, transform.Shape());
                fuse.Build();
                if (!fuse.IsDone()) {
                    throw std::runtime_error("linear_pattern_2d: fuse failed");
                }
                accumulated = fuse.Shape();
            }
        }

        auto result = std::make_unique<OcctShape>();
        result->shape = accumulated;
        return result;
    } catch (Standard_Failure const& e) {
        throw std::runtime_error(std::string("OCCT linear_pattern_2d: ") + e.GetMessageString());
    } catch (std::exception const& e) {
        throw std::runtime_error(std::string("OCCT linear_pattern_2d: unexpected: ") + e.what());
    } catch (...) {
        throw std::runtime_error("OCCT linear_pattern_2d: unknown C++ exception");
    }
}

std::unique_ptr<OcctShape> circular_pattern(const OcctShape& shape,
    double ox, double oy, double oz,
    double ax, double ay, double az,
    uint32_t count, double total_angle) {
    try {
        if (count < 1) {
            throw std::runtime_error("circular_pattern: count must be >= 1");
        }
        gp_Ax1 axis(gp_Pnt(ox, oy, oz), gp_Dir(ax, ay, az));

        TopoDS_Shape accumulated = shape.shape;

        for (uint32_t i = 1; i < count; ++i) {
            double angle_i = total_angle * static_cast<double>(i) / static_cast<double>(count);
            gp_Trsf trsf;
            trsf.SetRotation(axis, angle_i);
            BRepBuilderAPI_Transform transform(shape.shape, trsf, true);
            transform.Build();
            if (!transform.IsDone()) {
                throw std::runtime_error("circular_pattern: transform failed");
            }
            BRepAlgoAPI_Fuse fuse(accumulated, transform.Shape());
            fuse.Build();
            if (!fuse.IsDone()) {
                throw std::runtime_error("circular_pattern: fuse failed");
            }
            accumulated = fuse.Shape();
        }

        auto result = std::make_unique<OcctShape>();
        result->shape = accumulated;
        return result;
    } catch (Standard_Failure const& e) {
        throw std::runtime_error(std::string("OCCT circular_pattern: ") + e.GetMessageString());
    } catch (std::exception const& e) {
        throw std::runtime_error(std::string("OCCT circular_pattern: unexpected: ") + e.what());
    } catch (...) {
        throw std::runtime_error("OCCT circular_pattern: unknown C++ exception");
    }
}

std::unique_ptr<OcctShape> arbitrary_pattern(const OcctShape& shape,
    const rust::Vec<double>& flat_transforms, uint32_t num_transforms) {
    try {
        if (num_transforms == 0) {
            throw std::runtime_error("arbitrary_pattern: num_transforms must be > 0");
        }
        if (flat_transforms.size() != static_cast<size_t>(num_transforms) * 3) {
            throw std::runtime_error("arbitrary_pattern: flat_transforms.size() != num_transforms * 3");
        }

        // Start with the original shape
        TopoDS_Shape accumulated = shape.shape;

        for (uint32_t i = 0; i < num_transforms; ++i) {
            double dx = flat_transforms[i * 3 + 0];
            double dy = flat_transforms[i * 3 + 1];
            double dz = flat_transforms[i * 3 + 2];
            gp_Trsf trsf;
            trsf.SetTranslation(gp_Vec(dx, dy, dz));
            BRepBuilderAPI_Transform transform(shape.shape, trsf, true);
            transform.Build();
            if (!transform.IsDone()) {
                throw std::runtime_error("arbitrary_pattern: transform failed");
            }
            BRepAlgoAPI_Fuse fuse(accumulated, transform.Shape());
            fuse.Build();
            if (!fuse.IsDone()) {
                throw std::runtime_error("arbitrary_pattern: fuse failed");
            }
            accumulated = fuse.Shape();
        }

        auto result = std::make_unique<OcctShape>();
        result->shape = accumulated;
        return result;
    } catch (Standard_Failure const& e) {
        throw std::runtime_error(std::string("OCCT arbitrary_pattern: ") + e.GetMessageString());
    } catch (std::exception const& e) {
        throw std::runtime_error(std::string("OCCT arbitrary_pattern: unexpected: ") + e.what());
    } catch (...) {
        throw std::runtime_error("OCCT arbitrary_pattern: unknown C++ exception");
    }
}

// --- Thicken / Shell ---

std::unique_ptr<OcctShape> thicken_shape(const OcctShape& shape, double offset) {
    try {
        BRepOffsetAPI_MakeOffsetShape maker;
        maker.PerformBySimple(shape.shape, offset);
        if (!maker.IsDone()) {
            throw std::runtime_error("BRepOffsetAPI_MakeOffsetShape failed");
        }
        auto result = std::make_unique<OcctShape>();
        result->shape = maker.Shape();
        return result;
    } catch (Standard_Failure const& e) {
        throw std::runtime_error(std::string("OCCT thicken_shape: ") + e.GetMessageString());
    } catch (std::exception const& e) {
        throw std::runtime_error(std::string("OCCT thicken_shape: unexpected: ") + e.what());
    } catch (...) {
        throw std::runtime_error("OCCT thicken_shape: unknown C++ exception");
    }
}

std::unique_ptr<OcctShape> shell_shape(const OcctShape& shape, double thickness,
    const rust::Vec<uint32_t>& face_indices) {
    try {
        // Collect the faces to remove
        TopTools_ListOfShape faces_to_remove;
        std::vector<TopoDS_Face> all_faces;
        for (TopExp_Explorer ex(shape.shape, TopAbs_FACE); ex.More(); ex.Next()) {
            all_faces.push_back(TopoDS::Face(ex.Current()));
        }
        for (auto idx : face_indices) {
            if (idx < all_faces.size()) {
                faces_to_remove.Append(all_faces[idx]);
            }
        }
        BRepOffsetAPI_MakeThickSolid maker;
        maker.MakeThickSolidByJoin(shape.shape, faces_to_remove, thickness, 1e-3);
        maker.Build();
        if (!maker.IsDone()) {
            throw std::runtime_error("BRepOffsetAPI_MakeThickSolid failed");
        }
        auto result = std::make_unique<OcctShape>();
        result->shape = maker.Shape();
        return result;
    } catch (Standard_Failure const& e) {
        throw std::runtime_error(std::string("OCCT shell_shape: ") + e.GetMessageString());
    } catch (std::exception const& e) {
        throw std::runtime_error(std::string("OCCT shell_shape: unexpected: ") + e.what());
    } catch (...) {
        throw std::runtime_error("OCCT shell_shape: unknown C++ exception");
    }
}

// --- Draft ---

std::unique_ptr<OcctShape> draft_shape(const OcctShape& shape, double angle_rad,
    const OcctShape& plane_shape) {
    try {
        // Extract the neutral plane from plane_shape's first face
        gp_Dir pull_dir;
        gp_Pln neutral_plane;
        {
            TopExp_Explorer face_ex(plane_shape.shape, TopAbs_FACE);
            if (!face_ex.More()) {
                throw std::runtime_error("draft_shape: plane_shape has no faces");
            }
            TopoDS_Face plane_face = TopoDS::Face(face_ex.Current());
            Handle(Geom_Surface) surface = BRep_Tool::Surface(plane_face);
            Handle(Geom_Plane) geom_plane = Handle(Geom_Plane)::DownCast(surface);
            if (geom_plane.IsNull()) {
                throw std::runtime_error(
                    "draft_shape: plane_shape does not contain a planar face");
            }
            neutral_plane = geom_plane->Pln();
            pull_dir = neutral_plane.Axis().Direction();
        }

        BRepOffsetAPI_DraftAngle drafter(shape.shape);

        // Add draft to all faces
        for (TopExp_Explorer ex(shape.shape, TopAbs_FACE); ex.More(); ex.Next()) {
            TopoDS_Face face = TopoDS::Face(ex.Current());
            drafter.Add(face, pull_dir, angle_rad, neutral_plane);
            if (!drafter.AddDone()) {
                // Some faces may not be draftable - skip them
                drafter.Remove(face);
            }
        }

        drafter.Build();
        if (!drafter.IsDone()) {
            throw std::runtime_error("BRepOffsetAPI_DraftAngle failed");
        }
        auto result = std::make_unique<OcctShape>();
        result->shape = drafter.Shape();
        return result;
    } catch (Standard_Failure const& e) {
        throw std::runtime_error(std::string("OCCT draft_shape: ") + e.GetMessageString());
    } catch (std::exception const& e) {
        throw std::runtime_error(std::string("OCCT draft_shape: unexpected: ") + e.what());
    } catch (...) {
        throw std::runtime_error("OCCT draft_shape: unknown C++ exception");
    }
}

// --- Wire helpers ---

std::unique_ptr<OcctShape> make_circle_wire(double radius, double z_height) {
    try {
        if (!(std::isfinite(radius) && radius > 0.0)) {
            throw std::runtime_error("make_circle_wire: radius must be finite and positive");
        }
        gp_Ax2 axes(gp_Pnt(0, 0, z_height), gp_Dir(0, 0, 1));
        Handle(Geom_Circle) circle = new Geom_Circle(axes, radius);
        BRepBuilderAPI_MakeEdge edgeBuilder(circle);
        if (!edgeBuilder.IsDone()) {
            throw std::runtime_error("make_circle_wire: MakeEdge failed");
        }
        TopoDS_Edge edge = edgeBuilder.Edge();
        BRepBuilderAPI_MakeWire wireBuilder(edge);
        if (!wireBuilder.IsDone()) {
            throw std::runtime_error("make_circle_wire: MakeWire failed");
        }
        TopoDS_Wire wire = wireBuilder.Wire();
        auto result = std::make_unique<OcctShape>();
        result->shape = wire;
        return result;
    } catch (Standard_Failure const& e) {
        throw std::runtime_error(std::string("OCCT make_circle_wire: ") + e.GetMessageString());
    } catch (std::exception const& e) {
        throw std::runtime_error(std::string("OCCT make_circle_wire: unexpected: ") + e.what());
    } catch (...) {
        throw std::runtime_error("OCCT make_circle_wire: unknown C++ exception");
    }
}

std::unique_ptr<OcctShape> make_circle_face(double radius, double z_height) {
    try {
        if (!(std::isfinite(radius) && radius > 0.0)) {
            throw std::runtime_error("make_circle_face: radius must be finite and positive");
        }
        gp_Ax2 axes(gp_Pnt(0, 0, z_height), gp_Dir(0, 0, 1));
        Handle(Geom_Circle) circle = new Geom_Circle(axes, radius);
        BRepBuilderAPI_MakeEdge edgeBuilder(circle);
        if (!edgeBuilder.IsDone()) {
            throw std::runtime_error("make_circle_face: MakeEdge failed");
        }
        TopoDS_Edge edge = edgeBuilder.Edge();
        BRepBuilderAPI_MakeWire wireBuilder(edge);
        if (!wireBuilder.IsDone()) {
            throw std::runtime_error("make_circle_face: MakeWire failed");
        }
        TopoDS_Wire wire = wireBuilder.Wire();
        BRepBuilderAPI_MakeFace faceBuilder(wire, Standard_True);
        if (!faceBuilder.IsDone()) {
            throw std::runtime_error("make_circle_face: MakeFace failed");
        }
        auto result = std::make_unique<OcctShape>();
        result->shape = faceBuilder.Face();
        return result;
    } catch (Standard_Failure const& e) {
        throw std::runtime_error(std::string("OCCT make_circle_face: ") + e.GetMessageString());
    } catch (std::exception const& e) {
        throw std::runtime_error(std::string("OCCT make_circle_face: unexpected: ") + e.what());
    } catch (...) {
        throw std::runtime_error("OCCT make_circle_face: unknown C++ exception");
    }
}

// --- OcctShapeVec ---

std::unique_ptr<OcctShapeVec> new_shape_vec() {
    return std::make_unique<OcctShapeVec>();
}

void shape_vec_push(OcctShapeVec& vec, const OcctShape& shape) {
    vec.shapes.push_back(shape.shape);
}

// --- make_line_wire ---

std::unique_ptr<OcctShape> make_line_wire(double x1, double y1, double z1,
                                           double x2, double y2, double z2) {
    try {
        gp_Pnt p1(x1, y1, z1);
        gp_Pnt p2(x2, y2, z2);
        double dist_sq = (x2-x1)*(x2-x1) + (y2-y1)*(y2-y1) + (z2-z1)*(z2-z1);
        if (dist_sq < CPP_LINE_WIRE_MIN_LENGTH_SQ) {
            throw std::runtime_error("make_line_wire: start and end points must be distinct");
        }
        BRepBuilderAPI_MakeEdge edgeBuilder(p1, p2);
        if (!edgeBuilder.IsDone()) {
            throw std::runtime_error("make_line_wire: MakeEdge failed");
        }
        TopoDS_Edge edge = edgeBuilder.Edge();
        BRepBuilderAPI_MakeWire wireBuilder(edge);
        if (!wireBuilder.IsDone()) {
            throw std::runtime_error("make_line_wire: MakeWire failed");
        }
        auto result = std::make_unique<OcctShape>();
        result->shape = wireBuilder.Wire();
        return result;
    } catch (Standard_Failure const& e) {
        throw std::runtime_error(std::string("OCCT make_line_wire: ") + e.GetMessageString());
    } catch (std::exception const& e) {
        throw std::runtime_error(std::string("OCCT make_line_wire: unexpected: ") + e.what());
    } catch (...) {
        throw std::runtime_error("OCCT make_line_wire: unknown C++ exception");
    }
}

// --- make_arc_wire ---

std::unique_ptr<OcctShape> make_arc_wire(
    double cx, double cy, double cz,
    double radius,
    double start_angle, double end_angle,
    double ax, double ay, double az) {
    try {
        if (!(std::isfinite(radius) && radius > 0.0)) {
            throw std::runtime_error("make_arc_wire: radius must be finite and positive");
        }
        gp_Dir dir(ax, ay, az);
        gp_Ax2 axes(gp_Pnt(cx, cy, cz), dir);
        Handle(Geom_Circle) circle = new Geom_Circle(axes, radius);
        BRepBuilderAPI_MakeEdge edgeBuilder(circle, start_angle, end_angle);
        if (!edgeBuilder.IsDone()) {
            throw std::runtime_error("make_arc_wire: MakeEdge failed");
        }
        BRepBuilderAPI_MakeWire wireBuilder(edgeBuilder.Edge());
        if (!wireBuilder.IsDone()) {
            throw std::runtime_error("make_arc_wire: MakeWire failed");
        }
        auto result = std::make_unique<OcctShape>();
        result->shape = wireBuilder.Wire();
        return result;
    } catch (Standard_Failure const& e) {
        throw std::runtime_error(std::string("OCCT make_arc_wire: ") + e.GetMessageString());
    } catch (std::exception const& e) {
        throw std::runtime_error(std::string("OCCT make_arc_wire: unexpected: ") + e.what());
    } catch (...) {
        throw std::runtime_error("OCCT make_arc_wire: unknown C++ exception");
    }
}

// --- make_helix_wire ---

std::unique_ptr<OcctShape> make_helix_wire(
    double radius, double pitch, double height) {
    try {
        if (!(std::isfinite(radius) && radius > 0.0)) {
            throw std::runtime_error("make_helix_wire: radius must be finite and positive");
        }
        if (!(std::isfinite(pitch) && pitch > 0.0)) {
            throw std::runtime_error("make_helix_wire: pitch must be finite and positive");
        }
        if (!(std::isfinite(height) && height > 0.0)) {
            throw std::runtime_error("make_helix_wire: height must be finite and positive");
        }
        // Create a cylindrical surface
        gp_Ax2 ax2(gp_Pnt(0, 0, 0), gp_Dir(0, 0, 1));
        Handle(Geom_CylindricalSurface) cylinder = new Geom_CylindricalSurface(ax2, radius);
        // Helix as a 2D line on the cylindrical surface.
        // In (u,v) space: u = angle, v = height along axis.
        // A line from (0,0) with slope = pitch/(2*PI) traces a helix.
        double n_turns = height / pitch;
        double u_length = n_turns * 2.0 * M_PI;
        gp_Pnt2d origin2d(0.0, 0.0);
        gp_Dir2d dir2d(u_length, height);
        Handle(Geom2d_Line) line2d = new Geom2d_Line(origin2d, dir2d);
        double param_end = std::sqrt(u_length * u_length + height * height);
        BRepBuilderAPI_MakeEdge edgeBuilder(line2d, cylinder, 0.0, param_end);
        if (!edgeBuilder.IsDone()) {
            throw std::runtime_error("make_helix_wire: MakeEdge failed");
        }
        BRepBuilderAPI_MakeWire wireBuilder(edgeBuilder.Edge());
        if (!wireBuilder.IsDone()) {
            throw std::runtime_error("make_helix_wire: MakeWire failed");
        }
        auto result = std::make_unique<OcctShape>();
        result->shape = wireBuilder.Wire();
        return result;
    } catch (Standard_Failure const& e) {
        throw std::runtime_error(std::string("OCCT make_helix_wire: ") + e.GetMessageString());
    } catch (std::exception const& e) {
        throw std::runtime_error(std::string("OCCT make_helix_wire: unexpected: ") + e.what());
    } catch (...) {
        throw std::runtime_error("OCCT make_helix_wire: unknown C++ exception");
    }
}

// --- make_polyline_wire ---

std::unique_ptr<OcctShape> make_polyline_wire(
    rust::Slice<const double> coords, size_t n_points) {
    try {
        if (n_points < 2) {
            throw std::runtime_error("make_polyline_wire: requires at least 2 points");
        }
        if (coords.size() != n_points * 3) {
            throw std::runtime_error("make_polyline_wire: coords length must be 3 * n_points");
        }
        BRepBuilderAPI_MakeWire wireBuilder;
        for (size_t i = 0; i + 1 < n_points; ++i) {
            gp_Pnt p1(coords[3*i],     coords[3*i + 1],   coords[3*i + 2]);
            gp_Pnt p2(coords[3*(i+1)], coords[3*(i+1)+1], coords[3*(i+1)+2]);
            BRepBuilderAPI_MakeEdge edgeBuilder(p1, p2);
            if (!edgeBuilder.IsDone()) {
                throw std::runtime_error(
                    std::string("make_polyline_wire: MakeEdge failed at segment ") +
                    std::to_string(i));
            }
            wireBuilder.Add(edgeBuilder.Edge());
            if (!wireBuilder.IsDone()) {
                throw std::runtime_error(
                    std::string("make_polyline_wire: MakeWire failed at segment ") +
                    std::to_string(i));
            }
        }
        auto result = std::make_unique<OcctShape>();
        result->shape = wireBuilder.Wire();
        return result;
    } catch (Standard_Failure const& e) {
        throw std::runtime_error(std::string("OCCT make_polyline_wire: ") + e.GetMessageString());
    } catch (std::exception const& e) {
        throw std::runtime_error(std::string("OCCT make_polyline_wire: unexpected: ") + e.what());
    } catch (...) {
        throw std::runtime_error("OCCT make_polyline_wire: unknown C++ exception");
    }
}

// --- make_interp_curve ---

std::unique_ptr<OcctShape> make_interp_curve(
    rust::Slice<const double> coords, size_t n_points) {
    try {
        if (n_points < 2) {
            throw std::runtime_error("make_interp_curve: requires at least 2 points");
        }
        TColgp_Array1OfPnt points(1, static_cast<int>(n_points));
        for (size_t i = 0; i < n_points; ++i) {
            points.SetValue(static_cast<int>(i + 1),
                gp_Pnt(coords[i * 3], coords[i * 3 + 1], coords[i * 3 + 2]));
        }
        GeomAPI_PointsToBSpline interp(points);
        if (!interp.IsDone()) {
            throw std::runtime_error("make_interp_curve: interpolation failed");
        }
        BRepBuilderAPI_MakeEdge edgeBuilder(interp.Curve());
        if (!edgeBuilder.IsDone()) {
            throw std::runtime_error("make_interp_curve: MakeEdge failed");
        }
        BRepBuilderAPI_MakeWire wireBuilder(edgeBuilder.Edge());
        if (!wireBuilder.IsDone()) {
            throw std::runtime_error("make_interp_curve: MakeWire failed");
        }
        auto result = std::make_unique<OcctShape>();
        result->shape = wireBuilder.Wire();
        return result;
    } catch (Standard_Failure const& e) {
        throw std::runtime_error(std::string("OCCT make_interp_curve: ") + e.GetMessageString());
    } catch (std::exception const& e) {
        throw std::runtime_error(std::string("OCCT make_interp_curve: unexpected: ") + e.what());
    } catch (...) {
        throw std::runtime_error("OCCT make_interp_curve: unknown C++ exception");
    }
}

// --- make_bezier_curve ---

std::unique_ptr<OcctShape> make_bezier_curve(
    rust::Slice<const double> coords, size_t n_points) {
    try {
        if (n_points < 2) {
            throw std::runtime_error("make_bezier_curve: requires at least 2 control points");
        }
        TColgp_Array1OfPnt poles(1, static_cast<int>(n_points));
        for (size_t i = 0; i < n_points; ++i) {
            poles.SetValue(static_cast<int>(i + 1),
                gp_Pnt(coords[i * 3], coords[i * 3 + 1], coords[i * 3 + 2]));
        }
        Handle(Geom_BezierCurve) bezier = new Geom_BezierCurve(poles);
        BRepBuilderAPI_MakeEdge edgeBuilder(bezier);
        if (!edgeBuilder.IsDone()) {
            throw std::runtime_error("make_bezier_curve: MakeEdge failed");
        }
        BRepBuilderAPI_MakeWire wireBuilder(edgeBuilder.Edge());
        if (!wireBuilder.IsDone()) {
            throw std::runtime_error("make_bezier_curve: MakeWire failed");
        }
        auto result = std::make_unique<OcctShape>();
        result->shape = wireBuilder.Wire();
        return result;
    } catch (Standard_Failure const& e) {
        throw std::runtime_error(std::string("OCCT make_bezier_curve: ") + e.GetMessageString());
    } catch (std::exception const& e) {
        throw std::runtime_error(std::string("OCCT make_bezier_curve: unexpected: ") + e.what());
    } catch (...) {
        throw std::runtime_error("OCCT make_bezier_curve: unknown C++ exception");
    }
}

// --- make_nurbs_curve ---

std::unique_ptr<OcctShape> make_nurbs_curve(
    rust::Slice<const double> pole_coords, size_t n_poles,
    rust::Slice<const double> weights,
    rust::Slice<const double> flat_knots,
    int degree) {
    try {
        if (n_poles < 2) {
            throw std::runtime_error("make_nurbs_curve: requires at least 2 control points");
        }
        if (degree < 1) {
            throw std::runtime_error("make_nurbs_curve: degree must be >= 1");
        }
        // Build poles array
        TColgp_Array1OfPnt poles(1, static_cast<int>(n_poles));
        TColStd_Array1OfReal wts(1, static_cast<int>(n_poles));
        for (size_t i = 0; i < n_poles; ++i) {
            poles.SetValue(static_cast<int>(i + 1),
                gp_Pnt(pole_coords[i * 3], pole_coords[i * 3 + 1], pole_coords[i * 3 + 2]));
            wts.SetValue(static_cast<int>(i + 1), weights[i]);
        }
        // Deduplicate flat knots into unique knots + multiplicities
        std::vector<double> unique_knots;
        std::vector<int> mults;
        for (size_t i = 0; i < flat_knots.size(); ) {
            double k = flat_knots[i];
            int m = 0;
            while (i < flat_knots.size() && flat_knots[i] == k) { ++m; ++i; }
            unique_knots.push_back(k);
            mults.push_back(m);
        }
        TColStd_Array1OfReal knots_arr(1, static_cast<int>(unique_knots.size()));
        TColStd_Array1OfInteger mults_arr(1, static_cast<int>(mults.size()));
        for (size_t i = 0; i < unique_knots.size(); ++i) {
            knots_arr.SetValue(static_cast<int>(i + 1), unique_knots[i]);
            mults_arr.SetValue(static_cast<int>(i + 1), mults[i]);
        }
        Handle(Geom_BSplineCurve) bspline = new Geom_BSplineCurve(
            poles, wts, knots_arr, mults_arr, degree);
        BRepBuilderAPI_MakeEdge edgeBuilder(bspline);
        if (!edgeBuilder.IsDone()) {
            throw std::runtime_error("make_nurbs_curve: MakeEdge failed");
        }
        BRepBuilderAPI_MakeWire wireBuilder(edgeBuilder.Edge());
        if (!wireBuilder.IsDone()) {
            throw std::runtime_error("make_nurbs_curve: MakeWire failed");
        }
        auto result = std::make_unique<OcctShape>();
        result->shape = wireBuilder.Wire();
        return result;
    } catch (Standard_Failure const& e) {
        throw std::runtime_error(std::string("OCCT make_nurbs_curve: ") + e.GetMessageString());
    } catch (std::exception const& e) {
        throw std::runtime_error(std::string("OCCT make_nurbs_curve: unexpected: ") + e.what());
    } catch (...) {
        throw std::runtime_error("OCCT make_nurbs_curve: unknown C++ exception");
    }
}

// --- Loft (generic N profiles) ---

std::unique_ptr<OcctShape> loft_profiles(const OcctShapeVec& profiles) {
    try {
        if (profiles.shapes.size() < 2) {
            throw std::runtime_error("loft_profiles: requires at least 2 profiles");
        }
        BRepOffsetAPI_ThruSections loft(Standard_True, Standard_False);
        for (const auto& shape : profiles.shapes) {
            loft.AddWire(TopoDS::Wire(shape));
        }
        loft.Build();
        if (!loft.IsDone()) {
            throw std::runtime_error("BRepOffsetAPI_ThruSections (loft) failed");
        }
        auto result = std::make_unique<OcctShape>();
        result->shape = loft.Shape();
        return result;
    } catch (Standard_Failure const& e) {
        throw std::runtime_error(std::string("OCCT loft_profiles: ") + e.GetMessageString());
    } catch (std::exception const& e) {
        throw std::runtime_error(std::string("OCCT loft_profiles: unexpected: ") + e.what());
    } catch (...) {
        throw std::runtime_error("OCCT loft_profiles: unknown C++ exception");
    }
}

// --- Sweep ---

std::unique_ptr<OcctShape> make_pipe(const OcctShape& profile, const OcctShape& spine) {
    try {
        BRepOffsetAPI_MakePipe maker(TopoDS::Wire(spine.shape), profile.shape);
        // BRepOffsetAPI_MakePipe calls Build() internally in its constructor;
        // an explicit Build() here is redundant and was removed (task-383 S1).
        if (!maker.IsDone()) {
            throw std::runtime_error("BRepOffsetAPI_MakePipe failed");
        }
        auto result = std::make_unique<OcctShape>();
        result->shape = maker.Shape();
        return result;
    } catch (Standard_Failure const& e) {
        throw std::runtime_error(std::string("OCCT make_pipe: ") + e.GetMessageString());
    } catch (std::exception const& e) {
        throw std::runtime_error(std::string("OCCT make_pipe: unexpected: ") + e.what());
    } catch (...) {
        throw std::runtime_error("OCCT make_pipe: unknown C++ exception");
    }
}

std::unique_ptr<OcctShape> make_pipe_shell(const OcctShape& profile,
                                           const OcctShape& spine,
                                           const OcctShape& guide) {
    try {
        // Spine and guide must both be wires; profile may be an edge,
        // wire, or face.
        BRepOffsetAPI_MakePipeShell maker(TopoDS::Wire(spine.shape));
        maker.Add(profile.shape);
        // SetMode(auxWire, KeepContact) — KeepContact=false keeps the
        // section's centre free while using the guide to bias orientation.
        maker.SetMode(TopoDS::Wire(guide.shape), Standard_False);
        maker.Build();
        if (!maker.IsDone()) {
            throw std::runtime_error("BRepOffsetAPI_MakePipeShell failed");
        }
        auto result = std::make_unique<OcctShape>();
        result->shape = maker.Shape();
        return result;
    } catch (Standard_Failure const& e) {
        throw std::runtime_error(std::string("OCCT make_pipe_shell: ") + e.GetMessageString());
    } catch (std::exception const& e) {
        throw std::runtime_error(std::string("OCCT make_pipe_shell: unexpected: ") + e.what());
    } catch (...) {
        throw std::runtime_error("OCCT make_pipe_shell: unknown C++ exception");
    }
}

std::unique_ptr<OcctShape> loft_guided_profiles(const OcctShapeVec& profiles,
                                                const OcctShapeVec& guides) {
    try {
        // DEFENSE-IN-DEPTH: Rust layer validates; this catches direct FFI paths.
        if (profiles.shapes.size() < 2) {
            throw std::runtime_error("loft_guided_profiles: requires at least 2 profiles");
        }
        if (guides.shapes.empty()) {
            throw std::runtime_error("loft_guided_profiles: requires at least 1 guide");
        }
        // The first guide is the spine; each profile is added as a
        // section. An optional second guide provides auxiliary
        // orientation via SetMode(aux, /*KeepContact=*/false).
        BRepOffsetAPI_MakePipeShell maker(TopoDS::Wire(guides.shapes[0]));
        for (const auto& profile : profiles.shapes) {
            maker.Add(profile);
        }
        if (guides.shapes.size() >= 2) {
            maker.SetMode(TopoDS::Wire(guides.shapes[1]), Standard_False);
        }
        maker.Build();
        if (!maker.IsDone()) {
            throw std::runtime_error("BRepOffsetAPI_MakePipeShell (loft_guided) failed");
        }
        auto result = std::make_unique<OcctShape>();
        result->shape = maker.Shape();
        return result;
    } catch (Standard_Failure const& e) {
        throw std::runtime_error(std::string("OCCT loft_guided_profiles: ") + e.GetMessageString());
    } catch (std::exception const& e) {
        throw std::runtime_error(std::string("OCCT loft_guided_profiles: unexpected: ") + e.what());
    } catch (...) {
        throw std::runtime_error("OCCT loft_guided_profiles: unknown C++ exception");
    }
}

// --- Sweep / Extrude ---

std::unique_ptr<OcctShape> make_prism(const OcctShape& profile, double dx, double dy, double dz) {
    try {
        // DEFENSE-IN-DEPTH: Rust extrude validates distance; this catches direct FFI calls.
        double mag_sq = dx*dx + dy*dy + dz*dz;
        if (!(std::isfinite(dx) && std::isfinite(dy) && std::isfinite(dz))) {
            throw std::runtime_error("make_prism: direction vector components must be finite");
        }
        if (mag_sq < CPP_AXIS_MAG_SQ_MIN) {
            throw std::runtime_error("make_prism: direction vector magnitude must be > 0");
        }
        gp_Vec vec(dx, dy, dz);
        BRepPrimAPI_MakePrism maker(profile.shape, vec);
        if (!maker.IsDone()) {
            throw std::runtime_error("BRepPrimAPI_MakePrism failed");
        }
        auto result = std::make_unique<OcctShape>();
        result->shape = maker.Shape();
        return result;
    } catch (Standard_Failure const& e) {
        throw std::runtime_error(std::string("OCCT make_prism: ") + e.GetMessageString());
    } catch (std::exception const& e) {
        throw std::runtime_error(std::string("OCCT make_prism: unexpected: ") + e.what());
    } catch (...) {
        throw std::runtime_error("OCCT make_prism: unknown C++ exception");
    }
}

std::unique_ptr<OcctShape> make_revolve(const OcctShape& profile,
    double ox, double oy, double oz,
    double ax, double ay, double az,
    double angle_rad) {
    try {
        // DEFENSE-IN-DEPTH: Rust validates first with stricter threshold (1e-12 for axis).
        // These C++ checks (1e-30) are a safety net for future code paths that may bypass
        // the Rust layer (e.g., direct FFI calls from tests or hot-path optimizations).
        if (!(std::isfinite(ox) && std::isfinite(oy) && std::isfinite(oz) &&
              std::isfinite(ax) && std::isfinite(ay) && std::isfinite(az) &&
              std::isfinite(angle_rad))) {
            throw std::runtime_error("make_revolve: all parameters must be finite");
        }
        double axis_mag_sq = ax*ax + ay*ay + az*az;
        if (axis_mag_sq < CPP_AXIS_MAG_SQ_MIN) {
            throw std::runtime_error("make_revolve: axis direction must not be zero-length");
        }
        if (std::abs(angle_rad) < CPP_ANGLE_ABS_MIN) {
            throw std::runtime_error("make_revolve: angle must not be zero");
        }
        gp_Pnt origin(ox, oy, oz);
        gp_Dir dir(ax, ay, az);
        gp_Ax1 axis(origin, dir);
        BRepPrimAPI_MakeRevol maker(profile.shape, axis, angle_rad);
        maker.Build();
        if (!maker.IsDone()) {
            throw std::runtime_error("BRepPrimAPI_MakeRevol failed");
        }
        TopoDS_Shape rev_shape = maker.Shape();
        // Some OCCT versions produce a Shell instead of Solid when revolving
        // a Face. Convert Shell → Solid so volume queries work correctly.
        if (rev_shape.ShapeType() == TopAbs_SHELL) {
            BRepBuilderAPI_MakeSolid solidMaker(TopoDS::Shell(rev_shape));
            if (solidMaker.IsDone()) {
                rev_shape = solidMaker.Solid();
            } else {
                throw std::runtime_error("make_revolve: Shell\xe2\x86\x92Solid conversion failed \xe2\x80\x94 BRepBuilderAPI_MakeSolid did not complete");
            }
        }
        // Fix face orientations so volume computation works correctly.
        if (rev_shape.ShapeType() == TopAbs_SOLID) {
            TopoDS_Solid solid = TopoDS::Solid(rev_shape);
            BRepLib::OrientClosedSolid(solid);
            rev_shape = solid;
        }
        auto result = std::make_unique<OcctShape>();
        result->shape = rev_shape;
        return result;
    } catch (Standard_Failure const& e) {
        throw std::runtime_error(std::string("OCCT make_revolve: ") + e.GetMessageString());
    } catch (std::exception const& e) {
        throw std::runtime_error(std::string("OCCT make_revolve: unexpected: ") + e.what());
    } catch (...) {
        throw std::runtime_error("OCCT make_revolve: unknown C++ exception");
    }
}

std::unique_ptr<OcctShape> make_rect_face(double width, double height,
    double cx, double cy, double cz) {
    try {
        if (!(std::isfinite(width) && width > 0.0)) {
            throw std::runtime_error("make_rect_face: width must be finite and positive");
        }
        if (!(std::isfinite(height) && height > 0.0)) {
            throw std::runtime_error("make_rect_face: height must be finite and positive");
        }
        if (!(std::isfinite(cx) && std::isfinite(cy) && std::isfinite(cz))) {
            throw std::runtime_error("make_rect_face: center coordinates must be finite");
        }
        double hw = width / 2.0;
        double hh = height / 2.0;
        gp_Pnt p1(cx - hw, cy - hh, cz);
        gp_Pnt p2(cx + hw, cy - hh, cz);
        gp_Pnt p3(cx + hw, cy + hh, cz);
        gp_Pnt p4(cx - hw, cy + hh, cz);

        BRepBuilderAPI_MakeEdge e1(p1, p2);
        BRepBuilderAPI_MakeEdge e2(p2, p3);
        BRepBuilderAPI_MakeEdge e3(p3, p4);
        BRepBuilderAPI_MakeEdge e4(p4, p1);
        if (!e1.IsDone() || !e2.IsDone() || !e3.IsDone() || !e4.IsDone()) {
            throw std::runtime_error("make_rect_face: MakeEdge failed");
        }
        BRepBuilderAPI_MakeWire wireBuilder;
        wireBuilder.Add(e1.Edge());
        wireBuilder.Add(e2.Edge());
        wireBuilder.Add(e3.Edge());
        wireBuilder.Add(e4.Edge());
        if (!wireBuilder.IsDone()) {
            throw std::runtime_error("make_rect_face: MakeWire failed");
        }
        BRepBuilderAPI_MakeFace faceBuilder(wireBuilder.Wire(), Standard_True);
        if (!faceBuilder.IsDone()) {
            throw std::runtime_error("make_rect_face: MakeFace failed");
        }
        auto result = std::make_unique<OcctShape>();
        result->shape = faceBuilder.Face();
        return result;
    } catch (Standard_Failure const& e) {
        throw std::runtime_error(std::string("OCCT make_rect_face: ") + e.GetMessageString());
    } catch (std::exception const& e) {
        throw std::runtime_error(std::string("OCCT make_rect_face: unexpected: ") + e.what());
    } catch (...) {
        throw std::runtime_error("OCCT make_rect_face: unknown C++ exception");
    }
}

// --- Wire queries ---

Point3 wire_start_tangent(const OcctShape& wire_shape) {
    try {
        TopoDS_Wire w = TopoDS::Wire(wire_shape.shape);
        if (w.IsNull()) {
            throw std::runtime_error("wire_start_tangent: shape is not a wire");
        }
        BRepAdaptor_CompCurve adaptor(w);
        double u = adaptor.FirstParameter();
        gp_Pnt p;
        gp_Vec v;
        adaptor.D1(u, p, v);
        double m = v.Magnitude();
        if (m < 1e-12) {
            throw std::runtime_error("wire_start_tangent: degenerate curve (zero tangent)");
        }
        return Point3{ v.X() / m, v.Y() / m, v.Z() / m };
    } catch (Standard_Failure const& e) {
        throw std::runtime_error(std::string("OCCT wire_start_tangent: ") + e.GetMessageString());
    } catch (std::exception const& e) {
        throw std::runtime_error(std::string("OCCT wire_start_tangent: unexpected: ") + e.what());
    } catch (...) {
        throw std::runtime_error("OCCT wire_start_tangent: unknown C++ exception");
    }
}

// --- Queries ---

// Compute volume from triangle mesh using surface UV → 3D evaluation.
// In OCCT 7.6+ Poly_Triangulation may store only UV nodes, so we must
// evaluate the actual surface to get 3D coordinates.
static double mesh_based_volume(const TopoDS_Shape& shape, double deflection) {
    BRepMesh_IncrementalMesh mesher(shape, deflection);
    double volume = 0.0;
    for (TopExp_Explorer ex(shape, TopAbs_FACE); ex.More(); ex.Next()) {
        TopoDS_Face face = TopoDS::Face(ex.Current());
        TopLoc_Location loc;
        Handle(Poly_Triangulation) tri = BRep_Tool::Triangulation(face, loc);
        if (tri.IsNull()) continue;
        BRepAdaptor_Surface surf(face, Standard_False);
        bool reversed = (face.Orientation() == TopAbs_REVERSED);
        // Build 3D node cache by evaluating UV on the surface
        bool has_uv = tri->HasUVNodes();
        std::vector<gp_Pnt> nodes3d(tri->NbNodes() + 1);
        for (int j = 1; j <= tri->NbNodes(); j++) {
            if (has_uv) {
                gp_Pnt2d uv = tri->UVNode(j);
                surf.D0(uv.X(), uv.Y(), nodes3d[j]);
            } else {
                nodes3d[j] = tri->Node(j).Transformed(loc.Transformation());
            }
        }
        for (int i = 1; i <= tri->NbTriangles(); i++) {
            Standard_Integer n1, n2, n3;
            tri->Triangle(i).Get(n1, n2, n3);
            const gp_Pnt& p1 = nodes3d[n1];
            const gp_Pnt& p2 = reversed ? nodes3d[n3] : nodes3d[n2];
            const gp_Pnt& p3 = reversed ? nodes3d[n2] : nodes3d[n3];
            volume += (p1.X()*(p2.Y()*p3.Z() - p3.Y()*p2.Z())
                     - p2.X()*(p1.Y()*p3.Z() - p3.Y()*p1.Z())
                     + p3.X()*(p1.Y()*p2.Z() - p2.Y()*p1.Z())) / 6.0;
        }
    }
    return std::abs(volume);
}

double query_volume(const OcctShape& shape) {
    try {
        GProp_GProps props;
        BRepGProp::VolumeProperties(shape.shape, props);
        double vol = props.Mass();
        // BRepGProp::VolumeProperties returns 0 for some parametric surfaces
        // (e.g. revolution surfaces). Fall back to mesh-based computation.
        if (vol == 0.0 && shape.shape.ShapeType() <= TopAbs_SOLID) {
            vol = mesh_based_volume(shape.shape, 0.01);
        }
        return vol;
    } catch (Standard_Failure const& e) {
        throw std::runtime_error(std::string("OCCT query_volume: ") + e.GetMessageString());
    } catch (std::exception const& e) {
        throw std::runtime_error(std::string("OCCT query_volume: unexpected: ") + e.what());
    } catch (...) {
        throw std::runtime_error("OCCT query_volume: unknown C++ exception");
    }
}

double query_area(const OcctShape& shape) {
    try {
        GProp_GProps props;
        BRepGProp::SurfaceProperties(shape.shape, props);
        return props.Mass();
    } catch (Standard_Failure const& e) {
        throw std::runtime_error(std::string("OCCT query_area: ") + e.GetMessageString());
    } catch (std::exception const& e) {
        throw std::runtime_error(std::string("OCCT query_area: unexpected: ") + e.what());
    } catch (...) {
        throw std::runtime_error("OCCT query_area: unknown C++ exception");
    }
}

Point3 query_centroid(const OcctShape& shape) {
    try {
        GProp_GProps props;
        BRepGProp::VolumeProperties(shape.shape, props);
        gp_Pnt c = props.CentreOfMass();
        return Point3{c.X(), c.Y(), c.Z()};
    } catch (Standard_Failure const& e) {
        throw std::runtime_error(std::string("OCCT query_centroid: ") + e.GetMessageString());
    } catch (std::exception const& e) {
        throw std::runtime_error(std::string("OCCT query_centroid: unexpected: ") + e.what());
    } catch (...) {
        throw std::runtime_error("OCCT query_centroid: unknown C++ exception");
    }
}

BBox query_bbox(const OcctShape& shape) {
    try {
        Bnd_Box box;
        BRepBndLib::Add(shape.shape, box);
        double xmin, ymin, zmin, xmax, ymax, zmax;
        box.Get(xmin, ymin, zmin, xmax, ymax, zmax);
        return BBox{xmin, ymin, zmin, xmax, ymax, zmax};
    } catch (Standard_Failure const& e) {
        throw std::runtime_error(std::string("OCCT query_bbox: ") + e.GetMessageString());
    } catch (std::exception const& e) {
        throw std::runtime_error(std::string("OCCT query_bbox: unexpected: ") + e.what());
    } catch (...) {
        throw std::runtime_error("OCCT query_bbox: unknown C++ exception");
    }
}

double query_distance(const OcctShape& shape1, const OcctShape& shape2) {
    try {
        BRepExtrema_DistShapeShape dist(shape1.shape, shape2.shape);
        if (!dist.IsDone()) {
            throw std::runtime_error("BRepExtrema_DistShapeShape failed");
        }
        return dist.Value();
    } catch (Standard_Failure const& e) {
        throw std::runtime_error(std::string("OCCT query_distance: ") + e.GetMessageString());
    } catch (std::exception const& e) {
        throw std::runtime_error(std::string("OCCT query_distance: unexpected: ") + e.what());
    } catch (...) {
        throw std::runtime_error("OCCT query_distance: unknown C++ exception");
    }
}

double query_moment_of_inertia(const OcctShape& shape, double ax, double ay, double az) {
    try {
        GProp_GProps props;
        BRepGProp::VolumeProperties(shape.shape, props);
        gp_Ax1 axis(props.CentreOfMass(), gp_Dir(ax, ay, az));
        return props.MomentOfInertia(axis);
    } catch (Standard_Failure const& e) {
        throw std::runtime_error(std::string("OCCT query_moment_of_inertia: ") + e.GetMessageString());
    } catch (std::exception const& e) {
        throw std::runtime_error(std::string("OCCT query_moment_of_inertia: unexpected: ") + e.what());
    } catch (...) {
        throw std::runtime_error("OCCT query_moment_of_inertia: unknown C++ exception");
    }
}

// --- Conformance queries ---

bool is_watertight(const OcctShape& shape) {
    try {
        // Shape-type guard: only SOLID, COMPSOLID, and SHELL can be watertight
        // (they can enclose a volume). COMPOUND is intentionally excluded:
        // BRepCheck_Analyzer.IsValid() on a compound reports topological
        // consistency, not closure — a compound of wires or open faces would
        // spuriously return true. Callers that need to test a compound's
        // watertightness should iterate its sub-shapes individually.
        // FACE, WIRE, EDGE, VERTEX always return false immediately.
        TopAbs_ShapeEnum type = shape.shape.ShapeType();
        if (type != TopAbs_SOLID && type != TopAbs_COMPSOLID
                && type != TopAbs_SHELL) {
            return false;
        }
        BRepCheck_Analyzer analyzer(shape.shape);
        return analyzer.IsValid();
    } catch (Standard_Failure const& e) {
        throw std::runtime_error(std::string("OCCT is_watertight: ") + e.GetMessageString());
    } catch (std::exception const& e) {
        throw std::runtime_error(std::string("OCCT is_watertight: unexpected: ") + e.what());
    } catch (...) {
        throw std::runtime_error("OCCT is_watertight: unknown C++ exception");
    }
}

bool is_manifold(const OcctShape& shape) {
    try {
        // Walk the cached edge→face incidence map. Every edge that has more
        // than 2 parent faces violates manifoldness. Shapes with no face
        // incidence (wires, edges, vertices) trivially return true.
        const auto& m = shape.edge_face_map();
        for (Standard_Integer i = 1; i <= m.Extent(); ++i) {
            if (m.FindFromIndex(i).Extent() > 2) {
                return false;
            }
        }
        return true;
    } catch (Standard_Failure const& e) {
        throw std::runtime_error(std::string("OCCT is_manifold: ") + e.GetMessageString());
    } catch (std::exception const& e) {
        throw std::runtime_error(std::string("OCCT is_manifold: unexpected: ") + e.what());
    } catch (...) {
        throw std::runtime_error("OCCT is_manifold: unknown C++ exception");
    }
}

bool is_orientable(const OcctShape& shape) {
    try {
        ShapeAnalysis_Shell sa;
        sa.LoadShells(shape.shape);
        if (sa.NbLoaded() == 0) {
            // No shells: wires, isolated faces, vertices are trivially orientable.
            return true;
        }
        // CheckOrientedShells returns Standard_True when it finds "bad" edges
        // (edges with inconsistent orientation), i.e. true = problems found.
        // We invert: orientable iff no problems found.
        return !sa.CheckOrientedShells(shape.shape, Standard_False);
    } catch (Standard_Failure const& e) {
        throw std::runtime_error(std::string("OCCT is_orientable: ") + e.GetMessageString());
    } catch (std::exception const& e) {
        throw std::runtime_error(std::string("OCCT is_orientable: unexpected: ") + e.what());
    } catch (...) {
        throw std::runtime_error("OCCT is_orientable: unknown C++ exception");
    }
}

// --- Test fixture helpers ---

std::unique_ptr<OcctShape> make_nonmanifold_compound_for_test() {
    // Three planar faces sharing a common edge along the X axis from
    // (0,0,0) to (10mm,0,0). The shared edge has 3 incident faces, so
    // edge_face_map().FindFromIndex(i).Extent() == 3 > 2 for that edge.
    try {
        // Create the shared edge first; add it as the FIRST edge of each wire
        // so BRepBuilderAPI_MakeWire does not need to stitch it and preserves
        // its TShape identity across all three wires/faces.
        BRepBuilderAPI_MakeEdge e_shared(gp_Pnt(0.0,0.0,0.0), gp_Pnt(0.01,0.0,0.0));
        TopoDS_Edge shared = e_shared.Edge();

        // Face 1 — XY plane (z=0), y ∈ [0, 10mm]
        BRepBuilderAPI_MakeEdge e1a(gp_Pnt(0.01,0.0,0.0), gp_Pnt(0.01,0.01,0.0));
        BRepBuilderAPI_MakeEdge e1b(gp_Pnt(0.01,0.01,0.0), gp_Pnt(0.0,0.01,0.0));
        BRepBuilderAPI_MakeEdge e1c(gp_Pnt(0.0,0.01,0.0), gp_Pnt(0.0,0.0,0.0));
        BRepBuilderAPI_MakeWire w1;
        w1.Add(shared);
        w1.Add(e1a.Edge()); w1.Add(e1b.Edge()); w1.Add(e1c.Edge());
        BRepBuilderAPI_MakeFace f1(w1.Wire(), Standard_True);
        if (!f1.IsDone()) throw std::runtime_error("make_nonmanifold_compound: face1 failed");

        // Face 2 — XZ plane (y=0), z ∈ [0, 10mm]
        BRepBuilderAPI_MakeEdge e2a(gp_Pnt(0.01,0.0,0.0), gp_Pnt(0.01,0.0,0.01));
        BRepBuilderAPI_MakeEdge e2b(gp_Pnt(0.01,0.0,0.01), gp_Pnt(0.0,0.0,0.01));
        BRepBuilderAPI_MakeEdge e2c(gp_Pnt(0.0,0.0,0.01), gp_Pnt(0.0,0.0,0.0));
        BRepBuilderAPI_MakeWire w2;
        w2.Add(shared);
        w2.Add(e2a.Edge()); w2.Add(e2b.Edge()); w2.Add(e2c.Edge());
        BRepBuilderAPI_MakeFace f2(w2.Wire(), Standard_True);
        if (!f2.IsDone()) throw std::runtime_error("make_nonmanifold_compound: face2 failed");

        // Face 3 — XY plane (z=0), y ∈ [−10mm, 0]
        BRepBuilderAPI_MakeEdge e3a(gp_Pnt(0.01,0.0,0.0), gp_Pnt(0.01,-0.01,0.0));
        BRepBuilderAPI_MakeEdge e3b(gp_Pnt(0.01,-0.01,0.0), gp_Pnt(0.0,-0.01,0.0));
        BRepBuilderAPI_MakeEdge e3c(gp_Pnt(0.0,-0.01,0.0), gp_Pnt(0.0,0.0,0.0));
        BRepBuilderAPI_MakeWire w3;
        w3.Add(shared);
        w3.Add(e3a.Edge()); w3.Add(e3b.Edge()); w3.Add(e3c.Edge());
        BRepBuilderAPI_MakeFace f3(w3.Wire(), Standard_True);
        if (!f3.IsDone()) throw std::runtime_error("make_nonmanifold_compound: face3 failed");

        // Assemble into a compound (no topology validation, just containment)
        TopoDS_Compound compound;
        BRep_Builder builder;
        builder.MakeCompound(compound);
        builder.Add(compound, f1.Face());
        builder.Add(compound, f2.Face());
        builder.Add(compound, f3.Face());

        auto result = std::make_unique<OcctShape>();
        result->shape = compound;
        return result;
    } catch (Standard_Failure const& e) {
        throw std::runtime_error(std::string("OCCT make_nonmanifold_compound: ") + e.GetMessageString());
    } catch (std::exception const& e) {
        throw std::runtime_error(std::string("OCCT make_nonmanifold_compound: unexpected: ") + e.what());
    } catch (...) {
        throw std::runtime_error("OCCT make_nonmanifold_compound: unknown C++ exception");
    }
}

std::unique_ptr<OcctShape> make_malformed_solid_for_test() {
    // Build a 10×10×10 mm box, extract 5 of its 6 faces into a shell,
    // wrap the open shell in a solid. The 4 edges that connected to the
    // removed face are now free → BRepCheck_Analyzer::IsValid() returns false.
    try {
        BRepPrimAPI_MakeBox box_maker(0.01, 0.01, 0.01);
        box_maker.Build();
        if (!box_maker.IsDone()) {
            throw std::runtime_error("make_malformed_solid: box construction failed");
        }
        TopoDS_Shape box = box_maker.Shape();

        BRep_Builder builder;
        TopoDS_Shell shell;
        builder.MakeShell(shell);
        int face_count = 0;
        for (TopExp_Explorer ex(box, TopAbs_FACE); ex.More() && face_count < 5; ex.Next(), ++face_count) {
            builder.Add(shell, ex.Current());
        }

        // Wrap the open shell in a solid (TopAbs_SOLID type, passes shape-type
        // guard, but IsValid() fails because the shell is not closed)
        TopoDS_Solid solid;
        builder.MakeSolid(solid);
        builder.Add(solid, shell);

        auto result = std::make_unique<OcctShape>();
        result->shape = solid;
        return result;
    } catch (Standard_Failure const& e) {
        throw std::runtime_error(std::string("OCCT make_malformed_solid: ") + e.GetMessageString());
    } catch (std::exception const& e) {
        throw std::runtime_error(std::string("OCCT make_malformed_solid: unexpected: ") + e.what());
    } catch (...) {
        throw std::runtime_error("OCCT make_malformed_solid: unknown C++ exception");
    }
}

std::unique_ptr<OcctShape> make_nonorientable_shell_for_test() {
    // Two faces sharing a common edge, both wires using the shared edge
    // FORWARD — violates the requirement that adjacent faces must use each
    // non-free edge with opposite orientations. ShapeAnalysis_Shell::
    // CheckOrientedShells returns Standard_True (problems found) for this shell.
    try {
        // Shared edge along X: (0,0,0) → (10mm,0,0). Added first to both
        // wires to prevent BRepBuilderAPI_MakeWire from reversing it.
        BRepBuilderAPI_MakeEdge e_shared(gp_Pnt(0.0,0.0,0.0), gp_Pnt(0.01,0.0,0.0));
        TopoDS_Edge shared = e_shared.Edge();

        // Face 1 — XY plane (z=0), y ∈ [0, 10mm]; shared edge is FORWARD
        BRepBuilderAPI_MakeEdge f1e2(gp_Pnt(0.01,0.0,0.0), gp_Pnt(0.01,0.01,0.0));
        BRepBuilderAPI_MakeEdge f1e3(gp_Pnt(0.01,0.01,0.0), gp_Pnt(0.0,0.01,0.0));
        BRepBuilderAPI_MakeEdge f1e4(gp_Pnt(0.0,0.01,0.0), gp_Pnt(0.0,0.0,0.0));
        BRepBuilderAPI_MakeWire w1;
        w1.Add(shared);
        w1.Add(f1e2.Edge()); w1.Add(f1e3.Edge()); w1.Add(f1e4.Edge());
        BRepBuilderAPI_MakeFace face1(w1.Wire(), Standard_True);
        if (!face1.IsDone()) throw std::runtime_error("make_nonorientable_shell: face1 failed");

        // Face 2 — XZ plane (y=0), z ∈ [0, 10mm]; shared edge also FORWARD
        // (same direction as in face1) → orientation inconsistency
        BRepBuilderAPI_MakeEdge f2e2(gp_Pnt(0.01,0.0,0.0), gp_Pnt(0.01,0.0,0.01));
        BRepBuilderAPI_MakeEdge f2e3(gp_Pnt(0.01,0.0,0.01), gp_Pnt(0.0,0.0,0.01));
        BRepBuilderAPI_MakeEdge f2e4(gp_Pnt(0.0,0.0,0.01), gp_Pnt(0.0,0.0,0.0));
        BRepBuilderAPI_MakeWire w2;
        w2.Add(shared);
        w2.Add(f2e2.Edge()); w2.Add(f2e3.Edge()); w2.Add(f2e4.Edge());
        BRepBuilderAPI_MakeFace face2(w2.Wire(), Standard_True);
        if (!face2.IsDone()) throw std::runtime_error("make_nonorientable_shell: face2 failed");

        BRep_Builder builder;
        TopoDS_Shell shell;
        builder.MakeShell(shell);
        builder.Add(shell, face1.Face());
        builder.Add(shell, face2.Face());

        auto result = std::make_unique<OcctShape>();
        result->shape = shell;
        return result;
    } catch (Standard_Failure const& e) {
        throw std::runtime_error(std::string("OCCT make_nonorientable_shell: ") + e.GetMessageString());
    } catch (std::exception const& e) {
        throw std::runtime_error(std::string("OCCT make_nonorientable_shell: unexpected: ") + e.what());
    } catch (...) {
        throw std::runtime_error("OCCT make_nonorientable_shell: unknown C++ exception");
    }
}

// --- OcctShape lazy accessor implementations ---

// STRONG-EXCEPTION-GUARANTEE: Build into a local `unique_ptr` (`tmp`) and only
// move it into the cache slot after TopExp::MapShapes returns successfully.
// If MapShapes throws (OOM, corrupted topology, etc.), `tmp` is destroyed on
// stack unwind, the slot stays null, and the counter stays at its prior value.
// The next call therefore retries cleanly and observability remains honest.
// Do NOT revert to the "slot = make_unique; MapShapes(*slot); ++counter" order —
// that leaves the slot non-null with an empty map after a throw, masking the
// failure on every subsequent call.

const TopTools_IndexedMapOfShape& OcctShape::face_map() const {
    if (!face_map_cache_) {
        // STRONG-EXCEPTION-GUARANTEE: build into `tmp`; move into slot only on success.
        auto tmp = std::make_unique<TopTools_IndexedMapOfShape>();
        TopExp::MapShapes(shape, TopAbs_FACE, *tmp);
        face_map_cache_ = std::move(tmp);
        ++face_map_builds_;
    }
    return *face_map_cache_;
}

const TopTools_IndexedMapOfShape& OcctShape::edge_map() const {
    if (!edge_map_cache_) {
        // STRONG-EXCEPTION-GUARANTEE: build into `tmp`; move into slot only on success.
        auto tmp = std::make_unique<TopTools_IndexedMapOfShape>();
        TopExp::MapShapes(shape, TopAbs_EDGE, *tmp);
        edge_map_cache_ = std::move(tmp);
        ++edge_map_builds_;
    }
    return *edge_map_cache_;
}

const TopTools_IndexedDataMapOfShapeListOfShape& OcctShape::edge_face_map() const {
    if (!edge_face_map_cache_) {
        // STRONG-EXCEPTION-GUARANTEE: build into `tmp`; move into slot only on success.
        auto tmp = std::make_unique<TopTools_IndexedDataMapOfShapeListOfShape>();
        TopExp::MapShapesAndAncestors(shape, TopAbs_EDGE, TopAbs_FACE, *tmp);
        edge_face_map_cache_ = std::move(tmp);
        ++edge_face_map_builds_;
    }
    return *edge_face_map_cache_;
}

TopologyCacheBuildCounts topology_cache_build_counts(const OcctShape& shape) {
    TopologyCacheBuildCounts counts;
    counts.face_map_builds = shape.face_map_builds_;
    counts.edge_map_builds = shape.edge_map_builds_;
    counts.edge_face_map_builds = shape.edge_face_map_builds_;
    return counts;
}

rust::Vec<uint32_t> adjacent_faces(const OcctShape& shape, uint32_t face_index) {
    try {
        // Use the lazy cached face map (1-based IndexedMap, deduplicates by
        // IsSame). Converts 1-based OCCT indices to 0-based for callers.
        const TopTools_IndexedMapOfShape& face_map = shape.face_map();

        const uint32_t face_count = static_cast<uint32_t>(face_map.Extent());
        if (face_index >= face_count) {
            std::string msg = "adjacent_faces: face index "
                + std::to_string(face_index)
                + " out of range; shape has "
                + std::to_string(face_count)
                + " faces";
            throw std::runtime_error(msg);
        }

        // Use the lazy cached edge -> faces incidence map.
        const TopTools_IndexedDataMapOfShapeListOfShape& edge_face_map = shape.edge_face_map();

        // For each edge of the queried face, look up its parent faces and
        // recover the 0-based global face index via face_map.FindIndex (O(1)
        // via the map's IsSame-keyed hash).
        const TopoDS_Shape& target =
            face_map.FindKey(static_cast<Standard_Integer>(face_index + 1));
        std::set<uint32_t> result;
        for (TopExp_Explorer ex(target, TopAbs_EDGE); ex.More(); ex.Next()) {
            const TopoDS_Shape& edge = ex.Current();
            if (!edge_face_map.Contains(edge)) {
                continue;
            }
            const TopTools_ListOfShape& parents = edge_face_map.FindFromKey(edge);
            for (TopTools_ListIteratorOfListOfShape it(parents); it.More(); it.Next()) {
                const TopoDS_Shape& parent_face = it.Value();
                Standard_Integer one_based = face_map.FindIndex(parent_face);
                if (one_based < 1) {
                    continue;
                }
                uint32_t parent_idx = static_cast<uint32_t>(one_based - 1);
                if (parent_idx == face_index) {
                    continue;
                }
                result.insert(parent_idx);
            }
        }

        rust::Vec<uint32_t> out;
        for (uint32_t i : result) {
            out.push_back(i);
        }
        return out;
    } catch (Standard_Failure const& e) {
        throw std::runtime_error(std::string("OCCT adjacent_faces: ") + e.GetMessageString());
    } catch (std::exception const& e) {
        throw std::runtime_error(std::string("OCCT adjacent_faces: ") + e.what());
    } catch (...) {
        throw std::runtime_error("OCCT adjacent_faces: unknown C++ exception");
    }
}

rust::Vec<uint32_t> shared_edges(const OcctShape& shape, uint32_t face_a_index, uint32_t face_b_index) {
    try {
        // Use the lazy cached face map (1-based IndexedMap, deduplicates by
        // IsSame). Converts 1-based OCCT indices to 0-based for callers.
        const TopTools_IndexedMapOfShape& face_map = shape.face_map();

        const uint32_t face_count = static_cast<uint32_t>(face_map.Extent());
        if (face_a_index >= face_count) {
            std::string msg = "shared_edges: face index "
                + std::to_string(face_a_index)
                + " out of range; shape has "
                + std::to_string(face_count)
                + " faces";
            throw std::runtime_error(msg);
        }
        if (face_b_index >= face_count) {
            std::string msg = "shared_edges: face index "
                + std::to_string(face_b_index)
                + " out of range; shape has "
                + std::to_string(face_count)
                + " faces";
            throw std::runtime_error(msg);
        }

        // Same-face short-circuit: by design we treat shared_edges(f, f) as
        // empty rather than "all edges of f" (see plan design decisions).
        if (face_a_index == face_b_index) {
            return rust::Vec<uint32_t>{};
        }

        // Use the lazy cached edge map (1-based IndexedMap, deduplicates by
        // IsSame). Exposes 0-based indices to callers.
        const TopTools_IndexedMapOfShape& edge_map = shape.edge_map();

        const TopoDS_Shape& face_a =
            face_map.FindKey(static_cast<Standard_Integer>(face_a_index + 1));
        const TopoDS_Shape& face_b =
            face_map.FindKey(static_cast<Standard_Integer>(face_b_index + 1));

        // Build face_a's edge set as an IndexedMap so membership testing for
        // face_b's edges is O(1) (IsSame-keyed hash) instead of a linear scan.
        TopTools_IndexedMapOfShape face_a_edge_map;
        TopExp::MapShapes(face_a, TopAbs_EDGE, face_a_edge_map);

        // For each edge of face_b, check membership in face_a's edge set; if
        // present, recover the global edge index via edge_map (1-based -> 0-based).
        std::set<uint32_t> result;
        for (TopExp_Explorer ex(face_b, TopAbs_EDGE); ex.More(); ex.Next()) {
            const TopoDS_Shape& b_edge = ex.Current();
            if (!face_a_edge_map.Contains(b_edge)) {
                continue;
            }
            Standard_Integer one_based = edge_map.FindIndex(b_edge);
            if (one_based >= 1) {
                result.insert(static_cast<uint32_t>(one_based - 1));
            }
        }

        rust::Vec<uint32_t> out;
        for (uint32_t i : result) {
            out.push_back(i);
        }
        return out;
    } catch (Standard_Failure const& e) {
        throw std::runtime_error(std::string("OCCT shared_edges: ") + e.GetMessageString());
    } catch (std::exception const& e) {
        throw std::runtime_error(std::string("OCCT shared_edges: ") + e.what());
    } catch (...) {
        throw std::runtime_error("OCCT shared_edges: unknown C++ exception");
    }
}

// --- Export ---

// Process-global mutex for STEP export. OCCT's STEPControl_Writer (and its
// Transfer/Write pipeline) uses process-global state (XSAlgo session, interface
// model, shape naming tables) that is not thread-safe. This mutex serializes
// all concurrent export_step() calls across all kernel threads.
static std::mutex g_step_export_mutex;

rust::String export_step(const OcctShape& shape) {
    std::lock_guard<std::mutex> lock(g_step_export_mutex);
    try {
        STEPControl_Writer writer;
        writer.Transfer(shape.shape, STEPControl_AsIs);

        // Write to a temporary file, then read back
        char tmpname[] = "/tmp/reify_step_XXXXXX";
        int fd = mkstemp(tmpname);
        if (fd < 0) {
            throw std::runtime_error("Failed to create temp file for STEP export");
        }
        close(fd);

        IFSelect_ReturnStatus status = writer.Write(tmpname);
        if (status != IFSelect_RetDone) {
            std::remove(tmpname);
            throw std::runtime_error("STEPControl_Writer::Write failed");
        }

        std::ifstream ifs(tmpname);
        std::string content((std::istreambuf_iterator<char>(ifs)),
                            std::istreambuf_iterator<char>());
        ifs.close();
        std::remove(tmpname);

        return rust::String(content);
    } catch (Standard_Failure const& e) {
        throw std::runtime_error(std::string("OCCT export_step: ") + e.GetMessageString());
    } catch (std::exception const& e) {
        throw std::runtime_error(std::string("OCCT export_step: unexpected: ") + e.what());
    } catch (...) {
        throw std::runtime_error("OCCT export_step: unknown C++ exception");
    }
}

// --- BRep serialization ---

rust::String serialize_brep(const OcctShape& shape) {
    try {
        std::ostringstream oss;
        ::BRepTools::Write(shape.shape, oss);
        std::string content = oss.str();
        if (content.empty()) {
            throw std::runtime_error("BRepTools::Write produced empty output");
        }
        return rust::String(content);
    } catch (Standard_Failure const& e) {
        throw std::runtime_error(std::string("OCCT serialize_brep: ") + e.GetMessageString());
    } catch (std::exception const& e) {
        throw std::runtime_error(std::string("OCCT serialize_brep: unexpected: ") + e.what());
    } catch (...) {
        throw std::runtime_error("OCCT serialize_brep: unknown C++ exception");
    }
}

std::unique_ptr<OcctShape> deserialize_brep(const std::string& data) {
    try {
        ::BRep_Builder builder;
        auto result = std::make_unique<OcctShape>();
        std::istringstream iss(data);
        ::BRepTools::Read(result->shape, iss, builder);
        if (result->shape.IsNull()) {
            throw std::runtime_error("BRepTools::Read produced null shape");
        }
        return result;
    } catch (Standard_Failure const& e) {
        throw std::runtime_error(std::string("OCCT deserialize_brep: ") + e.GetMessageString());
    } catch (std::exception const& e) {
        throw std::runtime_error(std::string("OCCT deserialize_brep: unexpected: ") + e.what());
    } catch (...) {
        throw std::runtime_error("OCCT deserialize_brep: unknown C++ exception");
    }
}

// --- Tessellation ---

TessResult tessellate_shape(const OcctShape& shape, double tolerance) {
    try {
        BRepMesh_IncrementalMesh mesh(shape.shape, tolerance);
        mesh.Perform();
        if (!mesh.IsDone()) {
            throw std::runtime_error("BRepMesh_IncrementalMesh failed");
        }

        TessResult result;
        uint32_t vertex_offset = 0;

        for (TopExp_Explorer ex(shape.shape, TopAbs_FACE); ex.More(); ex.Next()) {
            TopoDS_Face face = TopoDS::Face(ex.Current());
            TopLoc_Location loc;
            Handle(Poly_Triangulation) tri = BRep_Tool::Triangulation(face, loc);
            if (tri.IsNull()) continue;

            int nb_nodes = tri->NbNodes();
            int nb_tris = tri->NbTriangles();

            // Extract vertices
            for (int i = 1; i <= nb_nodes; ++i) {
                gp_Pnt p = tri->Node(i);
                if (!loc.IsIdentity()) {
                    p.Transform(loc.Transformation());
                }
                result.vertices.push_back(static_cast<float>(p.X()));
                result.vertices.push_back(static_cast<float>(p.Y()));
                result.vertices.push_back(static_cast<float>(p.Z()));
            }

            // Extract normals — use stored normals if available, else compute from triangles
            if (tri->HasNormals()) {
                for (int i = 1; i <= nb_nodes; ++i) {
                    gp_Dir n = tri->Normal(i);
                    if (!loc.IsIdentity()) {
                        n.Transform(loc.Transformation());
                    }
                    result.normals.push_back(static_cast<float>(n.X()));
                    result.normals.push_back(static_cast<float>(n.Y()));
                    result.normals.push_back(static_cast<float>(n.Z()));
                }
            } else {
                // Compute per-vertex normals by averaging face normals
                std::vector<gp_Vec> vertex_normals(nb_nodes, gp_Vec(0, 0, 0));
                for (int i = 1; i <= nb_tris; ++i) {
                    int n1, n2, n3;
                    tri->Triangle(i).Get(n1, n2, n3);
                    gp_Pnt p1 = tri->Node(n1);
                    gp_Pnt p2 = tri->Node(n2);
                    gp_Pnt p3 = tri->Node(n3);
                    gp_Vec v1(p1, p2);
                    gp_Vec v2(p1, p3);
                    gp_Vec face_normal = v1.Crossed(v2);
                    vertex_normals[n1 - 1] += face_normal;
                    vertex_normals[n2 - 1] += face_normal;
                    vertex_normals[n3 - 1] += face_normal;
                }
                for (int i = 0; i < nb_nodes; ++i) {
                    gp_Vec n = vertex_normals[i];
                    double mag = n.Magnitude();
                    if (mag > CPP_DIR_MAG_MIN) {
                        n /= mag;
                    }
                    if (!loc.IsIdentity()) {
                        n.Transform(loc.Transformation());
                    }
                    result.normals.push_back(static_cast<float>(n.X()));
                    result.normals.push_back(static_cast<float>(n.Y()));
                    result.normals.push_back(static_cast<float>(n.Z()));
                }
            }

            // Extract indices (1-based → 0-based + offset)
            for (int i = 1; i <= nb_tris; ++i) {
                int n1, n2, n3;
                tri->Triangle(i).Get(n1, n2, n3);
                result.indices.push_back(vertex_offset + static_cast<uint32_t>(n1 - 1));
                result.indices.push_back(vertex_offset + static_cast<uint32_t>(n2 - 1));
                result.indices.push_back(vertex_offset + static_cast<uint32_t>(n3 - 1));
            }

            vertex_offset += static_cast<uint32_t>(nb_nodes);
        }

        return result;
    } catch (Standard_Failure const& e) {
        throw std::runtime_error(std::string("OCCT tessellate_shape: ") + e.GetMessageString());
    } catch (std::exception const& e) {
        throw std::runtime_error(std::string("OCCT tessellate_shape: unexpected: ") + e.what());
    } catch (...) {
        throw std::runtime_error("OCCT tessellate_shape: unknown C++ exception");
    }
}

} // namespace occt
