//! SI prefix and derived-unit tables + `.ri` source generator.
//!
//! Provides const tables for the 20 power-of-1000 SI prefixes (quecto..quetta)
//! and the standard SI derived units (N, Pa, J, W, Hz, V, ohm, S, F, H, Wb,
//! T, lm, lx, Bq, Gy, Sv, C, eV, bar, mbar, rpm, rad_per_s, Pa_s), together
//! with a programmatic generator that emits Reify unit declarations at
//! `load_stdlib()` time.

/// The 20 power-of-1000 SI prefixes, from quecto (1e-30) to quetta (1e30).
///
/// Excludes centi/deci/deca/hecto — the four non-power-of-1000 prefixes.
/// This matches the 2022 BIPM revision of the SI prefix set for engineering
/// use. ASCII `u` is the conventional stand-in for `µ` (micro).
pub const SI_PREFIXES: &[(&str, f64)] = &[
    ("q", 1e-30),
    ("r", 1e-27),
    ("y", 1e-24),
    ("z", 1e-21),
    ("a", 1e-18),
    ("f", 1e-15),
    ("p", 1e-12),
    ("n", 1e-9),
    ("u", 1e-6),
    ("m", 1e-3),
    ("k", 1e3),
    ("M", 1e6),
    ("G", 1e9),
    ("T", 1e12),
    ("P", 1e15),
    ("E", 1e18),
    ("Z", 1e21),
    ("Y", 1e24),
    ("R", 1e27),
    ("Q", 1e30),
];

/// SI base units that receive the full 20-prefix set, paired with their
/// dimension name. Excludes unprefixed bases themselves — those live in
/// `stdlib/units.ri` (m, kg, s, rad, K).
///
/// Note: `g` is used as the mass prefix base (not `kg`) because prefixes
/// can't stack, and `kg` is already the SI base unit. The generator
/// multiplies gram-prefix factors by 1e-3 and skips the `k` prefix to
/// avoid re-declaring `kg`.
pub const SI_PREFIX_BASES: &[(&str, &str)] = &[
    ("m", "Length"),
    ("g", "Mass"),
    ("s", "Time"),
    ("A", "Current"),
    ("K", "Temperature"),
    ("mol", "AmountOfSubstance"),
    ("cd", "LuminousIntensity"),
    ("rad", "Angle"),
];

/// Build the `.ri` source text for all SI units.
///
/// The generated source is compiled at `load_stdlib()` time as a synthetic
/// `std.si_units` module prepended to the stdlib chain. The text contains:
///   1. Prefixed base units (20 prefixes × 8 bases, minus `kg` special-case)
///
/// All factors are emitted as plain decimal literals (tree-sitter's
/// `number_literal` grammar does not accept scientific notation).
pub fn build_si_units_source() -> String {
    let mut out = String::new();
    out.push_str("// Generated by crates/reify-compiler/src/si_units.rs\n");
    out.push_str("// Do not edit by hand.\n\n");

    // Section 1: prefixed base units.
    out.push_str("// ── SI-prefixed base units ────────────────────────────\n");
    for (base, dim) in SI_PREFIX_BASES {
        // Gram is special: kg is the SI base, so each gram-prefix factor
        // must be multiplied by 1e-3 (since g = 0.001 kg), and the `k`
        // prefix must be skipped to avoid re-declaring kg.
        let base_factor_exp: i32 = if *base == "g" { -3 } else { 0 };

        for (prefix, prefix_factor) in SI_PREFIXES {
            // Skip `k` + `g` → would produce kg (already SI base).
            if *base == "g" && *prefix == "k" {
                continue;
            }
            let prefix_exp = prefix_factor.log10().round() as i32;
            let total_exp = prefix_exp + base_factor_exp;
            let factor_str = format_power_of_ten(total_exp);
            out.push_str(&format!(
                "pub unit {}{} : {} = {}\n",
                prefix, base, dim, factor_str
            ));
        }
        out.push('\n');
    }

    out
}

/// Format a power of 10 as a plain decimal string.
///
/// - `n >= 0` → `"1" + n zeros` (e.g., 3 → "1000", 0 → "1")
/// - `n < 0` → `"0." + (|n|-1) zeros + "1"` (e.g., -3 → "0.001")
///
/// Used instead of `f64` formatting because the tree-sitter grammar
/// (`/\d+(\.\d+)?/`) does not accept scientific notation, and f64
/// can't faithfully represent 1e-30 as a plain decimal anyway.
fn format_power_of_ten(n: i32) -> String {
    if n == 0 {
        "1".to_string()
    } else if n > 0 {
        let mut s = String::with_capacity(n as usize + 1);
        s.push('1');
        for _ in 0..n {
            s.push('0');
        }
        s
    } else {
        // e.g. n = -3 → "0.001"
        let zeros = (-n - 1) as usize;
        let mut s = String::with_capacity(zeros + 3);
        s.push_str("0.");
        for _ in 0..zeros {
            s.push('0');
        }
        s.push('1');
        s
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn format_power_of_ten_cases() {
        assert_eq!(format_power_of_ten(0), "1");
        assert_eq!(format_power_of_ten(1), "10");
        assert_eq!(format_power_of_ten(3), "1000");
        assert_eq!(format_power_of_ten(6), "1000000");
        assert_eq!(format_power_of_ten(-1), "0.1");
        assert_eq!(format_power_of_ten(-3), "0.001");
        assert_eq!(format_power_of_ten(-9), "0.000000001");
    }
}
