//! Tests for the `Nm` torque unit symbol in stdlib/units.ri (task θ).
//!
//! Pins docs/prds/v0_6/angle-units-surface-convergence.md task θ / contract C3
//! / boundary row B9: `pub unit Nm : Torque = 1` is hand-declared (never
//! generated by si_units.rs — `N`'s prefix set is `Only(["k","M","G"])`) and is
//! case-distinct from the generated `nm` (nanometre, prefix "n" × base `m`).
//!
//! Case-distinctness is an EXISTING property of `UnitRegistry::lookup`
//! (crates/reify-compiler/src/units.rs:1533), an exact HashMap key match with
//! zero case folding — this file PINS that property against `Nm`/`nm`/`NM`/`nM`
//! rather than building it.

mod common;

use common::{assert_eq_rel, assert_simple_unit, stdlib_param_si_value};
use reify_core::{DimensionVector, Severity};
use reify_test_support::compile_source_with_stdlib;

// ─── step-1/2: Nm — Torque, case-distinct from nm/NM/nM ──────────────────────

#[test]
fn nm_torque_is_case_distinct_from_nm_nanometre() {
    // (a) POSITIVE: `5Nm` resolves to Torque, si_value exactly 5.0 (factor 1).
    let (v, d) = stdlib_param_si_value("Torque", "5Nm");
    assert_eq_rel(v, 5.0, 1e-12, "5Nm should be 5.0 (SI coherent Torque unit)");
    assert_eq!(d, DimensionVector::TORQUE);

    // (b) BASELINE: `5nm` must not move — still nanometre, Length, 5e-9 m.
    let (v, d) = stdlib_param_si_value("Length", "5nm");
    assert_eq_rel(v, 5e-9, 1e-12, "5nm should still be 5e-9 m (nanometre)");
    assert_eq!(d, DimensionVector::LENGTH);

    // (c)/(d) NEGATIVE: `NM` and `nM` are ungeneratable and must stay unknown.
    // `M` is an SI *prefix* (1e6, si_units.rs:21) but no base or derived unit is
    // *named* `M`, and `N` is not a prefix at all — so si_units.rs's
    // `<prefix><name>` concatenation can never produce either spelling. Use
    // `compile_source_with_stdlib` directly here (not `stdlib_param_si_value`,
    // which panics on any error diagnostic and so cannot express a negative).

    // (c) NEGATIVE: `5NM` must remain an unknown unit naming "NM".
    let source = "structure def S { param x : Torque = 5NM }";
    let module = compile_source_with_stdlib(source);
    let errors: Vec<_> = module
        .diagnostics
        .iter()
        .filter(|d| d.severity == Severity::Error)
        .collect();
    assert!(
        !errors.is_empty(),
        "expected an Error diagnostic for unknown unit 'NM', got none"
    );
    assert!(
        errors.iter().any(|d| d.message.contains("NM")),
        "expected an Error naming 'NM'; got: {:?}",
        errors.iter().map(|d| &d.message).collect::<Vec<_>>()
    );

    // (d) NEGATIVE: `5nM` must remain an unknown unit naming "nM".
    let source = "structure def S { param x : Torque = 5nM }";
    let module = compile_source_with_stdlib(source);
    let errors: Vec<_> = module
        .diagnostics
        .iter()
        .filter(|d| d.severity == Severity::Error)
        .collect();
    assert!(
        !errors.is_empty(),
        "expected an Error diagnostic for unknown unit 'nM', got none"
    );
    assert!(
        errors.iter().any(|d| d.message.contains("nM")),
        "expected an Error naming 'nM'; got: {:?}",
        errors.iter().map(|d| &d.message).collect::<Vec<_>>()
    );
}

#[test]
fn stdlib_units_module_contains_nm_with_torque_dimension() {
    assert_simple_unit("Nm", DimensionVector::TORQUE, 1.0, 1e-12);
}
