//! Tests for the `Nm` torque unit symbol in stdlib/units.ri (task θ).
//!
//! Pins docs/prds/v0_6/angle-units-surface-convergence.md task θ / contract C3
//! / boundary row B9: `pub unit Nm : Torque = 1` is hand-declared (never
//! generated by si_units.rs — `N`'s prefix set is `Only(["k","M","G"])`) and is
//! case-distinct from the generated `nm` (nanometre, prefix "n" × base `m`).
//!
//! Case-distinctness is an EXISTING property of `UnitRegistry::lookup`
//! (crates/reify-compiler/src/units.rs:1533), an exact HashMap key match with
//! zero case folding — this file PINS that property against `Nm`/`nm`/`NM`/`nM`
//! rather than building it.

mod common;

use common::{assert_eq_rel, assert_simple_unit, stdlib_param_si_value};
use reify_core::{DimensionVector, Severity};
use reify_test_support::compile_source_with_stdlib;

// ─── step-1/2: Nm — Torque, case-distinct from nm/NM/nM ──────────────────────

#[test]
fn nm_torque_is_case_distinct_from_nm_nanometre() {
    // (a) POSITIVE: `5Nm` resolves to Torque, si_value exactly 5.0 (factor 1).
    let (v, d) = stdlib_param_si_value("Torque", "5Nm");
    assert_eq_rel(v, 5.0, 1e-12, "5Nm should be 5.0 (SI coherent Torque unit)");
    assert_eq!(d, DimensionVector::TORQUE);

    // (b) BASELINE: `5nm` must not move — still nanometre, Length, 5e-9 m.
    let (v, d) = stdlib_param_si_value("Length", "5nm");
    assert_eq_rel(v, 5e-9, 1e-12, "5nm should still be 5e-9 m (nanometre)");
    assert_eq!(d, DimensionVector::LENGTH);

    // (c)/(d) NEGATIVE: `NM` and `nM` are ungeneratable and must stay unknown.
    // `M` is an SI *prefix* (1e6, si_units.rs:21) but no base or derived unit is
    // *named* `M`, and `N` is not a prefix at all — so si_units.rs's
    // `<prefix><name>` concatenation can never produce either spelling. Use
    // `compile_source_with_stdlib` directly here (not `stdlib_param_si_value`,
    // which panics on any error diagnostic and so cannot express a negative).

    // (c) NEGATIVE: `5NM` must remain an unknown unit naming "NM".
    let source = "structure def S { param x : Torque = 5NM }";
    let module = compile_source_with_stdlib(source);
    let errors: Vec<_> = module
        .diagnostics
        .iter()
        .filter(|d| d.severity == Severity::Error)
        .collect();
    assert!(
        !errors.is_empty(),
        "expected an Error diagnostic for unknown unit 'NM', got none"
    );
    assert!(
        errors.iter().any(|d| d.message.contains("NM")),
        "expected an Error naming 'NM'; got: {:?}",
        errors.iter().map(|d| &d.message).collect::<Vec<_>>()
    );

    // (d) NEGATIVE: `5nM` must remain an unknown unit naming "nM".
    let source = "structure def S { param x : Torque = 5nM }";
    let module = compile_source_with_stdlib(source);
    let errors: Vec<_> = module
        .diagnostics
        .iter()
        .filter(|d| d.severity == Severity::Error)
        .collect();
    assert!(
        !errors.is_empty(),
        "expected an Error diagnostic for unknown unit 'nM', got none"
    );
    assert!(
        errors.iter().any(|d| d.message.contains("nM")),
        "expected an Error naming 'nM'; got: {:?}",
        errors.iter().map(|d| &d.message).collect::<Vec<_>>()
    );
}

#[test]
fn stdlib_units_module_contains_nm_with_torque_dimension() {
    assert_simple_unit("Nm", DimensionVector::TORQUE, 1.0, 1e-12);
}

// ─── consumer-level pins: PRD §12 θ signal + B9 postcondition ────────────────

#[test]
fn nm_equals_n_times_m_per_rad_and_is_not_energy() {
    // `N` has factor 1.0 (si_units.rs:180-184); `m` and `rad` are SI bases with
    // factor 1 — so both sides resolve to exactly 5.0. This is an exact
    // identity, not a tuned tolerance.
    let (nm_v, nm_d) = stdlib_param_si_value("Torque", "5Nm");
    let (ex_v, ex_d) = stdlib_param_si_value("Torque", "5N*m/rad");
    assert_eq_rel(nm_v, ex_v, 1e-12, "5Nm should equal 5N*m/rad in SI");
    assert_eq!(nm_d, ex_d);

    // Torque≠Energy guard: TORQUE and ENERGY differ ONLY in the Angle⁻¹ slot
    // (TORQUE = FORCE·LENGTH/ANGLE, ENERGY = FORCE·LENGTH), so a `Nm : Energy`
    // typo in units.ri would otherwise pass every other assertion in this file.
    //
    // Deliberately NOT asserted here: `canonical_name()` or any rendered
    // dimension/unit display string. TORQUE and ROTATIONAL_STIFFNESS currently
    // share one vector, and `canonical_name()` is first-match-wins with the
    // TORQUE row placed after RotationalStiffness, so today that vector
    // renders as "RotationalStiffness". Task #5799 re-dimensions
    // ROTATIONAL_STIFFNESS, at which point `canonical_name()` for this vector
    // flips to "Torque" — structural `DimensionVector` equality is invariant
    // across that flip, so asserting on it here would go red for reasons
    // outside this task's scope.
    assert_ne!(
        nm_d,
        DimensionVector::ENERGY,
        "Nm's dimension must be Torque, not Energy (they differ only in the Angle⁻¹ slot)"
    );
}

/// Loads the already-committed, previously-unreferenced prd-gate fixture
/// (`tests/prd-gate/fixtures/unit_nm_torque_immediate.ri`) and asserts it
/// compiles clean — the end-to-end user-observable θ signal (PRD §12).
/// Path resolution mirrors the idiom at
/// `crates/reify-compiler/tests/buckling_stdlib_compile.rs:700-712` and
/// `crates/reify-eval/tests/no_stale_undef_invariant_gate.rs:766-775`: the
/// committed fixture is the single source of truth, read from disk rather
/// than inlined, so it cannot drift out of sync. Read-only input: this test
/// must never edit the fixture file.
#[test]
fn prd_gate_fixture_unit_nm_torque_immediate_compiles_clean() {
    let path = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../../tests/prd-gate/fixtures/unit_nm_torque_immediate.ri");
    let src = std::fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("failed to read fixture {}: {}", path.display(), e));

    let module = compile_source_with_stdlib(&src);
    let errors: Vec<_> = module
        .diagnostics
        .iter()
        .filter(|d| d.severity == Severity::Error)
        .collect();
    assert!(
        errors.is_empty(),
        "fixture {} should compile with no errors, got: {:?}",
        path.display(),
        errors
    );
}
