#!/usr/bin/env bash
# tests/infra/test_host_global_unit_pinning.sh
#
# Guards that HOST-GLOBAL systemd --user units generated by scripts/setup-dev.sh
# name a STABLE main-checkout path in their ExecStart, never the (possibly
# ephemeral) checkout that happened to invoke the installer.
#
# Background (task 5888): setup-dev.sh's install_build_services() writes four
# units into the host-global $HOME/.config/systemd/user.  Until the fix that
# lands WITH this suite, the two jobserver units derived their ExecStart from
# ${BASH_SOURCE[0]} — the INVOKING checkout.  Run once from a warm lane
# (/home/leo/src/warm-lanes/worktrees/_lane-N), those two units were pinned at
# a path that vanishes the moment that lane is reclaimed and re-seeded.  From
# then on every start fails with status=203/EXEC, the dual-pool cargo jobserver
# never comes up, and every verify silently fails-open to a private -j(nproc) —
# completely silently, because nothing Requires= those units.  The fix sources
# scripts/lib_main_checkout.sh from install_build_services() and interpolates
# the resolved main checkout into both ExecStarts (and the chmod that makes
# exactly those two executables runnable), leaving every per-worktree call site
# alone — which is what B5b/B5c pin.  Same defect class, same fix shape, as the
# prior art in scripts/setup-agent-cache-redirect.sh:498-507,549-560, and the
# same host convention already encoded on
# deploy/systemd/reify-warm-lane{,-gc}.service
# (#4720): a host-global unit names the stable main checkout.
#
# Part A — the RESOLVER contract (scripts/lib_main_checkout.sh).
# Part B — the GENERATOR contract (see the section banner further down).
#
# WHY PART A EXISTS SEPARATELY: `git rev-parse --git-common-dir` is RELATIVE
# inside the main checkout (`.git`, or `../../.git` from a subdir) and absolute
# only inside a linked worktree, so the obvious `dirname "$(git rev-parse
# --git-common-dir)"` yields `.` exactly where it must not.  These cases pin
# `--path-format=absolute` and the `git -C` anchoring that make it uniform.
#
# HERMETIC (`pool` bucket in run-all-classification.manifest): every fixture is
# a mktemp -d git repo.  Nothing here reads or writes the real
# ~/.config/systemd/user, runs systemctl, or touches a host FIFO.
#
# Auto-discovered by tests/infra/run_all.sh via the test_*.sh glob.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
LIB_MAIN_CHECKOUT="$REPO_ROOT/scripts/lib_main_checkout.sh"

[ -f "$SCRIPT_DIR/test_helpers.sh" ] || {
    echo "ERROR: test_helpers.sh not found at $SCRIPT_DIR/test_helpers.sh" >&2
    exit 1
}
# shellcheck source=tests/infra/test_helpers.sh
source "$SCRIPT_DIR/test_helpers.sh"

_TMPDIRS=()
cleanup() {
    local d
    for d in "${_TMPDIRS[@]:-}"; do
        [ -n "$d" ] && rm -rf "$d"
    done
    # MANDATORY. This runs from the EXIT trap, so its return value BECOMES the
    # suite's exit status: with an empty _TMPDIRS the loop's last command is a
    # false `[ -n "" ]`, and the suite would exit 1 with every assertion green.
    return 0
}
trap cleanup EXIT

echo "=== host-global systemd unit ExecStart pinning ==="

# ---------------------------------------------------------------------------
# _mk_two_checkout_fixture <stem> — MAIN-SHELL ONLY. Mints a temp MAIN checkout
# with a REAL linked worktree beside it, and sets FIX_ROOT / FIX_MAIN /
# FIX_LANE.
#
# MUST NOT be called from a command substitution. It registers its mktemp root
# in _TMPDIRS for the EXIT trap, and an append performed inside a
# command-substitution SUBSHELL is silently discarded when that subshell exits
# — leaking the whole fixture tree (git repo + linked worktree) on every run.
# That is why this sets globals instead of echoing them, the same subshell trap
# test_helpers.sh's make_isolated_lane documents.
#
# A real `git worktree add` (not a simulated directory layout) is what makes
# this reproduce the bug rather than model it: the linked worktree is the only
# thing that makes --git-common-dir point somewhere other than the CWD's .git.
#
# Paths are canonicalized with `pwd -P` so they compare byte-for-byte against
# git's own absolute output.
# ---------------------------------------------------------------------------
_mk_two_checkout_fixture() {
    local stem="$1" root
    root="$(mktemp -d "${TMPDIR:-/tmp}/${stem}-XXXXXX")" || return 1
    root="$(cd "$root" && pwd -P)" || return 1
    _TMPDIRS+=("$root")
    FIX_ROOT="$root"
    FIX_MAIN="$root/main"
    FIX_LANE="$root/lane"
    mkdir -p "$FIX_MAIN/sub/deep" || return 1
    git init -q -b main "$FIX_MAIN" || return 1
    git -C "$FIX_MAIN" -c user.name=t -c user.email=t@example.invalid \
        -c commit.gpgsign=false commit -q --allow-empty -m init || return 1
    git -C "$FIX_MAIN" worktree add -q --detach "$FIX_LANE" >/dev/null 2>&1 || return 1
    mkdir -p "$FIX_LANE/sub/deep" || return 1
    return 0
}

# ---------------------------------------------------------------------------
# _resolver_out <cwd> <anchor> [ENV=VAL ...] — stdout of
# `reify_main_checkout <anchor>` run in a FRESH bash, from <cwd>.
#
# A fresh bash per case (rather than sourcing once into this shell) is what
# makes the ambient-CWD and REIFY_MAIN_CHECKOUT cases genuinely independent:
# bash's rules for a `VAR=v func` prefix on a *function* are subtle, and a
# leaked CWD or a leaked override would silently make a later case vacuous.
# GIT_DIR/GIT_WORK_TREE are unset because either would defeat `git -C`
# anchoring, and REIFY_MAIN_CHECKOUT is unset unless the caller re-supplies it.
#
# A FAILED call reads back as the EMPTY string at every call site below, never
# as a placeholder: a non-empty sentinel would satisfy the `-n` guards in the
# negative assertions (A2e, A5a) and let them pass vacuously against a resolver
# that does not exist at all.
# ---------------------------------------------------------------------------
_resolver_out() {
    local cwd="$1" anchor="$2"
    shift 2
    (
        cd "$cwd" || exit 1
        env -u GIT_DIR -u GIT_WORK_TREE -u GIT_INDEX_FILE -u REIFY_MAIN_CHECKOUT "$@" \
            bash -c 'source "$1" || exit 1; reify_main_checkout "$2"' _ \
            "$LIB_MAIN_CHECKOUT" "$anchor"
    )
}

# =============================================================================
# PART A — the main-checkout RESOLVER contract
# =============================================================================
echo ""
echo "--- A0: scripts/lib_main_checkout.sh exists and is sourceable ---"

assert "scripts/lib_main_checkout.sh exists" \
    test -f "$LIB_MAIN_CHECKOUT"

assert "scripts/lib_main_checkout.sh parses (bash -n)" \
    bash -n "$LIB_MAIN_CHECKOUT"

assert "sourcing scripts/lib_main_checkout.sh defines reify_main_checkout" \
    bash -c 'source "$1" || exit 1; declare -F reify_main_checkout >/dev/null' _ "$LIB_MAIN_CHECKOUT"

echo ""
echo "--- A1: two-checkout fixture (real linked worktree) ---"

FIX_ROOT=""; FIX_MAIN=""; FIX_LANE=""
_mk_two_checkout_fixture reify-mainck   # main shell, NOT $( ) — see the header
FIX_NOREPO="$FIX_ROOT/outside"
mkdir -p "$FIX_NOREPO"

# The fixture's own registration is what the EXIT trap reclaims; assert it
# happened rather than trusting it, so a future refactor that reintroduces the
# command-substitution form fails here instead of leaking a git repo per run.
assert "fixture: the mktemp root is registered in _TMPDIRS for the EXIT trap" \
    bash -c '[ "$1" = "$2" ] && [ -n "$2" ]' _ "${_TMPDIRS[0]:-}" "$FIX_ROOT"

# NON-VACUITY CONTROL, asserted BEFORE any resolver case: if these two paths
# were equal, every "resolves to the main checkout, not the lane" assertion
# below would pass no matter what the resolver did.
assert "fixture: the main checkout and the linked worktree are DISTINCT paths" \
    bash -c '[ "$1" != "$2" ]' _ "$FIX_MAIN" "$FIX_LANE"

assert "fixture: the linked worktree really is a linked worktree of the main checkout" \
    bash -c '[ "$(git -C "$2" rev-parse --path-format=absolute --git-common-dir)" = "$1/.git" ]' \
        _ "$FIX_MAIN" "$FIX_LANE"

# Precondition for the "outside any repo" case: $FIX_NOREPO must genuinely be
# outside every repository.  It normally is (TMPDIR is /tmp), but a TMPDIR
# nested inside a checkout would silently turn that case into a no-op, so the
# requirement is asserted rather than assumed.
assert "fixture: the non-repo scratch dir is genuinely outside any git repository" \
    bash -c '! git -C "$1" rev-parse --git-common-dir >/dev/null 2>&1' _ "$FIX_NOREPO"

echo ""
echo "--- A2: reify_main_checkout resolves the MAIN checkout from every anchor ---"

_R_MAIN="$(_resolver_out / "$FIX_MAIN")" || _R_MAIN=""
_R_MAIN_SUB="$(_resolver_out / "$FIX_MAIN/sub/deep")" || _R_MAIN_SUB=""
_R_LANE="$(_resolver_out / "$FIX_LANE")" || _R_LANE=""
_R_LANE_SUB="$(_resolver_out / "$FIX_LANE/sub/deep")" || _R_LANE_SUB=""

assert "A2a: anchored at the main checkout -> the main checkout root" \
    test "$_R_MAIN" = "$FIX_MAIN"

# Guards the --git-common-dir-is-RELATIVE-here trap: bare output is `.git` in
# the main checkout and `../../.git` from a subdir of it, so a resolver without
# --path-format=absolute answers `.` / `..` and is wrong precisely here.
assert "A2b: anchored at a SUBDIR of the main checkout -> the main checkout root" \
    test "$_R_MAIN_SUB" = "$FIX_MAIN"

assert "A2c: anchored at the LINKED WORKTREE -> the MAIN checkout root" \
    test "$_R_LANE" = "$FIX_MAIN"

assert "A2d: anchored at a SUBDIR of the linked worktree -> the MAIN checkout root" \
    test "$_R_LANE_SUB" = "$FIX_MAIN"

# THE BUG, stated directly: the whole defect is a host-global unit pinned at the
# linked worktree.  This is the assertion that would have caught it.
assert "A2e: the linked-worktree answer is NOT the linked worktree itself (the bug)" \
    bash -c '[ -n "$1" ] && [ "$1" != "$2" ]' _ "$_R_LANE" "$FIX_LANE"

echo ""
echo "--- A3: REIFY_MAIN_CHECKOUT override wins over the git derivation ---"

_R_OVERRIDE="$(_resolver_out / "$FIX_LANE" "REIFY_MAIN_CHECKOUT=$FIX_ROOT/override")" \
    || _R_OVERRIDE=""

assert "A3a: REIFY_MAIN_CHECKOUT set in the invocation env wins over git derivation" \
    test "$_R_OVERRIDE" = "$FIX_ROOT/override"

# ...and does not leak: the very next call, without it, must derive again.
assert "A3b: the override does not persist into a subsequent un-overridden call" \
    bash -c '[ "$1" = "$2" ]' _ "$(_resolver_out / "$FIX_LANE" || true)" "$FIX_MAIN"

echo ""
echo "--- A4: unresolvable anchors fail closed (non-zero, EMPTY stdout) ---"

_NOREPO_OUT=""; _NOREPO_RC=0
_NOREPO_OUT="$(_resolver_out / "$FIX_NOREPO" 2>/dev/null)" || _NOREPO_RC=$?

assert "A4a: anchored outside any git repo returns non-zero" \
    test "$_NOREPO_RC" -ne 0

# Never emit a guessed path: a bogus non-empty answer would be interpolated
# straight into an ExecStart and produce a silently dead unit.
assert "A4b: anchored outside any git repo prints NOTHING" \
    test -z "$_NOREPO_OUT"

_MISSING_OUT=""; _MISSING_RC=0
_MISSING_OUT="$(_resolver_out / "$FIX_ROOT/does-not-exist" 2>/dev/null)" || _MISSING_RC=$?

assert "A4c: anchored at a non-existent directory returns non-zero" \
    test "$_MISSING_RC" -ne 0

assert "A4d: anchored at a non-existent directory prints NOTHING" \
    test -z "$_MISSING_OUT"

echo ""
echo "--- A5: resolution does not depend on ambient CWD ---"

# `git rev-parse` resolves against CWD and setup-dev.sh has no top-level `cd`,
# so CWD is whatever the operator happened to be in.  Only a `git -C`-anchored
# resolver is deterministic.  Both answers must ALSO equal the main checkout,
# so two identical failures cannot pass this vacuously.
_R_CWD_SLASH="$(_resolver_out / "$FIX_LANE")" || _R_CWD_SLASH=""
_R_CWD_ROOT="$(_resolver_out "$FIX_ROOT" "$FIX_LANE")" || _R_CWD_ROOT=""

_CWD_INDEP=no
if [ -n "$_R_CWD_SLASH" ] && [ "$_R_CWD_SLASH" = "$_R_CWD_ROOT" ] && [ "$_R_CWD_SLASH" = "$FIX_MAIN" ]; then
    _CWD_INDEP=yes
fi

assert "A5a: same anchor from CWD=/ and CWD=<fixture root> -> same answer, == main checkout" \
    test "$_CWD_INDEP" = yes

# =============================================================================
# PART B — the GENERATOR contract (setup-dev.sh install_build_services)
#
# Asserts on what the installer actually WRITES, in a sandboxed HOME. It does
# NOT inspect the real ~/.config/systemd/user: the live units were already
# hand-repointed by operator action on 2026-08-15, so any check against them
# would pass vacuously and prove nothing about the generator — which is the
# whole remaining value here. Nothing below runs systemctl (a restart of
# reify-jobserver.service re-seeds both FIFO pools and every in-flight verify
# rustc holding a token loses it permanently, fleet-wide), touches a host FIFO,
# or writes outside its mktemp root.
# =============================================================================
echo ""
echo "--- B0: generator fixture (function extracted into a FAKE LANE) ---"

# ---------------------------------------------------------------------------
# _mk_generator_fixture <stem> — MAIN-SHELL ONLY (see _mk_two_checkout_fixture
# for why this sets globals rather than echoing them). Sets GEN_ROOT/GEN_MAIN/
# GEN_LANE/GEN_HOME/GEN_UNITS.
#
# The executable stubs and a copy of lib_main_checkout.sh are COMMITTED before
# `git worktree add`, so the linked worktree carries them too — the installer
# must be able to find its executables in whichever tree it ends up pinning,
# or a passing test could not distinguish "pinned correctly" from "chmod
# happened to fail".
#
# install_build_services() is extracted by column-0 sed anchors and written to
# <fake lane>/scripts/setup-dev.sh, so ${BASH_SOURCE[0]} inside the function
# resolves to the FAKE LANE. That is what reproduces the bug's exact trigger
# condition — an installer invoked from a warm lane — rather than simulating
# it. setup-dev.sh cannot simply be sourced: it is straight-line and would
# apt-install, curl rustup and build native deps long before reaching the
# function.
# ---------------------------------------------------------------------------
_mk_generator_fixture() {
    local stem="$1" root
    root="$(mktemp -d "${TMPDIR:-/tmp}/${stem}-XXXXXX")" || return 1
    root="$(cd "$root" && pwd -P)" || return 1
    _TMPDIRS+=("$root")
    GEN_ROOT="$root"
    GEN_MAIN="$root/main"
    GEN_LANE="$root/lane"
    GEN_HOME="$root/home"
    GEN_UNITS="$GEN_HOME/.config/systemd/user"

    mkdir -p "$GEN_MAIN/scripts" "$GEN_HOME/.cargo/bin" "$root/shim" || return 1

    # A no-op `systemctl` earlier on PATH than the real one. The installer runs
    # `daemon-reload` and `enable --now`; neither may reach the host.
    printf '#!/usr/bin/env bash\nexit 0\n' > "$root/shim/systemctl" || return 1
    chmod +x "$root/shim/systemctl" || return 1

    # The two executables the jobserver units name in their ExecStart, plus the
    # resolver the installer sources.
    printf '#!/usr/bin/env bash\nexit 0\n' > "$GEN_MAIN/scripts/jobserver-balancer.py" || return 1
    printf '#!/usr/bin/env bash\nexit 0\n' > "$GEN_MAIN/scripts/jobserver-canary.sh" || return 1
    cp "$REPO_ROOT/scripts/lib_main_checkout.sh" "$GEN_MAIN/scripts/lib_main_checkout.sh" || return 1
    chmod +x "$GEN_MAIN/scripts/jobserver-balancer.py" "$GEN_MAIN/scripts/jobserver-canary.sh" || return 1

    git init -q -b main "$GEN_MAIN" || return 1
    git -C "$GEN_MAIN" add -A || return 1
    git -C "$GEN_MAIN" -c user.name=t -c user.email=t@example.invalid \
        -c commit.gpgsign=false commit -q -m init || return 1
    git -C "$GEN_MAIN" worktree add -q --detach "$GEN_LANE" >/dev/null 2>&1 || return 1

    mkdir -p "$GEN_LANE/scripts" || return 1
    sed -n '/^install_build_services() {$/,/^}$/p' "$REPO_ROOT/scripts/setup-dev.sh" \
        > "$GEN_LANE/scripts/setup-dev.sh" || return 1
    return 0
}

# ---------------------------------------------------------------------------
# _run_generator — source the extracted function in a sandboxed environment and
# invoke it. HOME is the fixture's, PATH is shimmed, and the log helpers
# setup-dev.sh defines at top level (which the extraction deliberately does not
# carry) are stubbed. warn/err are echoed to stderr so a fallback taken during
# the run is visible in the captured-output dump of a failing assert.
# ---------------------------------------------------------------------------
_run_generator() {
    env -u REIFY_MAIN_CHECKOUT -u REIFY_SCCACHE_SIZE \
        HOME="$GEN_HOME" PATH="$GEN_ROOT/shim:$PATH" \
        bash -c '
            set -euo pipefail
            info() { :; }
            ok()   { :; }
            warn() { echo "warn: $*" >&2; }
            err()  { echo "err: $*" >&2; }
            source "$1"
            install_build_services
        ' _ "$GEN_LANE/scripts/setup-dev.sh"
}

# ---------------------------------------------------------------------------
# _exec_lines <unit_dir> — every `Exec*=` line across every emitted *.service,
# as "<unit basename>|<argv0>".
#
# argv[0] ONLY — the first whitespace-separated token, with systemd's `-@+!:`
# run-time prefix characters stripped. A worktree path passed as a DATA
# ARGUMENT is legitimate (deploy/systemd/reify-warm-lane-gc.service correctly
# carries `--mount /home/leo/src/warm-lanes/worktrees`), so a naive grep for
# the lane path over whole unit files would over-match and make this guard
# untrustworthy. Only the EXECUTABLE is the defect.
# ---------------------------------------------------------------------------
_exec_lines() {
    local unit_dir="$1" f line val
    for f in "$unit_dir"/*.service; do
        [ -f "$f" ] || continue
        while IFS= read -r line || [ -n "$line" ]; do
            case "$line" in
                Exec*=*) ;;
                *) continue ;;
            esac
            val="${line#*=}"
            while [ -n "$val" ]; do
                case "$val" in
                    [-@+!:]*) val="${val#?}" ;;
                    *) break ;;
                esac
            done
            printf '%s|%s\n' "${f##*/}" "${val%%[[:space:]]*}"
        done < "$f"
    done
}

GEN_ROOT=""; GEN_MAIN=""; GEN_LANE=""; GEN_HOME=""; GEN_UNITS=""
_mk_generator_fixture reify-genfix   # main shell, NOT $( )

# NON-VACUITY GUARDS on the extraction, asserted BEFORE the run. A future
# refactor of setup-dev.sh must fail this suite loudly rather than silently
# test an empty snippet.
_EXTRACT="$GEN_LANE/scripts/setup-dev.sh"

assert "B0a: the extracted snippet is non-empty" \
    test -s "$_EXTRACT"

assert "B0b: the extracted snippet defines install_build_services" \
    grep -qF 'install_build_services() {' "$_EXTRACT"

assert "B0c: the extracted snippet carries the balancer ExecStart" \
    bash -c 'grep -E "^ExecStart=.*jobserver-balancer\.py" "$1" >/dev/null' _ "$_EXTRACT"

assert "B0d: the extracted snippet carries the canary ExecStart" \
    bash -c 'grep -E "^ExecStart=.*jobserver-canary\.sh" "$1" >/dev/null' _ "$_EXTRACT"

# The bug's trigger condition: the installer is running from a DIFFERENT tree
# than the one its host-global units must name.
assert "B0e: the fake lane and the main checkout are DISTINCT paths" \
    bash -c '[ "$1" != "$2" ]' _ "$GEN_LANE" "$GEN_MAIN"

echo ""
echo "--- B1: install_build_services() emits units into the sandboxed HOME ---"

_GEN_RC=0
_GEN_ERR="$GEN_ROOT/generator.err"
_run_generator >"$GEN_ROOT/generator.out" 2>"$_GEN_ERR" || _GEN_RC=$?

assert "B1a: install_build_services() completes successfully in the sandbox" \
    bash -c '[ "$1" = "0" ] || { cat "$2" >&2; exit 1; }' _ "$_GEN_RC" "$_GEN_ERR"

assert "B1b: it wrote reify-jobserver.service into the sandboxed unit dir" \
    test -f "$GEN_UNITS/reify-jobserver.service"

assert "B1c: it wrote reify-jobserver-canary.service into the sandboxed unit dir" \
    test -f "$GEN_UNITS/reify-jobserver-canary.service"

assert "B1d: it wrote nothing outside the sandbox (real \$HOME untouched by construction)" \
    bash -c '[ "$(ls -1 "$1"/*.service 2>/dev/null | wc -l)" -ge 3 ]' _ "$GEN_UNITS"

echo ""
echo "--- B2: both jobserver ExecStarts name the MAIN checkout ---"

_EXEC_BALANCER="$(grep -E '^ExecStart=' "$GEN_UNITS/reify-jobserver.service" 2>/dev/null | head -1 || true)"
_EXEC_CANARY="$(grep -E '^ExecStart=' "$GEN_UNITS/reify-jobserver-canary.service" 2>/dev/null | head -1 || true)"

assert "B2a: reify-jobserver.service ExecStart == <main checkout>/scripts/jobserver-balancer.py" \
    test "$_EXEC_BALANCER" = "ExecStart=$GEN_MAIN/scripts/jobserver-balancer.py"

# Asserted SEPARATELY from the balancer on purpose: there are TWO defective
# ExecStart sites, and a fix that catches only the first leaves the leak canary
# permanently dead — which is exactly how the depletion self-heal stayed dead
# through the 2026-08-13 incident.
assert "B2b: reify-jobserver-canary.service ExecStart == <main checkout>/scripts/jobserver-canary.sh" \
    test "$_EXEC_CANARY" = "ExecStart=$GEN_MAIN/scripts/jobserver-canary.sh"

echo ""
echo "--- B3: no emitted unit EXECUTES anything under the invoking lane ---"

_EXEC_ALL="$GEN_ROOT/exec-lines.txt"
_exec_lines "$GEN_UNITS" > "$_EXEC_ALL"
_EXEC_COUNT="$(grep -c . "$_EXEC_ALL" || true)"

# Non-vacuity: the sweep must have actually examined something. The four units
# carry six Exec* lines today (sccache Pre+Start, jobserver Pre+Start+StopPost,
# canary Start); a lower bound of 3 leaves room for churn without letting an
# empty sweep report all-clear.
assert "B3a: the argv0 sweep examined at least 3 Exec* lines (non-vacuity)" \
    test "$_EXEC_COUNT" -ge 3

# Catches a future FIFTH host-global unit on arrival, not just the two known
# ones.
assert "B3b: no Exec* argv[0] in any emitted unit lives under the invoking lane" \
    bash -c '! cut -d"|" -f2 "$1" | grep -qF "$2/"' _ "$_EXEC_ALL" "$GEN_LANE"

echo ""
echo "--- B4: ANTI-OVER-PIN — units that were already correct stay untouched ---"

_EXEC_SCCACHE="$(grep -E '^ExecStart=' "$GEN_UNITS/sccache.service" 2>/dev/null | head -1 || true)"

# sccache.service's ExecStart is ${sccache_bin} = $HOME/.cargo/bin/sccache —
# checkout-independent and therefore NOT part of this defect. "Fixing" it would
# be a real regression.
assert "B4a: sccache.service ExecStart still resolves under \$HOME/.cargo/bin" \
    test "$_EXEC_SCCACHE" = "ExecStart=$GEN_HOME/.cargo/bin/sccache"

echo ""
echo "--- B5: static anti-over-fix pins on the real scripts/setup-dev.sh ---"

SETUP_DEV="$REPO_ROOT/scripts/setup-dev.sh"

assert "B5a: scripts/setup-dev.sh exists" \
    test -f "$SETUP_DEV"

# Regression pin. Two-step filter (strip comment lines, then a literal search),
# the tests/infra/test_setup_dev_no_ldconfig.sh idiom: explanatory comments
# describing the old shape stay legal, active code cannot reintroduce it.
assert "B5b: no uncommented line still emits ExecStart=\${repo_dir}/scripts/jobserver-" \
    bash -c '! grep -Ev "^[[:space:]]*#" "$1" | grep -qF "ExecStart=\${repo_dir}/scripts/jobserver-"' _ "$SETUP_DEV"

# The other half of the contract: ONLY the host-global systemd units get
# pinned. Everything per-worktree — hooks, the debug port, .cargo config, the
# warm-lane FS — must stay relative to the INVOKING checkout, or setup-dev.sh
# silently provisions the wrong tree when run from a lane.
_assert_worktree_relative() {
    local script="$1"
    assert "B5c: $script is still invoked worktree-relative via \$(dirname \"\${BASH_SOURCE[0]}\")" \
        bash -c 'grep -Ev "^[[:space:]]*#" "$1" | grep -qF "\$(dirname \"\${BASH_SOURCE[0]}\")/$2"' \
            _ "$SETUP_DEV" "$script"
}
_assert_worktree_relative build-manifold-deps.sh
_assert_worktree_relative provision-warm-lane-fs.sh
_assert_worktree_relative install-warm-lane-units.sh
_assert_worktree_relative setup-main-gate-worktree-config.sh
_assert_worktree_relative setup-agent-cache-redirect.sh

# -- Summary ------------------------------------------------------------------
test_summary
