#!/usr/bin/env bash
# tests/infra/test_host_global_unit_pinning.sh
#
# Guards that HOST-GLOBAL systemd --user units generated by scripts/setup-dev.sh
# name a STABLE main-checkout path in their ExecStart, never the (possibly
# ephemeral) checkout that happened to invoke the installer.
#
# Background (task 5888): setup-dev.sh's install_build_services() writes four
# units into the host-global $HOME/.config/systemd/user, but derived their
# ExecStart from ${BASH_SOURCE[0]} — the INVOKING checkout.  Run once from a
# warm lane (/home/leo/src/warm-lanes/worktrees/_lane-N), the two jobserver
# units were pinned at a path that vanishes the moment that lane is reclaimed
# and re-seeded.  From then on every start fails with status=203/EXEC, the
# dual-pool cargo jobserver never comes up, and every verify silently
# fails-open to a private -j(nproc) — completely silently, because nothing
# Requires= those units.  Same defect class, same fix shape, as the prior art
# in scripts/setup-agent-cache-redirect.sh:498-507,549-560, and the same host
# convention already encoded on deploy/systemd/reify-warm-lane{,-gc}.service
# (#4720): a host-global unit names the stable main checkout.
#
# Part A — the RESOLVER contract (scripts/lib_main_checkout.sh).
# Part B — the GENERATOR contract (see the section banner further down).
#
# WHY PART A EXISTS SEPARATELY: `git rev-parse --git-common-dir` is RELATIVE
# inside the main checkout (`.git`, or `../../.git` from a subdir) and absolute
# only inside a linked worktree, so the obvious `dirname "$(git rev-parse
# --git-common-dir)"` yields `.` exactly where it must not.  These cases pin
# `--path-format=absolute` and the `git -C` anchoring that make it uniform.
#
# HERMETIC (`pool` bucket in run-all-classification.manifest): every fixture is
# a mktemp -d git repo.  Nothing here reads or writes the real
# ~/.config/systemd/user, runs systemctl, or touches a host FIFO.
#
# Auto-discovered by tests/infra/run_all.sh via the test_*.sh glob.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
LIB_MAIN_CHECKOUT="$REPO_ROOT/scripts/lib_main_checkout.sh"

[ -f "$SCRIPT_DIR/test_helpers.sh" ] || {
    echo "ERROR: test_helpers.sh not found at $SCRIPT_DIR/test_helpers.sh" >&2
    exit 1
}
# shellcheck source=tests/infra/test_helpers.sh
source "$SCRIPT_DIR/test_helpers.sh"

_TMPDIRS=()
cleanup() {
    local d
    for d in "${_TMPDIRS[@]:-}"; do
        [ -n "$d" ] && rm -rf "$d"
    done
}
trap cleanup EXIT

echo "=== host-global systemd unit ExecStart pinning ==="

# ---------------------------------------------------------------------------
# _mk_two_checkout_fixture <stem> — mints a temp MAIN checkout with a REAL
# linked worktree beside it and echoes "<root>|<main>|<lane>".
#
# A real `git worktree add` (not a simulated directory layout) is what makes
# this reproduce the bug rather than model it: the linked worktree is the only
# thing that makes --git-common-dir point somewhere other than the CWD's .git.
#
# Paths are canonicalized with `pwd -P` so they compare byte-for-byte against
# git's own absolute output.
# ---------------------------------------------------------------------------
_mk_two_checkout_fixture() {
    local stem="$1" root main lane
    root="$(mktemp -d "${TMPDIR:-/tmp}/${stem}-XXXXXX")" || return 1
    root="$(cd "$root" && pwd -P)" || return 1
    _TMPDIRS+=("$root")
    main="$root/main"
    lane="$root/lane"
    mkdir -p "$main/sub/deep" || return 1
    git init -q -b main "$main" || return 1
    git -C "$main" -c user.name=t -c user.email=t@example.invalid \
        -c commit.gpgsign=false commit -q --allow-empty -m init || return 1
    git -C "$main" worktree add -q --detach "$lane" >/dev/null 2>&1 || return 1
    mkdir -p "$lane/sub/deep" || return 1
    printf '%s|%s|%s\n' "$root" "$main" "$lane"
}

# ---------------------------------------------------------------------------
# _resolver_out <cwd> <anchor> [ENV=VAL ...] — stdout of
# `reify_main_checkout <anchor>` run in a FRESH bash, from <cwd>.
#
# A fresh bash per case (rather than sourcing once into this shell) is what
# makes the ambient-CWD and REIFY_MAIN_CHECKOUT cases genuinely independent:
# bash's rules for a `VAR=v func` prefix on a *function* are subtle, and a
# leaked CWD or a leaked override would silently make a later case vacuous.
# GIT_DIR/GIT_WORK_TREE are unset because either would defeat `git -C`
# anchoring, and REIFY_MAIN_CHECKOUT is unset unless the caller re-supplies it.
#
# A FAILED call reads back as the EMPTY string at every call site below, never
# as a placeholder: a non-empty sentinel would satisfy the `-n` guards in the
# negative assertions (A2e, A5a) and let them pass vacuously against a resolver
# that does not exist at all.
# ---------------------------------------------------------------------------
_resolver_out() {
    local cwd="$1" anchor="$2"
    shift 2
    (
        cd "$cwd" || exit 1
        env -u GIT_DIR -u GIT_WORK_TREE -u GIT_INDEX_FILE -u REIFY_MAIN_CHECKOUT "$@" \
            bash -c 'source "$1" || exit 1; reify_main_checkout "$2"' _ \
            "$LIB_MAIN_CHECKOUT" "$anchor"
    )
}

# =============================================================================
# PART A — the main-checkout RESOLVER contract
# =============================================================================
echo ""
echo "--- A0: scripts/lib_main_checkout.sh exists and is sourceable ---"

assert "scripts/lib_main_checkout.sh exists" \
    test -f "$LIB_MAIN_CHECKOUT"

assert "scripts/lib_main_checkout.sh parses (bash -n)" \
    bash -n "$LIB_MAIN_CHECKOUT"

assert "sourcing scripts/lib_main_checkout.sh defines reify_main_checkout" \
    bash -c 'source "$1" || exit 1; declare -F reify_main_checkout >/dev/null' _ "$LIB_MAIN_CHECKOUT"

echo ""
echo "--- A1: two-checkout fixture (real linked worktree) ---"

_FIX="$(_mk_two_checkout_fixture reify-mainck)"
FIX_ROOT="${_FIX%%|*}"
FIX_LANE="${_FIX##*|}"
FIX_MAIN="${_FIX#*|}"; FIX_MAIN="${FIX_MAIN%%|*}"
FIX_NOREPO="$FIX_ROOT/outside"
mkdir -p "$FIX_NOREPO"

# NON-VACUITY CONTROL, asserted BEFORE any resolver case: if these two paths
# were equal, every "resolves to the main checkout, not the lane" assertion
# below would pass no matter what the resolver did.
assert "fixture: the main checkout and the linked worktree are DISTINCT paths" \
    bash -c '[ "$1" != "$2" ]' _ "$FIX_MAIN" "$FIX_LANE"

assert "fixture: the linked worktree really is a linked worktree of the main checkout" \
    bash -c '[ "$(git -C "$2" rev-parse --path-format=absolute --git-common-dir)" = "$1/.git" ]' \
        _ "$FIX_MAIN" "$FIX_LANE"

# Precondition for the "outside any repo" case: $FIX_NOREPO must genuinely be
# outside every repository.  It normally is (TMPDIR is /tmp), but a TMPDIR
# nested inside a checkout would silently turn that case into a no-op, so the
# requirement is asserted rather than assumed.
assert "fixture: the non-repo scratch dir is genuinely outside any git repository" \
    bash -c '! git -C "$1" rev-parse --git-common-dir >/dev/null 2>&1' _ "$FIX_NOREPO"

echo ""
echo "--- A2: reify_main_checkout resolves the MAIN checkout from every anchor ---"

_R_MAIN="$(_resolver_out / "$FIX_MAIN")" || _R_MAIN=""
_R_MAIN_SUB="$(_resolver_out / "$FIX_MAIN/sub/deep")" || _R_MAIN_SUB=""
_R_LANE="$(_resolver_out / "$FIX_LANE")" || _R_LANE=""
_R_LANE_SUB="$(_resolver_out / "$FIX_LANE/sub/deep")" || _R_LANE_SUB=""

assert "A2a: anchored at the main checkout -> the main checkout root" \
    test "$_R_MAIN" = "$FIX_MAIN"

# Guards the --git-common-dir-is-RELATIVE-here trap: bare output is `.git` in
# the main checkout and `../../.git` from a subdir of it, so a resolver without
# --path-format=absolute answers `.` / `..` and is wrong precisely here.
assert "A2b: anchored at a SUBDIR of the main checkout -> the main checkout root" \
    test "$_R_MAIN_SUB" = "$FIX_MAIN"

assert "A2c: anchored at the LINKED WORKTREE -> the MAIN checkout root" \
    test "$_R_LANE" = "$FIX_MAIN"

assert "A2d: anchored at a SUBDIR of the linked worktree -> the MAIN checkout root" \
    test "$_R_LANE_SUB" = "$FIX_MAIN"

# THE BUG, stated directly: the whole defect is a host-global unit pinned at the
# linked worktree.  This is the assertion that would have caught it.
assert "A2e: the linked-worktree answer is NOT the linked worktree itself (the bug)" \
    bash -c '[ -n "$1" ] && [ "$1" != "$2" ]' _ "$_R_LANE" "$FIX_LANE"

echo ""
echo "--- A3: REIFY_MAIN_CHECKOUT override wins over the git derivation ---"

_R_OVERRIDE="$(_resolver_out / "$FIX_LANE" "REIFY_MAIN_CHECKOUT=$FIX_ROOT/override")" \
    || _R_OVERRIDE=""

assert "A3a: REIFY_MAIN_CHECKOUT set in the invocation env wins over git derivation" \
    test "$_R_OVERRIDE" = "$FIX_ROOT/override"

# ...and does not leak: the very next call, without it, must derive again.
assert "A3b: the override does not persist into a subsequent un-overridden call" \
    bash -c '[ "$1" = "$2" ]' _ "$(_resolver_out / "$FIX_LANE" || true)" "$FIX_MAIN"

echo ""
echo "--- A4: unresolvable anchors fail closed (non-zero, EMPTY stdout) ---"

_NOREPO_OUT=""; _NOREPO_RC=0
_NOREPO_OUT="$(_resolver_out / "$FIX_NOREPO" 2>/dev/null)" || _NOREPO_RC=$?

assert "A4a: anchored outside any git repo returns non-zero" \
    test "$_NOREPO_RC" -ne 0

# Never emit a guessed path: a bogus non-empty answer would be interpolated
# straight into an ExecStart and produce a silently dead unit.
assert "A4b: anchored outside any git repo prints NOTHING" \
    test -z "$_NOREPO_OUT"

_MISSING_OUT=""; _MISSING_RC=0
_MISSING_OUT="$(_resolver_out / "$FIX_ROOT/does-not-exist" 2>/dev/null)" || _MISSING_RC=$?

assert "A4c: anchored at a non-existent directory returns non-zero" \
    test "$_MISSING_RC" -ne 0

assert "A4d: anchored at a non-existent directory prints NOTHING" \
    test -z "$_MISSING_OUT"

echo ""
echo "--- A5: resolution does not depend on ambient CWD ---"

# `git rev-parse` resolves against CWD and setup-dev.sh has no top-level `cd`,
# so CWD is whatever the operator happened to be in.  Only a `git -C`-anchored
# resolver is deterministic.  Both answers must ALSO equal the main checkout,
# so two identical failures cannot pass this vacuously.
_R_CWD_SLASH="$(_resolver_out / "$FIX_LANE")" || _R_CWD_SLASH=""
_R_CWD_ROOT="$(_resolver_out "$FIX_ROOT" "$FIX_LANE")" || _R_CWD_ROOT=""

_CWD_INDEP=no
if [ -n "$_R_CWD_SLASH" ] && [ "$_R_CWD_SLASH" = "$_R_CWD_ROOT" ] && [ "$_R_CWD_SLASH" = "$FIX_MAIN" ]; then
    _CWD_INDEP=yes
fi

assert "A5a: same anchor from CWD=/ and CWD=<fixture root> -> same answer, == main checkout" \
    test "$_CWD_INDEP" = yes

# -- Summary ------------------------------------------------------------------
test_summary
