#!/usr/bin/env bash
# tests/infra/test_host_global_unit_pinning.sh
#
# Guards that HOST-GLOBAL systemd --user units generated by scripts/setup-dev.sh
# and scripts/setup-agent-cache-redirect.sh name a STABLE main-checkout path in
# their ExecStart, never the (possibly ephemeral) checkout that happened to
# invoke the installer.
#
# Background (task 5888): setup-dev.sh's install_build_services() writes four
# units into the host-global $HOME/.config/systemd/user.  Until the fix that
# lands WITH this suite, the two jobserver units derived their ExecStart from
# ${BASH_SOURCE[0]} — the INVOKING checkout.  Run once from a warm lane
# (/home/leo/src/warm-lanes/worktrees/_lane-N), those two units were pinned at
# a path that vanishes the moment that lane is reclaimed and re-seeded.  From
# then on every start fails with status=203/EXEC, the dual-pool cargo jobserver
# never comes up, and every verify silently fails-open to a private -j(nproc) —
# completely silently, because nothing Requires= those units.  The fix sources
# scripts/lib_main_checkout.sh from install_build_services() and interpolates
# the resolved main checkout into both ExecStarts (and the chmod that makes
# exactly those two executables runnable), leaving every per-worktree call site
# alone — which is what B5b/B5c pin.  Same defect class, same fix shape, as the
# prior art in scripts/setup-agent-cache-redirect.sh's install_boot_unit()
# (cited by FUNCTION rather than line range, so the reference cannot rot; that
# site was itself migrated onto this same resolver by task 6864 — Part C), and
# the same host convention already encoded on
# deploy/systemd/reify-warm-lane{,-gc}.service
# (#4720): a host-global unit names the stable main checkout.
#
# Part A — the RESOLVER contract (scripts/lib_main_checkout.sh).
# Part B — the GENERATOR contract (see the section banner further down).
# Part C — the BOOT-UNIT generator contract: the SECOND host-global generator,
#          scripts/setup-agent-cache-redirect.sh's install_boot_unit() (task
#          6864; see the section banner further down).
#
# WHY PART A EXISTS SEPARATELY: `git rev-parse --git-common-dir` is RELATIVE
# inside the main checkout (`.git`, or `../../.git` from a subdir) and absolute
# only inside a linked worktree, so the obvious `dirname "$(git rev-parse
# --git-common-dir)"` yields `.` exactly where it must not.  These cases pin
# `--path-format=absolute` and the `git -C` anchoring that make it uniform.
#
# HERMETIC (`pool` bucket in run-all-classification.manifest): every fixture is
# a mktemp -d git repo.  Nothing here reads or writes the real
# ~/.config/systemd/user, runs systemctl, or touches a host FIFO.
#
# Auto-discovered by tests/infra/run_all.sh via the test_*.sh glob.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
LIB_MAIN_CHECKOUT="$REPO_ROOT/scripts/lib_main_checkout.sh"

[ -f "$SCRIPT_DIR/test_helpers.sh" ] || {
    echo "ERROR: test_helpers.sh not found at $SCRIPT_DIR/test_helpers.sh" >&2
    exit 1
}
# shellcheck source=tests/infra/test_helpers.sh
source "$SCRIPT_DIR/test_helpers.sh"

_TMPDIRS=()
cleanup() {
    local d
    for d in "${_TMPDIRS[@]:-}"; do
        [ -n "$d" ] && rm -rf "$d"
    done
    # MANDATORY. This runs from the EXIT trap, so its return value BECOMES the
    # suite's exit status: with an empty _TMPDIRS the loop's last command is a
    # false `[ -n "" ]`, and the suite would exit 1 with every assertion green.
    return 0
}
trap cleanup EXIT

echo "=== host-global systemd unit ExecStart pinning ==="

# ---------------------------------------------------------------------------
# _fixture_git <git args...> — git for FIXTURE CONSTRUCTION ONLY, with the
# ambient repository environment stripped.
#
# reify runs its whole verify gate from hooks/pre-merge-commit, and git EXPORTS
# GIT_DIR (and friends) into every hook.  An inherited GIT_DIR outranks `git -C`
# — measured — so the `git init` / `worktree add` calls below would operate on
# the REAL repository instead of the mktemp fixture.  Same precedent as
# tests/infra/test_spec_anchor_lint.sh:1182.
#
# The asymmetry with _resolver_out below is DELIBERATE: fixture construction
# sanitizes, the code under test does not get sanitized FOR it.  The resolver
# has to survive a hostile ambient environment on its own — that is what A6
# asserts, and a harness that pre-cleaned the environment would be certifying a
# posture production never actually has.
# ---------------------------------------------------------------------------
_fixture_git() {
    env -u GIT_DIR -u GIT_WORK_TREE -u GIT_COMMON_DIR -u GIT_INDEX_FILE git "$@"
}

# ---------------------------------------------------------------------------
# SHARED GENERATOR-FIXTURE SCAFFOLDING (Parts B and C).
#
# The two generator fixtures below are NOT merged into one: they commit
# different executables, strip different exec bits, and extract a different
# function out of a different script, and their mode sets do not overlap.  What
# IS identical is the mechanical scaffolding — the mktemp root, the recording
# systemctl shim, the initial commit — and those live here rather than being
# written twice, so a fix to any of them (a new variable in _fixture_git's strip
# set, a shim that records exit codes) cannot land for one Part's harness and
# silently leave the other on the old posture.
# ---------------------------------------------------------------------------

# _mk_fixture_root <stem> — MAIN-SHELL ONLY, and transitively so is every caller.
# Mints a canonicalized mktemp root, registers it in _TMPDIRS for the EXIT trap,
# and sets _FIXTURE_ROOT.  It sets a global rather than echoing because an
# append performed inside a command-substitution SUBSHELL is silently discarded,
# leaking the whole fixture tree — see _mk_two_checkout_fixture's banner.
#
# `pwd -P` canonicalizes so fixture paths compare byte-for-byte against git's
# own absolute output (macOS /tmp -> /private/tmp, and any symlinked TMPDIR).
_FIXTURE_ROOT=""
_mk_fixture_root() {
    local stem="$1" root
    root="$(mktemp -d "${TMPDIR:-/tmp}/${stem}-XXXXXX")" || return 1
    root="$(cd "$root" && pwd -P)" || return 1
    _TMPDIRS+=("$root")
    _FIXTURE_ROOT="$root"
}

# _write_systemctl_shim <bindir> <logfile> — a `systemctl` placed earlier on PATH
# than the real one, RECORDING its argv to <logfile> and exiting 0.  Neither
# generator's daemon-reload / `enable --now` may reach the host.
#
# Recording rather than merely no-op is load-bearing: both generators write
# their unit files well before their reload/enable tail, so unit PRESENCE cannot
# distinguish "installed" from "aborted two lines later".  Only the log can, and
# B9c and C4 depend on exactly that distinction.
_write_systemctl_shim() {
    local bindir="$1" log="$2"
    mkdir -p "$bindir" || return 1
    printf '#!/usr/bin/env bash\nprintf "%%s\\n" "$*" >> %s\nexit 0\n' "$log" \
        > "$bindir/systemctl" || return 1
    chmod +x "$bindir/systemctl" || return 1
}

# _fixture_init_commit <dir> — `git init -b main` + `add -A` + an initial commit
# that is independent of the developer's identity and signing config.  Routed
# through _fixture_git so an ambient GIT_DIR cannot redirect it at the REAL
# repository (see that function's banner).
#
# Committing before the caller's `git worktree add` is what makes a linked lane
# check out its own separate, mode-755 inodes — the asymmetry every noexec mode
# below depends on.
_fixture_init_commit() {
    local dir="$1"
    _fixture_git init -q -b main "$dir" || return 1
    _fixture_git -C "$dir" add -A || return 1
    _fixture_git -C "$dir" -c user.name=t -c user.email=t@example.invalid \
        -c commit.gpgsign=false commit -q -m init || return 1
}

# ---------------------------------------------------------------------------
# _mk_two_checkout_fixture <stem> — MAIN-SHELL ONLY. Mints a temp MAIN checkout
# with a REAL linked worktree beside it, and sets FIX_ROOT / FIX_MAIN /
# FIX_LANE.
#
# MUST NOT be called from a command substitution. It registers its mktemp root
# in _TMPDIRS for the EXIT trap, and an append performed inside a
# command-substitution SUBSHELL is silently discarded when that subshell exits
# — leaking the whole fixture tree (git repo + linked worktree) on every run.
# That is why this sets globals instead of echoing them, the same subshell trap
# test_helpers.sh's make_isolated_lane documents.
#
# A real `git worktree add` (not a simulated directory layout) is what makes
# this reproduce the bug rather than model it: the linked worktree is the only
# thing that makes --git-common-dir point somewhere other than the CWD's .git.
#
# Paths are canonicalized with `pwd -P` so they compare byte-for-byte against
# git's own absolute output.
# ---------------------------------------------------------------------------
_mk_two_checkout_fixture() {
    local stem="$1" root
    root="$(mktemp -d "${TMPDIR:-/tmp}/${stem}-XXXXXX")" || return 1
    root="$(cd "$root" && pwd -P)" || return 1
    _TMPDIRS+=("$root")
    FIX_ROOT="$root"
    FIX_MAIN="$root/main"
    FIX_LANE="$root/lane"
    # A third, entirely UNRELATED repository. Only used as the poison target for
    # A6: it is what an un-neutralized resolver answers when GIT_DIR (or
    # GIT_COMMON_DIR) is exported into the environment, which is what makes that
    # section non-vacuous.
    FIX_OTHER="$root/other"
    mkdir -p "$FIX_MAIN/sub/deep" || return 1
    _fixture_git init -q -b main "$FIX_MAIN" || return 1
    _fixture_git -C "$FIX_MAIN" -c user.name=t -c user.email=t@example.invalid \
        -c commit.gpgsign=false commit -q --allow-empty -m init || return 1
    _fixture_git -C "$FIX_MAIN" worktree add -q --detach "$FIX_LANE" >/dev/null 2>&1 || return 1
    mkdir -p "$FIX_LANE/sub/deep" || return 1
    _fixture_git init -q -b main "$FIX_OTHER" || return 1
    _fixture_git -C "$FIX_OTHER" -c user.name=t -c user.email=t@example.invalid \
        -c commit.gpgsign=false commit -q --allow-empty -m init || return 1
    return 0
}

# ---------------------------------------------------------------------------
# _resolver_out <cwd> <anchor> [ENV=VAL ...] — stdout of
# `reify_main_checkout <anchor>` run in a FRESH bash, from <cwd>.
#
# A fresh bash per case (rather than sourcing once into this shell) is what
# makes the ambient-CWD and REIFY_MAIN_CHECKOUT cases genuinely independent:
# bash's rules for a `VAR=v func` prefix on a *function* are subtle, and a
# leaked CWD or a leaked override would silently make a later case vacuous.
#
# ONLY REIFY_MAIN_CHECKOUT is scrubbed here — it is the override UNDER TEST, so
# an ambient one would make A2/A5 pass without the git derivation running at
# all.  The git repository environment (GIT_DIR, GIT_WORK_TREE, GIT_COMMON_DIR,
# GIT_INDEX_FILE) is deliberately NOT scrubbed: those are exactly the variables
# that outrank `git -C`, the resolver is responsible for neutralizing them
# itself, and a harness that pre-cleaned them would leave that responsibility
# permanently untested.  A6 poisons them on purpose.
#
# A FAILED call reads back as the EMPTY string at every call site below, never
# as a placeholder: a non-empty sentinel would satisfy the `-n` guards in the
# negative assertions (A2e, A5a) and let them pass vacuously against a resolver
# that does not exist at all.
# ---------------------------------------------------------------------------
_resolver_out() {
    local cwd="$1" anchor="$2"
    shift 2
    (
        cd "$cwd" || exit 1
        env -u REIFY_MAIN_CHECKOUT "$@" \
            bash -c 'source "$1" || exit 1; reify_main_checkout "$2"' _ \
            "$LIB_MAIN_CHECKOUT" "$anchor"
    )
}

# =============================================================================
# PART A — the main-checkout RESOLVER contract
# =============================================================================
echo ""
echo "--- A0: scripts/lib_main_checkout.sh exists and is sourceable ---"

assert "scripts/lib_main_checkout.sh exists" \
    test -f "$LIB_MAIN_CHECKOUT"

assert "scripts/lib_main_checkout.sh parses (bash -n)" \
    bash -n "$LIB_MAIN_CHECKOUT"

assert "sourcing scripts/lib_main_checkout.sh defines reify_main_checkout" \
    bash -c 'source "$1" || exit 1; declare -F reify_main_checkout >/dev/null' _ "$LIB_MAIN_CHECKOUT"

echo ""
echo "--- A1: two-checkout fixture (real linked worktree) ---"

FIX_ROOT=""; FIX_MAIN=""; FIX_LANE=""; FIX_OTHER=""
_mk_two_checkout_fixture reify-mainck   # main shell, NOT $( ) — see the header
FIX_NOREPO="$FIX_ROOT/outside"
mkdir -p "$FIX_NOREPO"

# The fixture's own registration is what the EXIT trap reclaims; assert it
# happened rather than trusting it, so a future refactor that reintroduces the
# command-substitution form fails here instead of leaking a git repo per run.
assert "fixture: the mktemp root is registered in _TMPDIRS for the EXIT trap" \
    bash -c '[ "$1" = "$2" ] && [ -n "$2" ]' _ "${_TMPDIRS[0]:-}" "$FIX_ROOT"

# NON-VACUITY CONTROL, asserted BEFORE any resolver case: if these two paths
# were equal, every "resolves to the main checkout, not the lane" assertion
# below would pass no matter what the resolver did.
assert "fixture: the main checkout and the linked worktree are DISTINCT paths" \
    bash -c '[ "$1" != "$2" ]' _ "$FIX_MAIN" "$FIX_LANE"

assert "fixture: the linked worktree really is a linked worktree of the main checkout" \
    bash -c '[ "$(env -u GIT_DIR -u GIT_WORK_TREE -u GIT_COMMON_DIR -u GIT_INDEX_FILE \
        git -C "$2" rev-parse --path-format=absolute --git-common-dir)" = "$1/.git" ]' \
        _ "$FIX_MAIN" "$FIX_LANE"

# Precondition for the "outside any repo" case: $FIX_NOREPO must genuinely be
# outside every repository.  It normally is (TMPDIR is /tmp), but a TMPDIR
# nested inside a checkout would silently turn that case into a no-op, so the
# requirement is asserted rather than assumed.
assert "fixture: the non-repo scratch dir is genuinely outside any git repository" \
    bash -c '! env -u GIT_DIR -u GIT_WORK_TREE -u GIT_COMMON_DIR -u GIT_INDEX_FILE \
        git -C "$1" rev-parse --git-common-dir >/dev/null 2>&1' _ "$FIX_NOREPO"

echo ""
echo "--- A2: reify_main_checkout resolves the MAIN checkout from every anchor ---"

_R_MAIN="$(_resolver_out / "$FIX_MAIN")" || _R_MAIN=""
_R_MAIN_SUB="$(_resolver_out / "$FIX_MAIN/sub/deep")" || _R_MAIN_SUB=""
_R_LANE="$(_resolver_out / "$FIX_LANE")" || _R_LANE=""
_R_LANE_SUB="$(_resolver_out / "$FIX_LANE/sub/deep")" || _R_LANE_SUB=""

assert "A2a: anchored at the main checkout -> the main checkout root" \
    test "$_R_MAIN" = "$FIX_MAIN"

# Guards the --git-common-dir-is-RELATIVE-here trap: bare output is `.git` in
# the main checkout and `../../.git` from a subdir of it, so a resolver without
# --path-format=absolute answers `.` / `..` and is wrong precisely here.
assert "A2b: anchored at a SUBDIR of the main checkout -> the main checkout root" \
    test "$_R_MAIN_SUB" = "$FIX_MAIN"

assert "A2c: anchored at the LINKED WORKTREE -> the MAIN checkout root" \
    test "$_R_LANE" = "$FIX_MAIN"

assert "A2d: anchored at a SUBDIR of the linked worktree -> the MAIN checkout root" \
    test "$_R_LANE_SUB" = "$FIX_MAIN"

# THE BUG, stated directly: the whole defect is a host-global unit pinned at the
# linked worktree.  This is the assertion that would have caught it.
assert "A2e: the linked-worktree answer is NOT the linked worktree itself (the bug)" \
    bash -c '[ -n "$1" ] && [ "$1" != "$2" ]' _ "$_R_LANE" "$FIX_LANE"

echo ""
echo "--- A3: REIFY_MAIN_CHECKOUT override wins over the git derivation ---"

_R_OVERRIDE="$(_resolver_out / "$FIX_LANE" "REIFY_MAIN_CHECKOUT=$FIX_ROOT/override")" \
    || _R_OVERRIDE=""

assert "A3a: REIFY_MAIN_CHECKOUT set in the invocation env wins over git derivation" \
    test "$_R_OVERRIDE" = "$FIX_ROOT/override"

# ...and does not leak: the very next call, without it, must derive again.
assert "A3b: the override does not persist into a subsequent un-overridden call" \
    bash -c '[ "$1" = "$2" ]' _ "$(_resolver_out / "$FIX_LANE" || true)" "$FIX_MAIN"

echo ""
echo "--- A4: unresolvable anchors fail closed (non-zero, EMPTY stdout) ---"

_NOREPO_OUT=""; _NOREPO_RC=0
_NOREPO_OUT="$(_resolver_out / "$FIX_NOREPO" 2>/dev/null)" || _NOREPO_RC=$?

assert "A4a: anchored outside any git repo returns non-zero" \
    test "$_NOREPO_RC" -ne 0

# Never emit a guessed path: a bogus non-empty answer would be interpolated
# straight into an ExecStart and produce a silently dead unit.
assert "A4b: anchored outside any git repo prints NOTHING" \
    test -z "$_NOREPO_OUT"

_MISSING_OUT=""; _MISSING_RC=0
_MISSING_OUT="$(_resolver_out / "$FIX_ROOT/does-not-exist" 2>/dev/null)" || _MISSING_RC=$?

assert "A4c: anchored at a non-existent directory returns non-zero" \
    test "$_MISSING_RC" -ne 0

assert "A4d: anchored at a non-existent directory prints NOTHING" \
    test -z "$_MISSING_OUT"

echo ""
echo "--- A5: resolution does not depend on ambient CWD ---"

# `git rev-parse` resolves against CWD and setup-dev.sh has no top-level `cd`,
# so CWD is whatever the operator happened to be in.  Only a `git -C`-anchored
# resolver is deterministic.  Both answers must ALSO equal the main checkout,
# so two identical failures cannot pass this vacuously.
_R_CWD_SLASH="$(_resolver_out / "$FIX_LANE")" || _R_CWD_SLASH=""
_R_CWD_ROOT="$(_resolver_out "$FIX_ROOT" "$FIX_LANE")" || _R_CWD_ROOT=""

_CWD_INDEP=no
if [ -n "$_R_CWD_SLASH" ] && [ "$_R_CWD_SLASH" = "$_R_CWD_ROOT" ] && [ "$_R_CWD_SLASH" = "$FIX_MAIN" ]; then
    _CWD_INDEP=yes
fi

assert "A5a: same anchor from CWD=/ and CWD=<fixture root> -> same answer, == main checkout" \
    test "$_CWD_INDEP" = yes

echo ""
echo "--- A6: a hostile ambient git environment does not redirect the answer ---"

# GIT_DIR, GIT_WORK_TREE and GIT_COMMON_DIR all OUTRANK `git -C`, so without
# explicit neutralization inside the resolver, the `git -C "$anchor"` anchoring
# that A2/A5 pin is decorative: the answer comes from whatever repository the
# environment names.  This is not a contrived environment — git EXPORTS GIT_DIR
# into every hook, and reify runs its entire verify gate from
# hooks/pre-merge-commit, so this is the posture the resolver most often runs in.
#
# The poison target is $FIX_OTHER, an UNRELATED repo, precisely so the assertions
# below cannot pass vacuously: pointing the poison at the lane's own git dir
# would resolve back to $FIX_MAIN anyway and prove nothing.
_POISON_RAW=""
_POISON_RAW="$(GIT_DIR="$FIX_OTHER/.git" GIT_WORK_TREE="$FIX_OTHER" \
    git -C "$FIX_LANE" rev-parse --path-format=absolute --git-common-dir 2>/dev/null)" \
    || _POISON_RAW=""

# CONTROL, asserted FIRST: prove the poison actually works on a raw `git -C`.
# If a future git release stopped honouring these variables (or they were simply
# misspelled here), every assertion below would pass while testing nothing.
assert "A6a: CONTROL — poisoned env really does redirect a raw \`git -C\` to the other repo" \
    bash -c '[ -n "$1" ] && [ "$1" = "$2/.git" ] && [ "$2" != "$3" ]' \
        _ "$_POISON_RAW" "$FIX_OTHER" "$FIX_MAIN"

_R_POISON_DIR="$(_resolver_out / "$FIX_LANE" \
    "GIT_DIR=$FIX_OTHER/.git" "GIT_WORK_TREE=$FIX_OTHER")" || _R_POISON_DIR=""

assert "A6b: GIT_DIR+GIT_WORK_TREE exported, anchored at the lane -> still the MAIN checkout" \
    test "$_R_POISON_DIR" = "$FIX_MAIN"

# GIT_COMMON_DIR is the third override and the one most easily missed: it
# redirects --git-common-dir specifically, which is the exact query this
# resolver is built on.
_R_POISON_COMMON="$(_resolver_out / "$FIX_LANE" "GIT_COMMON_DIR=$FIX_OTHER/.git")" \
    || _R_POISON_COMMON=""

assert "A6c: GIT_COMMON_DIR exported, anchored at the lane -> still the MAIN checkout" \
    test "$_R_POISON_COMMON" = "$FIX_MAIN"

# The hook shape: setup-dev.sh (or a consumer) invoked from inside the MAIN
# checkout while git has exported a GIT_DIR for some other repository.
_R_POISON_MAIN="$(_resolver_out / "$FIX_MAIN" \
    "GIT_DIR=$FIX_OTHER/.git" "GIT_WORK_TREE=$FIX_OTHER")" || _R_POISON_MAIN=""

assert "A6d: GIT_DIR exported, anchored at the MAIN checkout -> still the MAIN checkout" \
    test "$_R_POISON_MAIN" = "$FIX_MAIN"

# =============================================================================
# PART B — the GENERATOR contract (setup-dev.sh install_build_services)
#
# Asserts on what the installer actually WRITES, in a sandboxed HOME. It does
# NOT inspect the real ~/.config/systemd/user: the live units were already
# hand-repointed by operator action on 2026-08-15, so any check against them
# would pass vacuously and prove nothing about the generator — which is the
# whole remaining value here. Nothing below runs systemctl (a restart of
# reify-jobserver.service re-seeds both FIFO pools and every in-flight verify
# rustc holding a token loses it permanently, fleet-wide), touches a host FIFO,
# or writes outside its mktemp root.
#
# CONTAINMENT IS BY CONSTRUCTION, not by assertion: _run_generator overrides
# HOME to the fixture's, and $unit_dir is derived from $HOME inside
# install_build_services(), so the real ~/.config/systemd/user is unreachable
# from here. There is deliberately no assertion for it — an assertion could only
# re-measure the override it already depends on.
# =============================================================================
echo ""
echo "--- B0: generator fixture (function extracted into a FAKE LANE) ---"

# ---------------------------------------------------------------------------
# _mk_generator_fixture <stem> [MODE] — MAIN-SHELL ONLY (see
# _mk_two_checkout_fixture for why this sets globals rather than echoing them).
# Sets GEN_ROOT/GEN_MAIN/GEN_LANE/GEN_HOME/GEN_UNITS/GEN_SYSTEMCTL_LOG.
#
# MODE selects which branch of the installer's pin decision the fixture drives:
#   main-exec    (default) the main checkout resolves AND holds both executables
#                -> the PIN is taken, units name the main checkout. B1-B4.
#   main-noexec  the main checkout resolves but its two scripts are NOT
#                executable -> the FALLBACK is taken, units name the invoking
#                lane and the installer warns. B6.
#   lane-norepo  the invoking tree is not a git worktree at all, so the resolver
#                fails outright -> the FALLBACK is taken with an EMPTY
#                main_checkout, exercising the `<unresolved>` message. B7.
#   main-only    the invoking tree IS the main checkout, and its scripts are not
#                executable -> main_checkout == repo_dir, the case an
#                `!= "$repo_dir"`-gated warn would swallow. B8.
#   fallback-noscripts
#                the fallback is taken at a tree that does not hold the scripts
#                at all, so the trailing `chmod +x` fails -> exercises the
#                non-fatal chmod guard. B9.
#
# The fallback branch matters disproportionately: it is the one whose guard,
# if it were ever inverted or dropped, silently re-creates the original 203/EXEC
# defect. Covering only main-exec would leave it green under exactly that edit.
#
# The executable stubs and a copy of lib_main_checkout.sh are COMMITTED before
# `git worktree add`, so the linked worktree carries them too — the installer
# must be able to find its executables in whichever tree it ends up pinning,
# or a passing test could not distinguish "pinned correctly" from "chmod
# happened to fail".
#
# install_build_services() is extracted by column-0 sed anchors and written to
# <fake lane>/scripts/setup-dev.sh, so ${BASH_SOURCE[0]} inside the function
# resolves to the FAKE LANE. That is what reproduces the bug's exact trigger
# condition — an installer invoked from a warm lane — rather than simulating
# it. setup-dev.sh cannot simply be sourced: it is straight-line and would
# apt-install, curl rustup and build native deps long before reaching the
# function.
# ---------------------------------------------------------------------------
_mk_generator_fixture() {
    local stem="$1" mode="${2:-main-exec}" root
    _mk_fixture_root "$stem" || return 1
    root="$_FIXTURE_ROOT"
    GEN_ROOT="$root"
    GEN_MAIN="$root/main"
    GEN_LANE="$root/lane"
    GEN_HOME="$root/home"
    GEN_UNITS="$GEN_HOME/.config/systemd/user"

    mkdir -p "$GEN_MAIN/scripts" "$GEN_HOME/.cargo/bin" "$root/shim" || return 1

    # The recording `systemctl` (see _write_systemctl_shim). B9c is the case
    # that needs the recording rather than a bare no-op.
    GEN_SYSTEMCTL_LOG="$root/systemctl.log"
    _write_systemctl_shim "$root/shim" "$GEN_SYSTEMCTL_LOG" || return 1

    # The two executables the jobserver units name in their ExecStart, plus the
    # resolver the installer sources.
    printf '#!/usr/bin/env bash\nexit 0\n' > "$GEN_MAIN/scripts/jobserver-balancer.py" || return 1
    printf '#!/usr/bin/env bash\nexit 0\n' > "$GEN_MAIN/scripts/jobserver-canary.sh" || return 1
    cp "$REPO_ROOT/scripts/lib_main_checkout.sh" "$GEN_MAIN/scripts/lib_main_checkout.sh" || return 1
    chmod +x "$GEN_MAIN/scripts/jobserver-balancer.py" "$GEN_MAIN/scripts/jobserver-canary.sh" || return 1

    _fixture_init_commit "$GEN_MAIN" || return 1

    if [ "$mode" = main-only ]; then
        # No linked worktree at all: the invoking tree IS the main checkout, so
        # repo_dir and main_checkout resolve to the same path.
        GEN_LANE="$GEN_MAIN"
    elif [ "$mode" = lane-norepo ]; then
        # A plain directory, NOT a worktree: `git worktree add` is skipped
        # entirely so reify_main_checkout() fails outright from this anchor.
        # It still carries the scripts and the resolver, so the ONLY thing being
        # exercised is the unresolvable-anchor branch.
        mkdir -p "$GEN_LANE/scripts" || return 1
        cp "$GEN_MAIN/scripts/jobserver-balancer.py" \
           "$GEN_MAIN/scripts/jobserver-canary.sh" \
           "$GEN_MAIN/scripts/lib_main_checkout.sh" "$GEN_LANE/scripts/" || return 1
    else
        _fixture_git -C "$GEN_MAIN" worktree add -q --detach "$GEN_LANE" >/dev/null 2>&1 || return 1
        mkdir -p "$GEN_LANE/scripts" || return 1
    fi

    if [ "$mode" = main-noexec ] || [ "$mode" = main-only ] \
        || [ "$mode" = fallback-noscripts ]; then
        # Strip the exec bit in the MAIN checkout ONLY, and only AFTER the
        # worktree add: the lane's copies are separate inodes checked out at the
        # committed mode 755, so they stay runnable. That asymmetry is exactly
        # the shape the fallback exists for — the main checkout resolves, but
        # cannot run what the units would name.
        chmod -x "$GEN_MAIN/scripts/jobserver-balancer.py" \
                 "$GEN_MAIN/scripts/jobserver-canary.sh" || return 1
    fi

    if [ "$mode" = fallback-noscripts ]; then
        # ...and the tree the fallback lands on does not hold them AT ALL, so
        # the installer's trailing `chmod +x` fails with ENOENT. A portable
        # stand-in for the real-world failures (EPERM on a main checkout owned
        # by another uid, EROFS on a read-only mount) that a hermetic test
        # cannot manufacture.
        rm -f "$GEN_LANE/scripts/jobserver-balancer.py" \
              "$GEN_LANE/scripts/jobserver-canary.sh" || return 1
    fi

    sed -n '/^install_build_services() {$/,/^}$/p' "$REPO_ROOT/scripts/setup-dev.sh" \
        > "$GEN_LANE/scripts/setup-dev.sh" || return 1
    return 0
}

# ---------------------------------------------------------------------------
# _run_generator — source the extracted function in a sandboxed environment and
# invoke it. HOME is the fixture's, PATH is shimmed, and the log helpers
# setup-dev.sh defines at top level (which the extraction deliberately does not
# carry) are stubbed. warn/err are echoed to stderr so a fallback taken during
# the run is visible in the captured-output dump of a failing assert.
# ---------------------------------------------------------------------------
_run_generator() {
    env -u REIFY_MAIN_CHECKOUT -u REIFY_SCCACHE_SIZE \
        HOME="$GEN_HOME" PATH="$GEN_ROOT/shim:$PATH" \
        bash -c '
            set -euo pipefail
            info() { :; }
            ok()   { :; }
            warn() { echo "warn: $*" >&2; }
            err()  { echo "err: $*" >&2; }
            source "$1"
            install_build_services
        ' _ "$GEN_LANE/scripts/setup-dev.sh"
}

# ---------------------------------------------------------------------------
# _exec_lines <unit_dir> — every `Exec*=` line across every emitted *.service,
# as "<unit basename>|<argv0>".
#
# argv[0] ONLY — the first whitespace-separated token, with systemd's `-@+!:`
# run-time prefix characters stripped. A worktree path passed as a DATA
# ARGUMENT is legitimate (deploy/systemd/reify-warm-lane-gc.service correctly
# carries `--mount /home/leo/src/warm-lanes/worktrees`), so a naive grep for
# the lane path over whole unit files would over-match and make this guard
# untrustworthy. Only the EXECUTABLE is the defect.
# ---------------------------------------------------------------------------
_exec_lines() {
    local unit_dir="$1" f line val
    for f in "$unit_dir"/*.service; do
        [ -f "$f" ] || continue
        while IFS= read -r line || [ -n "$line" ]; do
            case "$line" in
                Exec*=*) ;;
                *) continue ;;
            esac
            val="${line#*=}"
            while [ -n "$val" ]; do
                case "$val" in
                    [-@+!:]*) val="${val#?}" ;;
                    *) break ;;
                esac
            done
            printf '%s|%s\n' "${f##*/}" "${val%%[[:space:]]*}"
        done < "$f"
    done
}

GEN_ROOT=""; GEN_MAIN=""; GEN_LANE=""; GEN_HOME=""; GEN_UNITS=""; GEN_SYSTEMCTL_LOG=""
_mk_generator_fixture reify-genfix   # main shell, NOT $( )

# NON-VACUITY GUARDS on the extraction, asserted BEFORE the run. A future
# refactor of setup-dev.sh must fail this suite loudly rather than silently
# test an empty snippet.
_EXTRACT="$GEN_LANE/scripts/setup-dev.sh"

assert "B0a: the extracted snippet is non-empty" \
    test -s "$_EXTRACT"

assert "B0b: the extracted snippet defines install_build_services" \
    grep -qF 'install_build_services() {' "$_EXTRACT"

assert "B0c: the extracted snippet carries the balancer ExecStart" \
    bash -c 'grep -E "^ExecStart=.*jobserver-balancer\.py" "$1" >/dev/null' _ "$_EXTRACT"

assert "B0d: the extracted snippet carries the canary ExecStart" \
    bash -c 'grep -E "^ExecStart=.*jobserver-canary\.sh" "$1" >/dev/null' _ "$_EXTRACT"

# The bug's trigger condition: the installer is running from a DIFFERENT tree
# than the one its host-global units must name.
assert "B0e: the fake lane and the main checkout are DISTINCT paths" \
    bash -c '[ "$1" != "$2" ]' _ "$GEN_LANE" "$GEN_MAIN"

echo ""
echo "--- B1: install_build_services() emits units into the sandboxed HOME ---"

_GEN_RC=0
_GEN_ERR="$GEN_ROOT/generator.err"
_run_generator >"$GEN_ROOT/generator.out" 2>"$_GEN_ERR" || _GEN_RC=$?

assert "B1a: install_build_services() completes successfully in the sandbox" \
    bash -c '[ "$1" = "0" ] || { cat "$2" >&2; exit 1; }' _ "$_GEN_RC" "$_GEN_ERR"

assert "B1b: it wrote reify-jobserver.service into the sandboxed unit dir" \
    test -f "$GEN_UNITS/reify-jobserver.service"

assert "B1c: it wrote reify-jobserver-canary.service into the sandboxed unit dir" \
    test -f "$GEN_UNITS/reify-jobserver-canary.service"

# What this actually measures is the unit COUNT: three .service files (sccache,
# jobserver, jobserver-canary) landed in the sandboxed unit dir. Named for that,
# not for containment — see the section banner for why containment carries no
# assertion.
assert "B1d: all three .service units were emitted into the sandboxed unit dir" \
    bash -c '[ "$(ls -1 "$1"/*.service 2>/dev/null | wc -l)" -ge 3 ]' _ "$GEN_UNITS"

echo ""
echo "--- B2: both jobserver ExecStarts name the MAIN checkout ---"

_EXEC_BALANCER="$(grep -E '^ExecStart=' "$GEN_UNITS/reify-jobserver.service" 2>/dev/null | head -1 || true)"
_EXEC_CANARY="$(grep -E '^ExecStart=' "$GEN_UNITS/reify-jobserver-canary.service" 2>/dev/null | head -1 || true)"

assert "B2a: reify-jobserver.service ExecStart == <main checkout>/scripts/jobserver-balancer.py" \
    test "$_EXEC_BALANCER" = "ExecStart=$GEN_MAIN/scripts/jobserver-balancer.py"

# Asserted SEPARATELY from the balancer on purpose: there are TWO defective
# ExecStart sites, and a fix that catches only the first leaves the leak canary
# permanently dead — which is exactly how the depletion self-heal stayed dead
# through the 2026-08-13 incident.
assert "B2b: reify-jobserver-canary.service ExecStart == <main checkout>/scripts/jobserver-canary.sh" \
    test "$_EXEC_CANARY" = "ExecStart=$GEN_MAIN/scripts/jobserver-canary.sh"

echo ""
echo "--- B3: no emitted unit EXECUTES anything under the invoking lane ---"

_EXEC_ALL="$GEN_ROOT/exec-lines.txt"
_exec_lines "$GEN_UNITS" > "$_EXEC_ALL"
_EXEC_COUNT="$(grep -c . "$_EXEC_ALL" || true)"

# Non-vacuity: the sweep must have actually examined something. The four units
# carry six Exec* lines today (sccache Pre+Start, jobserver Pre+Start+StopPost,
# canary Start); a lower bound of 3 leaves room for churn without letting an
# empty sweep report all-clear.
assert "B3a: the argv0 sweep examined at least 3 Exec* lines (non-vacuity)" \
    test "$_EXEC_COUNT" -ge 3

# Catches a future FIFTH host-global unit on arrival, not just the two known
# ones.
assert "B3b: no Exec* argv[0] in any emitted unit lives under the invoking lane" \
    bash -c '! cut -d"|" -f2 "$1" | grep -qF "$2/"' _ "$_EXEC_ALL" "$GEN_LANE"

echo ""
echo "--- B4: ANTI-OVER-PIN — units that were already correct stay untouched ---"

_EXEC_SCCACHE="$(grep -E '^ExecStart=' "$GEN_UNITS/sccache.service" 2>/dev/null | head -1 || true)"

# sccache.service's ExecStart is ${sccache_bin} = $HOME/.cargo/bin/sccache —
# checkout-independent and therefore NOT part of this defect. "Fixing" it would
# be a real regression.
assert "B4a: sccache.service ExecStart still resolves under \$HOME/.cargo/bin" \
    test "$_EXEC_SCCACHE" = "ExecStart=$GEN_HOME/.cargo/bin/sccache"

echo ""
echo "--- B5: static anti-over-fix pins on the real scripts/setup-dev.sh ---"

SETUP_DEV="$REPO_ROOT/scripts/setup-dev.sh"

assert "B5a: scripts/setup-dev.sh exists" \
    test -f "$SETUP_DEV"

# Regression pin. Two-step filter (strip comment lines, then a literal search),
# the tests/infra/test_setup_dev_no_ldconfig.sh idiom: explanatory comments
# describing the old shape stay legal, active code cannot reintroduce it.
assert "B5b: no uncommented line still emits ExecStart=\${repo_dir}/scripts/jobserver-" \
    bash -c '! grep -Ev "^[[:space:]]*#" "$1" | grep -qF "ExecStart=\${repo_dir}/scripts/jobserver-"' _ "$SETUP_DEV"

# The other half of the contract: ONLY the host-global systemd units get
# pinned. Everything per-worktree — hooks, the debug port, .cargo config, the
# warm-lane FS — must stay relative to the INVOKING checkout, or setup-dev.sh
# silently provisions the wrong tree when run from a lane.
_assert_worktree_relative() {
    local script="$1"
    assert "B5c: $script is still invoked worktree-relative via \$(dirname \"\${BASH_SOURCE[0]}\")" \
        bash -c 'grep -Ev "^[[:space:]]*#" "$1" | grep -qF "\$(dirname \"\${BASH_SOURCE[0]}\")/$2"' \
            _ "$SETUP_DEV" "$script"
}
_assert_worktree_relative build-manifold-deps.sh
_assert_worktree_relative provision-warm-lane-fs.sh
_assert_worktree_relative install-warm-lane-units.sh
_assert_worktree_relative setup-main-gate-worktree-config.sh
_assert_worktree_relative setup-agent-cache-redirect.sh

echo ""
echo "--- B6: FALLBACK — main checkout resolves but cannot RUN the scripts ---"

# The branch that matters most and was previously uncovered. B1-B5 above only
# ever drove the happy path (the fixture always committed executable stubs), so
# the fallback assignment, both `warn` lines, and the message shape had no
# coverage at all: an edit that inverted the -x guard or deleted the fallback
# would still have shown every assertion green.
#
# NOTE: this deliberately RE-BINDS the GEN_* globals to a second fixture. B6/B7
# must therefore stay LAST — nothing after them may read the first fixture.
_mk_generator_fixture reify-genfix-noexec main-noexec   # main shell, NOT $( )

# NON-VACUITY, asserted before the run: the fallback branch is only the one
# under test if the main checkout genuinely cannot run the scripts while the
# invoking lane still can. If `chmod -x` had silently applied to both trees (or
# to neither), the assertions below would be measuring some other branch.
assert "B6a: the MAIN checkout's jobserver scripts are NOT executable" \
    bash -c '[ ! -x "$1/scripts/jobserver-balancer.py" ] && [ ! -x "$1/scripts/jobserver-canary.sh" ]' \
        _ "$GEN_MAIN"

assert "B6b: the invoking lane's jobserver scripts ARE still executable" \
    bash -c '[ -x "$1/scripts/jobserver-balancer.py" ] && [ -x "$1/scripts/jobserver-canary.sh" ]' \
        _ "$GEN_LANE"

_GEN2_RC=0
_GEN2_ERR="$GEN_ROOT/generator.err"
_run_generator >"$GEN_ROOT/generator.out" 2>"$_GEN2_ERR" || _GEN2_RC=$?

# The fallback must DEGRADE, not abort: the units still have to be written,
# reloaded and enabled.
assert "B6c: install_build_services() still completes successfully on the fallback path" \
    bash -c '[ "$1" = "0" ] || { cat "$2" >&2; exit 1; }' _ "$_GEN2_RC" "$_GEN2_ERR"

assert "B6d: reify-jobserver.service ExecStart falls back to the INVOKING lane" \
    bash -c '[ "$(grep -E "^ExecStart=" "$1" | head -1)" = "ExecStart=$2/scripts/jobserver-balancer.py" ]' \
        _ "$GEN_UNITS/reify-jobserver.service" "$GEN_LANE"

assert "B6e: reify-jobserver-canary.service ExecStart falls back to the INVOKING lane" \
    bash -c '[ "$(grep -E "^ExecStart=" "$1" | head -1)" = "ExecStart=$2/scripts/jobserver-canary.sh" ]' \
        _ "$GEN_UNITS/reify-jobserver-canary.service" "$GEN_LANE"

# A silent fallback is the failure mode this whole task is about. Pinning at an
# ephemeral lane is survivable when it is ANNOUNCED; it is the silence that let
# the 2026-08-13 incident run for two days.
assert "B6f: the installer WARNS that it pinned at the invoking checkout" \
    grep -qF 'pinning the host-global jobserver units at the invoking checkout' "$_GEN2_ERR"

# Message shape, resolved branch: the warn must name the tree it rejected, so an
# operator reading the journal can see WHICH path lacked the executables.
assert "B6g: the warn names the resolved main checkout, not the <unresolved> placeholder" \
    bash -c 'grep -qF "stable main checkout ($2)" "$1" && ! grep -qF "<unresolved>" "$1"' \
        _ "$_GEN2_ERR" "$GEN_MAIN"

echo ""
echo "--- B7: FALLBACK — the resolver fails outright (<unresolved> message shape) ---"

# The other half of `${main_checkout:-<unresolved>}`: a checkout that is not a
# git worktree at all, so reify_main_checkout() fails closed with EMPTY stdout.
# The installer must still produce working units rather than interpolating an
# empty path into an ExecStart (`ExecStart=/scripts/jobserver-balancer.py`).
_mk_generator_fixture reify-genfix-norepo lane-norepo   # main shell, NOT $( )

assert "B7a: the invoking tree is genuinely outside any git worktree" \
    bash -c '! env -u GIT_DIR -u GIT_WORK_TREE -u GIT_COMMON_DIR -u GIT_INDEX_FILE \
        git -C "$1" rev-parse --git-common-dir >/dev/null 2>&1' _ "$GEN_LANE"

_GEN3_RC=0
_GEN3_ERR="$GEN_ROOT/generator.err"
_run_generator >"$GEN_ROOT/generator.out" 2>"$_GEN3_ERR" || _GEN3_RC=$?

assert "B7b: install_build_services() still completes with an unresolvable main checkout" \
    bash -c '[ "$1" = "0" ] || { cat "$2" >&2; exit 1; }' _ "$_GEN3_RC" "$_GEN3_ERR"

# The point of failing CLOSED: an empty answer must never reach the unit file.
assert "B7c: the emitted ExecStart is an absolute path under the invoking tree, not /scripts/..." \
    bash -c '[ "$(grep -E "^ExecStart=" "$1" | head -1)" = "ExecStart=$2/scripts/jobserver-balancer.py" ]' \
        _ "$GEN_UNITS/reify-jobserver.service" "$GEN_LANE"

assert "B7d: the warn renders the <unresolved> placeholder for an empty resolution" \
    grep -qF 'stable main checkout (<unresolved>)' "$_GEN3_ERR"

echo ""
echo "--- B8: FALLBACK warn is NOT gated on the invoking tree differing ---"

# The case a `[ "$main_checkout" != "$repo_dir" ]` guard on the warn would
# swallow: a standalone clone that IS its own main checkout, whose jobserver
# scripts are missing or non-executable. The units are still about to be pinned
# at a tree that cannot run them — the same 203/EXEC end state — so silence here
# would be the same class of bug as the original defect, just one layer in.
_mk_generator_fixture reify-genfix-mainonly main-only   # main shell, NOT $( )

# NON-VACUITY: this section is only meaningful if the two paths really coincide.
assert "B8a: the invoking tree and the resolved main checkout are the SAME path" \
    bash -c '[ "$1" = "$2" ]' _ "$GEN_LANE" "$GEN_MAIN"

_GEN4_RC=0
_GEN4_ERR="$GEN_ROOT/generator.err"
_run_generator >"$GEN_ROOT/generator.out" 2>"$_GEN4_ERR" || _GEN4_RC=$?

assert "B8b: install_build_services() still completes in the same-tree case" \
    bash -c '[ "$1" = "0" ] || { cat "$2" >&2; exit 1; }' _ "$_GEN4_RC" "$_GEN4_ERR"

assert "B8c: the installer STILL warns when the invoking tree is the main checkout" \
    grep -qF 'pinning the host-global jobserver units at the invoking checkout' "$_GEN4_ERR"

echo ""
echo "--- B9: a failing chmod degrades to a warn, it does not abort the install ---"

# install_build_services() runs under `set -euo pipefail`, and the trailing
# `chmod +x` targets whichever tree was pinned — not necessarily one this uid
# owns. An unguarded failure there aborts AFTER all four units are written but
# BEFORE daemon-reload/enable, leaving stale unreloaded units on disk. Asserting
# rc 0 here is what pins the `|| warn`.
_mk_generator_fixture reify-genfix-nochmod fallback-noscripts   # main shell, NOT $( )

assert "B9a: NON-VACUITY — the pinned tree really does lack the jobserver scripts" \
    bash -c '[ ! -e "$1/scripts/jobserver-balancer.py" ] && [ ! -e "$1/scripts/jobserver-canary.sh" ]' \
        _ "$GEN_LANE"

_GEN5_RC=0
_GEN5_ERR="$GEN_ROOT/generator.err"
_run_generator >"$GEN_ROOT/generator.out" 2>"$_GEN5_ERR" || _GEN5_RC=$?

assert "B9b: install_build_services() completes despite the chmod failing" \
    bash -c '[ "$1" = "0" ] || { cat "$2" >&2; exit 1; }' _ "$_GEN5_RC" "$_GEN5_ERR"

# Deliberately NOT an assertion on unit PRESENCE: the units are written well
# before the chmod, so they would still be there had the install aborted at it.
# Only the systemctl log distinguishes the two.
assert "B9c: it went on to reach the daemon-reload/enable tail" \
    bash -c 'grep -qF "daemon-reload" "$1" && grep -qF "enable --now" "$1"' \
        _ "$GEN_SYSTEMCTL_LOG"

assert "B9d: the chmod failure is reported rather than swallowed" \
    grep -qF 'could not chmod +x the jobserver scripts' "$_GEN5_ERR"

# =============================================================================
# Part C — the BOOT-UNIT generator contract
#   scripts/setup-agent-cache-redirect.sh's install_boot_unit()  (task 6864)
#
# The SECOND host-global unit generator on this host, and until task 6864 the
# one that still resolved the main checkout PRIVATELY, as
# `${REIFY_MAIN_CHECKOUT:-/home/leo/src/reify}` — a hardcoded host default where
# Part B's generator DERIVES the answer from git. The two agreed on the reify
# host and on any host exporting REIFY_MAIN_CHECKOUT, and disagreed SILENTLY on
# a contributor clone or a relocated tree: the redirect script pinned its boot
# unit at a nonexistent /home/leo/src/reify and fell back to $self. This Part
# mirrors Part B one-for-one for that generator.
#
# WHY THIS COVERAGE LIVES HERE AND NOT IN tests/infra/test_agent_cache_redirect.sh:
# every behavioural case in that suite's Block H pins REIFY_MAIN_CHECKOUT
# explicitly — its run_redirect helper hardcodes it so no run can reach the real
# host default, and H8/H11b override it again — and layer 1 of
# reify_main_checkout honours that override verbatim. So no run THERE can
# observe which resolver produced the answer; that suite's behavioural
# assertions are regression coverage, not discrimination. Only a run with REIFY_MAIN_CHECKOUT
# UNSET, inside a real linked worktree, discriminates. That is this Part —
# which makes C1c, not any grep, the assertion a silent revert of the migration
# has to get past. Block H keeps the regression matrix plus one cheap local
# canary (H8d, with H8f as its non-vacuity).
#
# The BU_* globals are deliberately NOT the GEN_* ones Part B uses. Part B's
# sections rebind those in place, and a shared name would suggest the two Parts
# drove the same fixture generator.
# =============================================================================

# ---------------------------------------------------------------------------
# _mk_boot_unit_fixture <stem> [MODE] — MAIN-SHELL ONLY (see
# _mk_two_checkout_fixture for why this sets globals rather than echoing them).
# Sets BU_ROOT/BU_MAIN/BU_LANE/BU_HOME/BU_UNITS/BU_UNIT/BU_SYSTEMCTL_LOG.
#
# MODE selects which branch of install_boot_unit()'s pin decision it drives:
#   lane         (default) a real linked worktree, and the main checkout holds
#                an EXECUTABLE copy of the script -> the PIN is taken, the unit
#                names the main checkout. C1-C4.
#   main-noexec  the main checkout resolves but its copy is NOT executable ->
#                the FALLBACK is taken and the installer warns. C5.
#   lane-norepo  the invoking tree is not a git worktree at all, so
#                reify_main_checkout() fails outright -> fail-open with an EMPTY
#                main_checkout. C6.
#   nolib        the resolver is absent from the invoking tree entirely, so the
#                `-r` source guard is what has to hold. C7.
#   nofunc       the resolver is PRESENT, readable, and sources cleanly — it
#                just defines nothing, because its own source guard is already
#                satisfied. `-r` passes and the `.` succeeds, so the resolution
#                has to come back EMPTY without taking the function down with
#                it. The state C7 structurally cannot reach. C9.
#
# The fallback branches matter disproportionately: they are the ones whose
# guards, if inverted or dropped, silently re-create the original 203/EXEC
# defect — and the script runs under `set -euo pipefail`, so a resolver that
# returns non-zero unguarded would abort a deliberately fail-open provisioning
# step instead.
#
# The script and the resolver are COMMITTED mode 755 BEFORE `git worktree add`,
# so the linked lane checks out its own separate, executable inodes. That
# asymmetry is what lets main-noexec strip the exec bit from the main copy alone.
#
# install_boot_unit() is extracted by column-0 sed anchors and written to
# <fake lane>/scripts/setup-agent-cache-redirect.sh, so ${BASH_SOURCE[0]} inside
# the function resolves to the FAKE LANE — REPRODUCING the invoked-from-a-warm-
# lane trigger rather than simulating it. The full script cannot simply be
# sourced: it is straight-line and would run the whole hardlink pre-seed and the
# sudo'd tmpfiles install long before reaching the function.
# ---------------------------------------------------------------------------
_mk_boot_unit_fixture() {
    local stem="$1" mode="${2:-lane}" root
    _mk_fixture_root "$stem" || return 1
    root="$_FIXTURE_ROOT"
    BU_ROOT="$root"
    BU_MAIN="$root/main"
    BU_LANE="$root/lane"
    BU_HOME="$root/home"
    BU_UNITS="$BU_HOME/.config/systemd/user"
    BU_UNIT="$BU_UNITS/reify-agent-caches.service"

    mkdir -p "$BU_MAIN/scripts" "$BU_HOME/.config" "$root/shim" || return 1

    # The recording `systemctl` (see _write_systemctl_shim). This function also
    # PROBES the --user bus with `show-environment` before doing anything, so
    # the shim is what keeps the whole Part from short-circuiting into the
    # no-bus skip on a CI box. C4 is the case that needs the recording.
    BU_SYSTEMCTL_LOG="$root/systemctl.log"
    _write_systemctl_shim "$root/shim" "$BU_SYSTEMCTL_LOG" || return 1

    # The MAIN checkout holds the executable copy the unit's ExecStart must
    # name, plus the resolver the function sources.
    cp "$REPO_ROOT/scripts/setup-agent-cache-redirect.sh" "$BU_MAIN/scripts/" || return 1
    cp "$REPO_ROOT/scripts/lib_main_checkout.sh" "$BU_MAIN/scripts/" || return 1
    chmod +x "$BU_MAIN/scripts/setup-agent-cache-redirect.sh" || return 1

    _fixture_init_commit "$BU_MAIN" || return 1

    if [ "$mode" = lane-norepo ]; then
        # A plain directory, NOT a worktree: `git worktree add` is skipped
        # entirely so reify_main_checkout() fails outright from this anchor. It
        # still carries the resolver, so the ONLY thing exercised is the
        # unresolvable-anchor branch.
        mkdir -p "$BU_LANE/scripts" || return 1
        cp "$BU_MAIN/scripts/lib_main_checkout.sh" "$BU_LANE/scripts/" || return 1
    else
        _fixture_git -C "$BU_MAIN" worktree add -q --detach "$BU_LANE" >/dev/null 2>&1 || return 1
    fi

    if [ "$mode" = main-noexec ]; then
        # Strip the exec bit in the MAIN checkout ONLY, and only AFTER the
        # worktree add: the lane's copy is a separate inode checked out at the
        # committed mode 755, so it stays runnable. That asymmetry is exactly
        # the shape the fallback exists for — the main checkout resolves, but
        # holds nothing the unit could execute.
        chmod -x "$BU_MAIN/scripts/setup-agent-cache-redirect.sh" || return 1
    fi

    if [ "$mode" = nolib ]; then
        rm -f "$BU_LANE/scripts/lib_main_checkout.sh" || return 1
    fi

    if [ "$mode" = nofunc ]; then
        # REPRODUCED, not simulated: this IS the real lib, with its own source-
        # guard variable pre-set on the line above it. Sourcing it therefore
        # takes the `return 0` at lib_main_checkout.sh's guard and defines
        # NOTHING — precisely what an exported
        # _REIFY_LIB_MAIN_CHECKOUT_SH_SOURCED=1 in the ambient environment does
        # in production, and what a half-written or renamed-function lib does by
        # accident. Unlike nolib, `-r` passes and the `.` succeeds here, so the
        # fail-open outcome has to come from the CALL SITE rather than from the
        # source guard. See C9's banner for what that does and does not pin.
        {
            printf '%s\n' '_REIFY_LIB_MAIN_CHECKOUT_SH_SOURCED=1'
            cat "$BU_MAIN/scripts/lib_main_checkout.sh"
        } > "$BU_LANE/scripts/lib_main_checkout.sh" || return 1
    fi

    mkdir -p "$BU_LANE/scripts" || return 1
    sed -n '/^install_boot_unit() {$/,/^}$/p' \
        "$REPO_ROOT/scripts/setup-agent-cache-redirect.sh" \
        > "$BU_LANE/scripts/setup-agent-cache-redirect.sh" || return 1
    chmod +x "$BU_LANE/scripts/setup-agent-cache-redirect.sh" || return 1
    return 0
}

# ---------------------------------------------------------------------------
# _run_boot_unit — source the extracted function in a sandboxed environment and
# invoke it. HOME and XDG_CONFIG_HOME are the fixture's, PATH is shimmed, and
# the log helpers the script defines at top level (which the extraction
# deliberately does not carry) are stubbed. _warn is echoed to stderr so a
# fallback taken during the run is visible in a failing assert's dump.
#
# `env -u REIFY_MAIN_CHECKOUT` is THE point of this Part: with the override set,
# layer 1 of reify_main_checkout short-circuits the git derivation and the run
# would certify nothing about which resolver is in use. The ambient GIT_* are
# deliberately NOT stripped — the resolver has to neutralize those itself (Part
# A's A6), and a harness that pre-cleaned them would be certifying a posture
# production never has.
# ---------------------------------------------------------------------------
_run_boot_unit() {
    env -u REIFY_MAIN_CHECKOUT \
        HOME="$BU_HOME" \
        XDG_CONFIG_HOME="$BU_HOME/.config" \
        PATH="$BU_ROOT/shim:$PATH" \
        bash -c '
            set -euo pipefail
            _info() { :; }
            _ok()   { :; }
            _warn() { echo "warn: $*" >&2; }
            source "$1"
            install_boot_unit
        ' _ "$BU_LANE/scripts/setup-agent-cache-redirect.sh"
}

# ---------------------------------------------------------------------------
# _no_root_relative_path <file> — 0 when <file> mentions no ROOT-RELATIVE
# `/scripts/setup-agent-cache-redirect.sh`, i.e. the string an EMPTY
# $main_checkout interpolates into.
#
# The literal is a SUFFIX of every legitimate absolute path too, so a plain
# `grep -F` would match always and certify nothing. The match is therefore
# anchored on what PRECEDES it: a legitimate path has a directory-name character
# there, the unresolved one has a delimiter (line start, whitespace, `(`, `=`).
# ---------------------------------------------------------------------------
_no_root_relative_path() {
    ! grep -qE '(^|[^[:alnum:]_.~-])/scripts/setup-agent-cache-redirect\.sh' "$1"
}

echo ""
echo "--- C0: boot-unit fixture (function extracted into a FAKE LANE) ---"

BU_ROOT=""; BU_MAIN=""; BU_LANE=""; BU_HOME=""; BU_UNITS=""; BU_UNIT=""; BU_SYSTEMCTL_LOG=""
_mk_boot_unit_fixture reify-bootfix   # main shell, NOT $( )

_BU_EXTRACT="$BU_LANE/scripts/setup-agent-cache-redirect.sh"

assert "C0a: the extracted snippet is non-empty" \
    test -s "$_BU_EXTRACT"

assert "C0b: the extracted snippet defines install_boot_unit" \
    grep -qF 'install_boot_unit() {' "$_BU_EXTRACT"

assert "C0c: the extracted snippet carries the --seed-only ExecStart" \
    bash -c 'grep -qE "^ExecStart=.* --seed-only$" "$1"' _ "$_BU_EXTRACT"

# The bug's trigger condition: the installer is running from a DIFFERENT tree
# than the one its host-global unit must name.
assert "C0d: the fake lane and the main checkout are DISTINCT paths" \
    bash -c '[ "$1" != "$2" ]' _ "$BU_LANE" "$BU_MAIN"

# NON-VACUITY for C1/C2: if the main copy were not executable the -x guard would
# send us down the fallback and C1 would be measuring some other branch; if the
# lane copy were not, C2 could pass for the wrong reason.
assert "C0e: BOTH the main and the lane copies are executable" \
    bash -c '[ -x "$1/scripts/setup-agent-cache-redirect.sh" ] \
             && [ -x "$2/scripts/setup-agent-cache-redirect.sh" ]' \
        _ "$BU_MAIN" "$BU_LANE"

echo ""
echo "--- C1-C4: derivation from a linked lane pins the MAIN checkout ---"

_BU_RC=0
_BU_ERR="$BU_ROOT/boot.err"
_run_boot_unit >"$BU_ROOT/boot.out" 2>"$_BU_ERR" || _BU_RC=$?

assert "C1a: install_boot_unit() completes successfully in the sandbox" \
    bash -c '[ "$1" = "0" ] || { cat "$2" >&2; exit 1; }' _ "$_BU_RC" "$_BU_ERR"

assert "C1b: it wrote reify-agent-caches.service into the sandboxed unit dir" \
    test -f "$BU_UNIT"

assert "C1c: ExecStart == <main checkout>/scripts/setup-agent-cache-redirect.sh --seed-only" \
    bash -c '[ "$(grep "^ExecStart=" "$1" | head -1)" \
              = "ExecStart=$2/scripts/setup-agent-cache-redirect.sh --seed-only" ]' \
        _ "$BU_UNIT" "$BU_MAIN"

# What gives C5f/C6d/C7d teeth in the other direction. Those three assert the
# fallback warn is PRESENT; without this, a regression that warned
# UNCONDITIONALLY — the `[ -n "$stable" ] && [ -x "$stable" ]` short-circuit
# dropped, or the warn hoisted above the branch — would leave every one of them
# green AND leave C1c/C2/C3 green, because the ExecStart would still be right.
# The suite would then be unable to tell "pinned cleanly" from "pinned correctly
# while shouting a spurious fallback warning at every operator", which is what
# trains operators to ignore the one warn that matters.
assert "C1d: the success path emits NO fallback warn" \
    bash -c '! grep -qF "pinning the boot unit at the invoking copy" "$1"' _ "$_BU_ERR"

# The half that gives C1c teeth: the lane path is what a ${BASH_SOURCE[0]}-derived
# ExecStart would have baked in, and it vanishes the next time that lane is
# reclaimed.
assert "C2: ExecStart is NOT the invoking (warm-lane) copy" \
    bash -c '! grep -qF -- "ExecStart=$2/scripts/setup-agent-cache-redirect.sh" "$1"' \
        _ "$BU_UNIT" "$BU_LANE"

assert "C3: Documentation=file:// also names the MAIN copy, not the lane copy" \
    bash -c 'grep -qF -- "Documentation=file://$2/scripts/setup-agent-cache-redirect.sh" "$1"' \
        _ "$BU_UNIT" "$BU_MAIN"

assert "C4a: systemctl --user daemon-reload was called" \
    bash -c 'grep -qF -- "--user daemon-reload" "$1"' _ "$BU_SYSTEMCTL_LOG"

assert "C4b: systemctl --user enable naming reify-agent-caches.service was called" \
    bash -c 'grep -qE -- "--user enable.*reify-agent-caches\.service" "$1"' _ "$BU_SYSTEMCTL_LOG"

assert "C4c: daemon-reload precedes enable in call order" \
    bash -c '
        r=$(grep -n "daemon-reload" "$1" | head -1 | cut -d: -f1)
        e=$(grep -n "enable.*reify-agent-caches.service" "$1" | head -1 | cut -d: -f1)
        [ -n "$r" ] && [ -n "$e" ] && [ "$r" -lt "$e" ]
    ' _ "$BU_SYSTEMCTL_LOG"

echo ""
echo "--- C5: FALLBACK — the main checkout resolves but holds no executable ---"

# The branch whose guard, if inverted or dropped, silently re-creates the
# original 203/EXEC defect. Each section below RE-BINDS the BU_* globals to a
# fresh fixture, so nothing after a section may read the previous one's.
_mk_boot_unit_fixture reify-bootfix-noexec main-noexec   # main shell, NOT $( )

assert "C5a: NON-VACUITY — the MAIN copy is NOT executable" \
    bash -c '[ ! -x "$1/scripts/setup-agent-cache-redirect.sh" ]' _ "$BU_MAIN"

assert "C5b: NON-VACUITY — the invoking lane copy IS still executable" \
    bash -c '[ -x "$1/scripts/setup-agent-cache-redirect.sh" ]' _ "$BU_LANE"

_BU2_RC=0
_BU2_ERR="$BU_ROOT/boot.err"
_BU2_UNIT="$BU_UNIT"
_run_boot_unit >"$BU_ROOT/boot.out" 2>"$_BU2_ERR" || _BU2_RC=$?

assert "C5c: install_boot_unit() still completes on the fallback path" \
    bash -c '[ "$1" = "0" ] || { cat "$2" >&2; exit 1; }' _ "$_BU2_RC" "$_BU2_ERR"

assert "C5d: the unit is STILL installed" \
    test -f "$_BU2_UNIT"

assert "C5e: ExecStart falls back to the INVOKING lane copy" \
    bash -c '[ "$(grep "^ExecStart=" "$1" | head -1)" \
              = "ExecStart=$2/scripts/setup-agent-cache-redirect.sh --seed-only" ]' \
        _ "$_BU2_UNIT" "$BU_LANE"

# A silent fallback is the failure mode the whole convention exists to prevent:
# pinning at an ephemeral lane is survivable when it is ANNOUNCED.
assert "C5f: the installer WARNS that it pinned at the invoking copy" \
    grep -qF 'pinning the boot unit at the invoking copy' "$_BU2_ERR"

assert "C5g: the warn names the resolved main checkout it rejected" \
    bash -c 'grep -qF -- "$2" "$1"' _ "$_BU2_ERR" "$BU_MAIN"

# The remedy clause is branch-specific, and this is the branch it must NOT
# appear on: the derivation SUCCEEDED here, so telling the operator to set
# REIFY_MAIN_CHECKOUT would point them at a knob that changes nothing. C6e is
# the positive half.
assert "C5h: the warn does NOT offer the REIFY_MAIN_CHECKOUT remedy (it resolved)" \
    bash -c '! grep -qF "set REIFY_MAIN_CHECKOUT" "$1"' _ "$_BU2_ERR"

echo ""
echo "--- C6: FAIL-OPEN — the resolver fails outright (anchor is not a worktree) ---"

_mk_boot_unit_fixture reify-bootfix-norepo lane-norepo   # main shell, NOT $( )

assert "C6a: NON-VACUITY — the invoking tree is genuinely outside any git worktree" \
    bash -c '! env -u GIT_DIR -u GIT_WORK_TREE -u GIT_COMMON_DIR -u GIT_INDEX_FILE \
        git -C "$1" rev-parse --git-common-dir >/dev/null 2>&1' _ "$BU_LANE"

_BU3_RC=0
_BU3_ERR="$BU_ROOT/boot.err"
_BU3_UNIT="$BU_UNIT"
_run_boot_unit >"$BU_ROOT/boot.out" 2>"$_BU3_ERR" || _BU3_RC=$?

# `set -euo pipefail` is live in the extracted function's shell, and
# reify_main_checkout returns NON-ZERO when it cannot resolve. An unguarded call
# would abort here rather than degrade — which is why the rc assertion is the
# first thing this section checks.
assert "C6b: install_boot_unit() still exits 0 with an unresolvable main checkout" \
    bash -c '[ "$1" = "0" ] || { cat "$2" >&2; exit 1; }' _ "$_BU3_RC" "$_BU3_ERR"

assert "C6c: the unit is STILL installed, pinned at the invoking lane copy" \
    bash -c '[ "$(grep "^ExecStart=" "$1" | head -1)" \
              = "ExecStart=$2/scripts/setup-agent-cache-redirect.sh --seed-only" ]' \
        _ "$_BU3_UNIT" "$BU_LANE"

assert "C6d: the installer WARNS that it pinned at the invoking copy" \
    grep -qF 'pinning the boot unit at the invoking copy' "$_BU3_ERR"

# `<unresolved>` says what failed but not what to do about it, and the unit the
# operator is left with is the ephemeral one — the 203/EXEC shape. On this
# branch the warn must therefore name the override that pins it at a stable
# path; C5h is the negative half, on the branch where it would be wrong advice.
assert "C6e: the warn names the REIFY_MAIN_CHECKOUT remedy" \
    grep -qF 'set REIFY_MAIN_CHECKOUT' "$_BU3_ERR"

echo ""
echo "--- C7: FAIL-OPEN — the resolver is not present in the invoking tree ---"

# Proves the `-r` SOURCE GUARD is load-bearing rather than decorative: with the
# file absent, the function must still produce a working unit. It says nothing
# about what happens when the lib is present but defines nothing — `-r`
# short-circuits before anything downstream is reached — which is why C9 exists
# as a separate case rather than as more assertions here.
_mk_boot_unit_fixture reify-bootfix-nolib nolib   # main shell, NOT $( )

assert "C7a: NON-VACUITY — the invoking tree holds no lib_main_checkout.sh" \
    bash -c '[ ! -e "$1/scripts/lib_main_checkout.sh" ]' _ "$BU_LANE"

_BU4_RC=0
_BU4_ERR="$BU_ROOT/boot.err"
_BU4_UNIT="$BU_UNIT"
_run_boot_unit >"$BU_ROOT/boot.out" 2>"$_BU4_ERR" || _BU4_RC=$?

assert "C7b: install_boot_unit() still exits 0 with no resolver available" \
    bash -c '[ "$1" = "0" ] || { cat "$2" >&2; exit 1; }' _ "$_BU4_RC" "$_BU4_ERR"

assert "C7c: the unit is STILL installed, pinned at the invoking lane copy" \
    bash -c '[ "$(grep "^ExecStart=" "$1" | head -1)" \
              = "ExecStart=$2/scripts/setup-agent-cache-redirect.sh --seed-only" ]' \
        _ "$_BU4_UNIT" "$BU_LANE"

assert "C7d: the installer WARNS that it pinned at the invoking copy" \
    grep -qF 'pinning the boot unit at the invoking copy' "$_BU4_ERR"

echo ""
echo "--- C8: an UNRESOLVED main checkout is never rendered as a bare leading / ---"

# The counterpart of Part B's B7d. An empty $main_checkout must not be
# interpolated into a path at all: neither into the unit (which the -x guard
# already prevents) nor into the operator-facing warn, where
# `/scripts/setup-agent-cache-redirect.sh` names a file that exists nowhere and
# tells the reader nothing about what actually failed.
assert "C8a: (lane-norepo) the emitted unit carries no root-relative path" \
    _no_root_relative_path "$_BU3_UNIT"

assert "C8b: (lane-norepo) the warn carries no root-relative path" \
    _no_root_relative_path "$_BU3_ERR"

assert "C8c: (nolib) the emitted unit carries no root-relative path" \
    _no_root_relative_path "$_BU4_UNIT"

assert "C8d: (nolib) the warn carries no root-relative path" \
    _no_root_relative_path "$_BU4_ERR"

echo ""
echo "--- C9: FAIL-OPEN — the resolver sources cleanly but defines nothing ---"

# The present-but-defines-nothing state, which C7 structurally CANNOT reach:
# there the file is absent, so the `-r` guard short-circuits and nothing
# downstream of it is exercised at all. Here `-r` passes and the `.` succeeds,
# and the resolution still has to come back empty without taking the function
# down with it.
#
# Not a contrived state: _REIFY_LIB_MAIN_CHECKOUT_SH_SOURCED is a plain shell
# variable, so an exported value in the ambient environment makes the REAL,
# unmodified lib take its source-guard `return 0` before defining anything —
# which is exactly what this fixture reproduces. A half-written lib, or one
# whose function was renamed, lands in the same state by accident.
#
# WHAT THIS PINS IS THE OUTCOME, NOT WHICH GUARD PRODUCES IT — deliberately, and
# on measurement rather than taste. Deleting install_boot_unit()'s `declare -F`
# guard leaves this entire Part green, because
# `$(reify_main_checkout ... 2>/dev/null || true)` already absorbs the
# command-not-found (exit 127) into an empty string without tripping
# `set -euo pipefail` — probed directly, both by that mutation and standalone.
# The two call-site guards are therefore REDUNDANT here rather than layered, and
# an assertion naming `declare -F` as the load-bearing one would be pinning
# something false. What must hold — and what C9c-C9f pin — is that this state
# degrades fail-open at all, whichever guard gets there first.
_mk_boot_unit_fixture reify-bootfix-nofunc nofunc   # main shell, NOT $( )

assert "C9a: NON-VACUITY — the lib IS present and readable in the invoking tree" \
    bash -c '[ -r "$1/scripts/lib_main_checkout.sh" ]' _ "$BU_LANE"

assert "C9b: NON-VACUITY — sourcing it defines no reify_main_checkout" \
    bash -c '. "$1" >/dev/null 2>&1; ! declare -F reify_main_checkout >/dev/null 2>&1' \
        _ "$BU_LANE/scripts/lib_main_checkout.sh"

_BU5_RC=0
_BU5_ERR="$BU_ROOT/boot.err"
_BU5_UNIT="$BU_UNIT"
_run_boot_unit >"$BU_ROOT/boot.out" 2>"$_BU5_ERR" || _BU5_RC=$?

assert "C9c: install_boot_unit() still exits 0 when the lib defines nothing" \
    bash -c '[ "$1" = "0" ] || { cat "$2" >&2; exit 1; }' _ "$_BU5_RC" "$_BU5_ERR"

assert "C9d: the unit is STILL installed, pinned at the invoking lane copy" \
    bash -c '[ "$(grep "^ExecStart=" "$1" | head -1)" \
              = "ExecStart=$2/scripts/setup-agent-cache-redirect.sh --seed-only" ]' \
        _ "$_BU5_UNIT" "$BU_LANE"

assert "C9e: the installer WARNS that it pinned at the invoking copy" \
    grep -qF 'pinning the boot unit at the invoking copy' "$_BU5_ERR"

assert "C9f: the warn carries no root-relative path" \
    _no_root_relative_path "$_BU5_ERR"

# -- Summary ------------------------------------------------------------------
test_summary
