#!/usr/bin/env bash
# Scheduled README + getting-started audit. Run by
# ~/.config/systemd/user/reify-readme-review.timer every 4 days.
#
# Invokes Claude Code in non-interactive mode to compare the docs against
# the current state of the repo and patch any drift; claude only edits files.
# The edit lands as a hook-gated commit by the review-readme machine identity
# and is never pushed: docs/notes/unattended-writers-of-main.md.
#
# Manual invocation (for testing):
#   scripts/review-readme.sh
#
# Logs to logs/readme-review-<timestamp>.log.
#
# Exit status:
#   0   no drift, or the edit was committed
#   1   refused: off main, a target untracked at HEAD, no claude CLI, or the commit was refused (edit kept in <log>.refused.patch)
#   75  deferred: a target already differs from HEAD (human WIP), so claude was not run

set -euo pipefail

# shellcheck source=scripts/lib_main_checkout.sh
source "$(dirname "${BASH_SOURCE[0]}")/lib_main_checkout.sh"

REPO="$(reify_main_checkout)" || { echo "ERROR: cannot resolve the main checkout" >&2; exit 1; }
CLAUDE_BIN="${CLAUDE_BIN:-/home/leo/.local/bin/claude}"
TARGET_FILES=(README.md docs/getting-started.md)
readonly WRITER_ID=review-readme
readonly WRITER_EMAIL="${WRITER_ID}@automation.reify.invalid"

cd "$REPO"

mkdir -p logs
LOG="logs/readme-review-$(date +%Y%m%d-%H%M%S).log"

# Only a clean, gated state may reach the session: on any branch but main the
# commit would skip hooks/pre-commit, and a target that is untracked or already
# dirty would make the machine commit absorb (or the restore destroy) human WIP.
preflight() {
    local f
    if [ "$(git symbolic-ref --short -q HEAD)" != main ]; then
        echo "REFUSE: main checkout is not on main (pre-commit gates only main)"
        exit 1
    fi
    for f in "${TARGET_FILES[@]}"; do
        if ! git cat-file -e "HEAD:$f" 2>/dev/null; then
            echo "REFUSE: $f not tracked at HEAD"
            exit 1
        fi
    done
    if ! git diff --quiet HEAD -- "${TARGET_FILES[@]}" \
        || ! git diff --cached --quiet HEAD -- "${TARGET_FILES[@]}"; then
        echo "DEFER: uncommitted changes to target files; not overwriting human WIP"
        exit 75
    fi
}

# Commit the target files through the pre-commit gate as the machine identity.
# A refused commit leaves no trace in the checkout: the edit is saved beside
# the log, the targets are restored to HEAD, and the run exits 1.
land_or_quarantine() {
    local rc=0 patch
    GIT_AUTHOR_NAME="$WRITER_ID" GIT_AUTHOR_EMAIL="$WRITER_EMAIL" \
    GIT_COMMITTER_NAME="$WRITER_ID" GIT_COMMITTER_EMAIL="$WRITER_EMAIL" \
        git commit --only -m "docs: scheduled 4-day README/getting-started review

Auto-generated by scripts/review-readme.sh via
~/.config/systemd/user/reify-readme-review.timer." -- "${TARGET_FILES[@]}" || rc=$?

    if [ "$rc" -eq 0 ]; then
        echo "committed $(git rev-parse --short HEAD) (publication to origin is the merge worker's post-advance push)"
        return 0
    fi

    patch="${LOG%.log}.refused.patch"
    git diff --binary HEAD -- "${TARGET_FILES[@]}" > "$patch"
    git restore --source=HEAD --staged --worktree -- "${TARGET_FILES[@]}"
    echo "commit refused (rc=$rc); edit quarantined at $patch; targets restored to HEAD"
    exit 1
}

{
    echo "=== reify-readme-review @ $(date -Iseconds) ==="

    if [ ! -x "$CLAUDE_BIN" ]; then
        echo "ERROR: claude CLI not executable at $CLAUDE_BIN"
        exit 1
    fi

    preflight

    PROMPT='You are auditing the Reify project documentation. The repo is your working directory.

Goal: keep README.md and docs/getting-started.md accurate as the codebase evolves. Make ONLY corrections to existing claims; do not expand scope, add new sections, or restructure.

Steps:
1. Read README.md and docs/getting-started.md.
2. Run "git log --oneline -50" to see recent changes. Skim commits that look like they might affect documented behavior (CLI changes, new features, removed examples, build-system changes).
3. Build and run the CLI to verify documented behavior:
   - "cargo build --release -p reify-cli" if target/release/reify is missing.
   - "./target/release/reify --help" — confirm command list in README matches.
   - "./target/release/reify --version" — confirm it works.
   - "./target/release/reify check examples/m5_geometry.ri" — confirm the smoke-test command in README still works.
4. Verify scripts/setup-dev.sh, scripts/run-gui.sh, scripts/run-gui-dev.sh still exist and roughly match what the README claims they do.
5. Update README.md or docs/getting-started.md to fix any drift you find. Edit in place; do not create new files. Do not touch any other files.
6. If everything is current, change nothing and exit. Conservatism wins.

Do NOT commit, push, or use git mutating commands. The wrapper script handles that.'

    echo "--- claude session ---"
    "$CLAUDE_BIN" -p "$PROMPT" \
        --dangerously-skip-permissions \
        --max-turns 40 \
        --output-format text \
        || echo "(claude exited $?)"
    echo "--- end claude session ---"

    if git diff --quiet HEAD -- "${TARGET_FILES[@]}"; then
        echo "no changes against HEAD — done"
        exit 0
    fi

    echo "changes detected; committing target files only"
    land_or_quarantine

    echo "=== done ==="
} 2>&1 | tee -a "$LOG"
