#!/usr/bin/env bash
# Scheduled README + getting-started audit. Run by
# ~/.config/systemd/user/reify-readme-review.timer every 4 days.
#
# Invokes Claude Code in non-interactive mode to compare the docs against
# the current state of the repo and patch any drift. The wrapper handles
# the git plumbing — claude only edits files.
#
# Manual invocation (for testing):
#   scripts/review-readme.sh
#
# Logs to logs/readme-review-<timestamp>.log.

set -euo pipefail

REPO="/home/leo/src/reify"
CLAUDE_BIN="${CLAUDE_BIN:-/home/leo/.local/bin/claude}"
TARGET_FILES=(README.md docs/getting-started.md)

cd "$REPO"

mkdir -p logs
LOG="logs/readme-review-$(date +%Y%m%d-%H%M%S).log"

{
    echo "=== reify-readme-review @ $(date -Iseconds) ==="

    if [ ! -x "$CLAUDE_BIN" ]; then
        echo "ERROR: claude CLI not executable at $CLAUDE_BIN"
        exit 1
    fi

    # Capture pre-state hashes so we can detect whether claude actually
    # touched the target files. We tolerate missing files (hash to "").
    hash_targets() {
        for f in "${TARGET_FILES[@]}"; do
            if [ -f "$f" ]; then
                git hash-object "$f"
            else
                echo "missing"
            fi
        done | sha256sum | awk '{print $1}'
    }
    BEFORE=$(hash_targets)
    echo "before-hash: $BEFORE"

    PROMPT='You are auditing the Reify project documentation. The repo is at /home/leo/src/reify.

Goal: keep README.md and docs/getting-started.md accurate as the codebase evolves. Make ONLY corrections to existing claims; do not expand scope, add new sections, or restructure.

Steps:
1. Read README.md and docs/getting-started.md.
2. Run "git log --oneline -50" to see recent changes. Skim commits that look like they might affect documented behavior (CLI changes, new features, removed examples, build-system changes).
3. Build and run the CLI to verify documented behavior:
   - "cargo build --release -p reify-cli" if target/release/reify is missing.
   - "./target/release/reify --help" — confirm command list in README matches.
   - "./target/release/reify --version" — confirm it works.
   - "./target/release/reify check examples/m5_geometry.ri" — confirm the smoke-test command in README still works.
4. Verify scripts/setup-dev.sh, scripts/run-gui.sh, scripts/run-gui-dev.sh still exist and roughly match what the README claims they do.
5. Update README.md or docs/getting-started.md to fix any drift you find. Edit in place; do not create new files. Do not touch any other files.
6. If everything is current, change nothing and exit. Conservatism wins.

Do NOT commit, push, or use git mutating commands. The wrapper script handles that.'

    echo "--- claude session ---"
    "$CLAUDE_BIN" -p "$PROMPT" \
        --dangerously-skip-permissions \
        --max-turns 40 \
        --output-format text \
        || echo "(claude exited $?)"
    echo "--- end claude session ---"

    AFTER=$(hash_targets)
    echo "after-hash:  $AFTER"

    if [ "$BEFORE" = "$AFTER" ]; then
        echo "no changes — done"
        exit 0
    fi

    echo "changes detected; staging + committing target files only"
    git add -- "${TARGET_FILES[@]}"

    if git diff --cached --quiet -- "${TARGET_FILES[@]}"; then
        echo "nothing staged after add (perhaps claude reverted) — done"
        exit 0
    fi

    git -c user.name="Leo Dawn" -c user.email="leo@leodearden.org" commit -m "docs: scheduled 4-day README/getting-started review

Auto-generated by scripts/review-readme.sh via
~/.config/systemd/user/reify-readme-review.timer."

    if git push origin main; then
        echo "pushed to origin/main"
    else
        echo "WARN: git push failed (rc=$?); local commit kept, will retry next cycle"
    fi

    echo "=== done ==="
} 2>&1 | tee -a "$LOG"
