#!/usr/bin/env bash
# Regenerate tree-sitter parser from grammar.js.
# Produces: src/parser.c, src/grammar.json, src/node-types.json
#
# This script is idempotent — safe to run repeatedly.
# Called by: build.rs (auto), orchestrator verification, hooks/project-checks.
# Usage: tree-sitter-generate.sh [--force]

set -euo pipefail

FORCE=false
if [ "${1:-}" = "--force" ]; then
    FORCE=true
fi

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TS_DIR="$(cd "$SCRIPT_DIR/../tree-sitter-reify" && pwd)"

if ! command -v tree-sitter >/dev/null 2>&1; then
    echo "ERROR: tree-sitter CLI not found on PATH." >&2
    echo "Install via: cargo install tree-sitter-cli" >&2
    exit 1
fi

if [ ! -f "$TS_DIR/grammar.js" ]; then
    echo "ERROR: $TS_DIR/grammar.js not found." >&2
    exit 1
fi

# Portable SHA-256: prefer sha256sum (GNU coreutils), fall back to shasum (macOS).
compute_sha256() {
    if command -v sha256sum >/dev/null 2>&1; then
        sha256sum "$1"
    elif command -v shasum >/dev/null 2>&1; then
        shasum -a 256 "$1"
    else
        echo "ERROR: neither sha256sum nor shasum found on PATH." >&2
        exit 1
    fi
}

cd "$TS_DIR"

# Compute grammar hash once before generation (avoids TOCTOU race between
# staleness check and stamp write — same pattern as build.rs).
GRAMMAR_HASH=$(compute_sha256 grammar.js | awk '{print $1}')
STAMP_FILE="src/.grammar_hash.stamp"

# Staleness check: skip generation if stamp matches and all outputs exist.
# --force bypasses this check entirely.
if [ "$FORCE" = false ]; then
    STALE=false
    if [ ! -f "$STAMP_FILE" ]; then
        STALE=true
    elif [ "$(cat "$STAMP_FILE" 2>/dev/null)" != "$GRAMMAR_HASH" ]; then
        STALE=true
    else
        for f in src/parser.c src/grammar.json src/node-types.json; do
            if [ ! -f "$f" ]; then
                STALE=true
                break
            fi
        done
    fi

    if [ "$STALE" = false ]; then
        echo "tree-sitter: up to date (grammar.js unchanged)"
        exit 0
    fi
fi

# Acquire exclusive advisory lock to prevent concurrent generation from
# corrupting parser.c/grammar.json/node-types.json via interleaved writes.
LOCK_FILE="src/.generate.lock"
exec 9>"$LOCK_FILE"
flock -x 9

# Re-check staleness inside lock — another process may have regenerated
# while we waited for the lock (double-check-locking pattern).
GRAMMAR_HASH=$(compute_sha256 grammar.js | awk '{print $1}')
if [ "$FORCE" = false ]; then
    STALE=false
    if [ ! -f "$STAMP_FILE" ]; then
        STALE=true
    elif [ "$(cat "$STAMP_FILE" 2>/dev/null)" != "$GRAMMAR_HASH" ]; then
        STALE=true
    else
        for f in src/parser.c src/grammar.json src/node-types.json; do
            if [ ! -f "$f" ]; then
                STALE=true
                break
            fi
        done
    fi

    if [ "$STALE" = false ]; then
        echo "tree-sitter: up to date (regenerated by another process)"
        exit 0
    fi
fi

GEN_EXIT=0
timeout 60 tree-sitter generate || GEN_EXIT=$?
if [ "$GEN_EXIT" -eq 124 ]; then
    echo "ERROR: tree-sitter generate timed out after 60s" >&2
    exit 1
elif [ "$GEN_EXIT" -ne 0 ]; then
    echo "ERROR: tree-sitter generate failed (exit code $GEN_EXIT)" >&2
    exit 1
fi

# Verify expected outputs exist.
for f in src/parser.c src/grammar.json src/node-types.json; do
    if [ ! -f "$f" ]; then
        echo "ERROR: tree-sitter generate did not produce $f" >&2
        exit 1
    fi
done

# Write stamp file with the pre-computed hash.
echo -n "$GRAMMAR_HASH" > "$STAMP_FILE"

# Lock released automatically when script exits (fd 9 is closed).
echo "tree-sitter: generated parser files in $TS_DIR/src/"
