#!/usr/bin/env bash
# Regenerate tree-sitter parser from grammar.js.
# Produces: src/parser.c, src/grammar.json, src/node-types.json
#
# This script is idempotent — safe to run repeatedly.
# Called by: build.rs (auto), orchestrator verification, hooks/project-checks.
# Usage: tree-sitter-generate.sh [--force]

set -euo pipefail

FORCE=false
if [ "${1:-}" = "--force" ]; then
    FORCE=true
fi

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TS_DIR="$(cd "$SCRIPT_DIR/../tree-sitter-reify" && pwd)"

# Maximum seconds to wait for lock acquisition (used by flock and stale-age check).
MAX_WAIT_SECS=120
# Maximum polling iterations for mkdir-based lock (75 × 1s = 75s < MAX_WAIT_SECS).
# Keeping these separate preserves the ~45s safety buffer between giving up and
# treating a lock as stale — the original design intent.
MAX_LOCK_ATTEMPTS=75

if ! command -v tree-sitter >/dev/null 2>&1; then
    echo "ERROR: tree-sitter CLI not found on PATH." >&2
    echo "Install via: cargo install tree-sitter-cli" >&2
    exit 1
fi

if [ ! -f "$TS_DIR/grammar.js" ]; then
    echo "ERROR: $TS_DIR/grammar.js not found." >&2
    exit 1
fi

# Shared utilities (compute_sha256, etc.)
source "$SCRIPT_DIR/lib.sh"

cd "$TS_DIR"

# Compute grammar hash once before generation (avoids TOCTOU race between
# staleness check and stamp write — same pattern as build.rs).
GRAMMAR_HASH=$(compute_sha256 grammar.js | awk '{print $1}')
STAMP_FILE="src/.grammar_hash.stamp"

# Staleness check: skip generation if stamp matches and all outputs exist.
# --force bypasses this check entirely.
if [ "$FORCE" = false ]; then
    STALE=false
    if [ ! -f "$STAMP_FILE" ]; then
        STALE=true
    elif [ "$(cat "$STAMP_FILE" 2>/dev/null)" != "$GRAMMAR_HASH" ]; then
        STALE=true
    else
        for f in src/parser.c src/grammar.json src/node-types.json; do
            if [ ! -f "$f" ]; then
                STALE=true
                break
            fi
        done
    fi

    if [ "$STALE" = false ]; then
        echo "tree-sitter: up to date (grammar.js unchanged)"
        exit 0
    fi
fi

# Acquire exclusive advisory lock to prevent concurrent generation from
# corrupting parser.c/grammar.json/node-types.json via interleaved writes.
# Uses flock on Linux; falls back to mkdir-based lock on macOS/other POSIX.
LOCK_FILE="src/.generate.lock"
LOCK_DIR="src/.generate.lock.d"

if command -v flock >/dev/null 2>&1; then
    exec 9>"$LOCK_FILE"
    if ! flock -x -w $MAX_WAIT_SECS 9; then
        echo "ERROR: could not acquire flock within ${MAX_WAIT_SECS}s" >&2
        exit 1
    fi
else
    # Portable mkdir-based advisory lock (atomic on POSIX).
    # Retry with backoff; stale locks are cleaned up after MAX_WAIT_SECS.
    _lock_attempts=0
    while ! mkdir "$LOCK_DIR" 2>/dev/null; do
        _lock_attempts=$((_lock_attempts + 1))
        if [ "$_lock_attempts" -ge $MAX_LOCK_ATTEMPTS ]; then
            # Stale lock detection: if lock dir is older than MAX_WAIT_SECS, remove it.
            # Use empty sentinel when stat fails — refuse to remove a lock
            # we cannot verify as stale (avoids unconditional removal on
            # platforms where neither GNU nor BSD stat is available).
            if [ -d "$LOCK_DIR" ]; then
                _lock_mtime=$(stat -c %Y "$LOCK_DIR" 2>/dev/null || stat -f %m "$LOCK_DIR" 2>/dev/null || echo '')
                if [ -n "$_lock_mtime" ]; then
                    _lock_age=$(( $(date +%s) - _lock_mtime ))
                    if [ "$_lock_age" -ge $MAX_WAIT_SECS ]; then
                        echo "WARNING: removing stale lock dir (age=${_lock_age}s)" >&2
                        if rmdir "$LOCK_DIR" 2>/dev/null; then
                            _lock_attempts=0
                            continue
                        fi
                        # rmdir failed (e.g. NFS/uid-mismatch) — sleep to
                        # avoid tight busy-loop, then retry
                        sleep 1
                        continue
                    fi
                fi
            fi
            echo "ERROR: could not acquire generation lock after $MAX_LOCK_ATTEMPTS attempts" >&2
            exit 1
        fi
        sleep 1
    done
    # Ensure lock dir is removed on exit
    trap 'rmdir "$LOCK_DIR" 2>/dev/null || true' EXIT
fi

# Re-check staleness inside lock — another process may have regenerated
# while we waited for the lock (double-check-locking pattern).
GRAMMAR_HASH=$(compute_sha256 grammar.js | awk '{print $1}')
if [ "$FORCE" = false ]; then
    STALE=false
    if [ ! -f "$STAMP_FILE" ]; then
        STALE=true
    elif [ "$(cat "$STAMP_FILE" 2>/dev/null)" != "$GRAMMAR_HASH" ]; then
        STALE=true
    else
        for f in src/parser.c src/grammar.json src/node-types.json; do
            if [ ! -f "$f" ]; then
                STALE=true
                break
            fi
        done
    fi

    if [ "$STALE" = false ]; then
        echo "tree-sitter: up to date (regenerated by another process)"
        exit 0
    fi
fi

GEN_EXIT=0
# Use portable_timeout from lib_portable.sh (sourced via lib.sh above).
portable_timeout 60 tree-sitter generate || GEN_EXIT=$?
if [ "$GEN_EXIT" -eq 124 ] && [ "${_PORTABLE_TIMEOUT_TIMED_OUT:-false}" = "true" ]; then
    echo "ERROR: tree-sitter generate timed out after 60s" >&2
    # Remove any partial output files left by the killed process to prevent
    # corrupted parser.c/grammar.json/node-types.json from being used.
    rm -f src/parser.c src/grammar.json src/node-types.json
    exit 1
elif [ "$GEN_EXIT" -ne 0 ]; then
    echo "ERROR: tree-sitter generate failed (exit code $GEN_EXIT)" >&2
    exit 1
fi

# Verify expected outputs exist.
for f in src/parser.c src/grammar.json src/node-types.json; do
    if [ ! -f "$f" ]; then
        echo "ERROR: tree-sitter generate did not produce $f" >&2
        exit 1
    fi
done

# Write stamp file with the pre-computed hash.
echo -n "$GRAMMAR_HASH" > "$STAMP_FILE"

# Lock released automatically when script exits (fd 9 is closed).
echo "tree-sitter: generated parser files in $TS_DIR/src/"
