// Snapshot diffing for GUI state.
//
// Pure functions that compare consecutive GuiState snapshots and produce
// minimal deltas for targeted event emission. No tauri dependency.
//
// `StateDelta`, `diff_gui_state`, and `delta_to_events` are generated by the
// `gui_state!` macro (PRD `docs/prds/v0_6/gui-state-sync.md` §8 L5, task
// #5034) from the single schema definition at `crate::types::GuiState` — see
// `gui_state_schema.rs` for the macro and `types.rs` for the invocation.
// Re-exported here (`pub use` below) so every existing
// `crate::diff::{StateDelta, diff_gui_state, delta_to_events}` import path
// (main.rs, debug_server.rs, test modules) is unchanged.

use std::sync::Mutex;

use tracing::warn;

use crate::types::GuiState;

pub use crate::types::{StateDelta, delta_to_events, diff_gui_state};

/// Push a serialized event onto `events`, or a structured error event on failure.
///
/// On `Ok(val)`: pushes `(event_name, val)`.
/// On `Err(err)`: emits a `warn!` and pushes a `"serialization-error"` event
/// with `item_type`, `item_id`, and `error` fields.
///
/// `pub` (bumped from `pub(crate)` for L5, task #5034) so the `gui_state!`
/// macro's generated `events_fn` bodies (invoked from `crate::types`) can
/// reach it, in addition to the test module in `src/tests/`. This also
/// includes the macro's external-crate doctests in `gui_state_schema.rs`:
/// the `compile_fail` ones never expand to code that calls it (classifying
/// a field is what makes the call site exist at all), but the `diffed
/// keyed` positive doctest does — it invokes the generated `events_fn` and
/// so exercises this `pub` path for real, not just by assertion.
pub fn push_serialized_event(
    events: &mut Vec<(String, serde_json::Value)>,
    event_name: &str,
    item_type: &str,
    item_id: &str,
    result: Result<serde_json::Value, serde_json::Error>,
) {
    match result {
        Ok(val) => events.push((event_name.to_string(), val)),
        Err(err) => {
            warn!("failed to serialize {item_type} {item_id}: {err}");
            events.push((
                "serialization-error".to_string(),
                serde_json::json!({
                    "item_type": item_type,
                    "item_id": item_id,
                    "error": err.to_string(),
                }),
            ));
        }
    }
}

/// Compute a delta against the last known state, then store the new state.
///
/// If `last_state` is `None` (first call), returns a full delta.
/// Otherwise diffs against the previous state and returns the minimal delta.
pub fn compute_delta(last_state: &Mutex<Option<GuiState>>, new_state: &GuiState) -> StateDelta {
    let mut guard = last_state.lock().unwrap_or_else(|e| e.into_inner());
    let delta = match guard.as_ref() {
        Some(old) => diff_gui_state(old, new_state),
        None => StateDelta::full(new_state),
    };
    *guard = Some(new_state.clone());
    delta
}
